### ISSUE TITLE
unknown encoding name - CP720 while "ridk.cmd install"  

### ISSUE THREAD

**Issue by BudiKusasi** [oneclick/rubyinstaller2#100]
I installed Ruby 2.5.0p in dir. D:\APP\Ruby25\bin, and did: 
```
D:\APP\Ruby25\bin>ridk.cmd install
Traceback (most recent call last):
        13: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
        12: from <internal:gem_prelude>:2:in `require'
        11: from D:/APP/Ruby25/lib/ruby/2.5.0/rubygems.rb:1388:in `<top (required)>'
        10: from D:/APP/Ruby25/lib/ruby/2.5.0/rubygems.rb:1388:in `require'
         9: from D:/APP/Ruby25/lib/ruby/2.5.0/rubygems/defaults/operating_system.rb:3:in `<top (required)>'
         8: from D:/APP/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/singleton.rb:27:in `enable_dll_search_paths'
         7: from D:/APP/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/msys2_installation.rb:96:in `enable_dll_search_paths'
         6: from D:/APP/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/msys2_installation.rb:86:in `mingw_bin_path'
         5: from D:/APP/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/msys2_installation.rb:73:in `msys_path'
         4: from D:/APP/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/msys2_installation.rb:46:in `iterate_msys_paths'
         3: from D:/APP/Ruby25/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/msys2_installation.rb:46:in `require'
         2: from D:/APP/Ruby25/lib/ruby/2.5.0/win32/registry.rb:4:in `<top (required)>'
         1: from D:/APP/Ruby25/lib/ruby/2.5.0/win32/registry.rb:72:in `<module:Win32>'
D:/APP/Ruby25/lib/ruby/2.5.0/win32/registry.rb:72:in `find': unknown encoding name - CP720 (ArgumentError)
```

What's caused this and how to solve it ?
Thanks in advance..

**Comment by larskanis** [comment]
Unfortunately CP720 is not yet supported in ruby. This is a [known bug](https://bugs.ruby-lang.org/issues/13831), but no one stepped in so far to fix it. The workaround is to change the console codepage like:
```
chcp 1252
```
.. and issue the failing command again.

**Comment by larskanis** [comment]
Did changing the codepage work for you? If so I would like to close this issue.

**Comment by hasanzadegan** [comment]
goto 
registry.rb 

replace LOCALE = Encoding.find(Encoding.locale_charmap)
to
LOCALE = Encoding::UTF_8

**Comment by farghly** [comment]
This problem has two solution
first solution write in command line 
`chcp 1252`
Second solution modified line 72 of registry.rb (in RailsInstaller\Ruby2.1.0\lib\ruby\2.1.0\win32)
change this line 
`LOCALE = Encoding.find(Encoding.locale_charmap)`
To this one

`LOCALE = Encoding::UTF_8`
Second solution is ths best forever
![Second solution gif](https://user-images.githubusercontent.com/14139322/110253585-d4ad9d80-7f93-11eb-9a7e-ae23f1776d27.gif)
