### ISSUE TITLE
Rmagick gem: module not found (Ruby 2.4 only)

### ISSUE THREAD

**Issue by deining** [oneclick/rubyinstaller2#102]
Hi,

I have two parallel installtaions of Ruby 2.3.3 and Ruby 2.4.3 on my Windows box (Windows Server 2012).

With both installations, I can successfully install rmagick gem, latest version 2.16.0.

```
C:\>gem list rmagick

*** LOCAL GEMS ***

rmagick (2.16.0)
```

With ruby 2.3, I can make use of installed gem without problems:
```
C:\Ruby233\bin>irb
irb(main):001:0> require 'rmagick'
=> true
irb(main):002:0>
```
With ruby 2.4, I'm running into trouble when trying to use the gem:
```
C:\Ruby2.4.3\bin>irb.cmd
irb(main):001:0> require 'rmagick'
LoadError: 126: Das angegebene Modul wurde nicht gefunden.   - C:/Ruby2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/lib/RMagick2.so
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Ruby2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/lib/rmagick_internal.rb:12:in `<top (required)>'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby2.4.3/lib/ruby/gems/2.4.0/gems/rmagick-2.16.0/lib/rmagick.rb:1:in `<top (required)>'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby2.4.3/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby2.4.3/bin/irb.cmd:19:in `<main>'
irb(main):002:0>
```
I'm not sure whether this issue is related to rmagick itself or the rubyinstaller2.
I asked for help on the rmagick site [(issue 291)](https://github.com/rmagick/rmagick/issues/291) already, to no avail up to yet.

Maybe you have an idea how to resolve this issue?

Thanks in advance.

**Comment by larskanis** [comment]
The RMagick installation is really cumbersome. The point you missed for Ruby 2.4 is copying the dlls from the ImageMagick directory to C:/Ruby2.4.3/bin.

If RMagick would support the latest ImageMagick version, it could install+use ImageMagick from the [MSYS2/MINGW repository](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-imagemagick) per [gemspec dependency](https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency). But [it doesn't](https://github.com/rmagick/rmagick/issues/256). Hopefully someone takes this project over and fixes this.

**Comment by deining** [comment]
Thanks for the tip, it now works!

Additional hint for affected users:
Be sure to copy **all** dll to the directory, not only those dll's starting with _CORE_RL_..._ !!!

**Comment by trinhcanhphuc** [comment]
Thank you so much. I have copied all dll files from ImageMagick directory to C:/Ruby/bin and this problem has been resolved <3

**Comment by trinhcanhphuc** [comment]
> The RMagick installation is really cumbersome. The point you missed for Ruby 2.4 is copying the dlls from the ImageMagick directory to C:/Ruby2.4.3/bin.
> 
> If RMagick would support the latest ImageMagick version, it could install+use ImageMagick from the [MSYS2/MINGW repository](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-imagemagick) per [gemspec dependency](https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency). But [it doesn't](https://github.com/rmagick/rmagick/issues/256). Hopefully someone takes this project over and fixes this.

Thank you so much. I have copied all dll files from ImageMagick directory to C:/Ruby/bin and this problem has been resolved <3
