### ISSUE TITLE
How to Uninstall

### ISSUE THREAD

**Issue by ismael-rivera** [oneclick/rubyinstaller2#104]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
Not specifically sure. Installer rubyinstaller-2.4.3-2-x64 ran it's course. It's possible that I might have accidentally skipped something but I'm not entirely sure. All I know is once ruby installer had "apparently finished'', MSYS2 began to install. Once THAT was done, a terminal window opened automatically and... well, I was unable to write anything. The terminal window for msys2 was unresponsive and I had to force it to quit. Very strange. Afterwards, I reopened a command prompt both windows and msys2. Nothing was working. The gem commands were not to be found and same with msys2.

## Steps to reproduce
Again, I'm not entirely sure what happened. The process repeated itself once it was done, this time through the command prompt. I would like to uninstall everything and begin from scratch so I can better assess what I did and locate the

## What's the output from `ridk version`?
not sure what this is.

**Comment by ismael-rivera** [comment]
The ridk version is rubyinstaller-2.4.3-2-x64

**Comment by ismael-rivera** [comment]
UPDATE:
Uninstalling MSYS2 was pretty obvious. Control Panel(duh right?). In my defense, I've been using Macs for over 8 years. Just a week ago made the switch. Control Panel uninstaller is not something I'm used to having. Ruby on the other hand was not even on the programs list. Not sure if it's a CLI thing but I can't seem to find the files so it's possible the installer never got it ready. Not sure. Anyways I will try again, see if it happens/.

**Comment by larskanis** [comment]
RubyInstaller should be in "Add/Remove Programs" so that you can uninstall it. Alternatively you can run `c:/Ruby24-x64/unins000.exe` or just remove the directory `c:/Ruby24-x64` with the explorer.

With the [latest release](https://rubyinstaller.org/2018/03/29/rubyinstaller-2.5.1-1-and-2.4.4-1-released.html) there is a easier way to install ruby: Ruby+Devkit. It installs the MSYS2-Devkit within the Ruby path with no additional downloads.

To be able to use Ruby from command prompt, make sure to enable the "Add Ruby to PATH" box in the installer. After the installer has finished, you have to open a new command prompt from the start menu so that this change gets active. Then you should be able to run the `ridk version` command (and other as well).

**Comment by OwenMcDonnell** [comment]
I don't really want to start an issue, but i'm curious about a couple things. First, how it is that the ruby installer exe is larger than space needed for ruby installation. And second, does the devkit/msys really require over 700MB of disk space!?

**Comment by abidkhalid751** [comment]
how to install ruby?

**Comment by jonovik** [comment]
To anyone else googling for how to uninstall RubyInstaller:
On Windows 10 with Ruby 2.5.5, I did not see Ruby listed in "Add or remove programs".
However, there was an uninstaller in `C:\Ruby25-x64\unins000.exe` which worked fine.

**Comment by hrk1l2x** [comment]
If you want to uninstall silently, you can run `C:\Ruby2*\unins001.exe /verysilent`

**Comment by mohits** [comment]
Ok! Documented here: https://notepad.onghu.com/2022/uninstalling-ruby-on-windows/ - I will also see how to add it to the wiki.

**Comment by mohits** [comment]
Hi @larskanis - I don't think I can edit the wiki but the content for the FAQ is as below for you/ someone to copy it there.


How do I uninstall RubyInstaller2?
You can uninstall RubyInstaller in any of the following ways:
# From the Start Menu: If you have a classic start menu, you can navigate to Programs > Ruby XX and select the option to Uninstall Ruby.
# From Add or Remove Programs: Navigate to the Add or Remove Programs settings menu in Windows and find the Ruby Version you want to uninstall, and click on Uninstall.
# From the Command Line: The uninstaller program is installed in the base directory of your Ruby installation and is called `unins000.exe`. You can run it from the command line as `C:\Ruby*\unins001.exe` or `C:\Ruby*\unins001.exe /verysilent` if you want to do a silent removal.
# Just remove the directory: You can also just simply delete the entire Ruby installation directory. If you had added it to your Windows PATH, you should also remove that path entry even if you don’t do that, it does have a big impact.
