### ISSUE TITLE
New 2.5.1 version released

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller2#107]
Hi,

I found the new version 2.5.1 has been released. Please update the binaries distroes. 

Thanks!

**Comment by Kjarrigan** [comment]
@larskanis wrote yesterday in #106 
> I'll publish rubyinstaller-2.4.4 and 2.5.1 tomorrow (...)

**Comment by luislavena** [comment]
Released: https://rubyinstaller.org/2018/03/29/rubyinstaller-2.5.1-1-and-2.4.4-1-released.html

Closing.
