### ISSUE TITLE
Wrong Version of Ruby for Windows gets installed from install package 

### ISSUE THREAD

**Issue by FodorTheMagnificent** [oneclick/rubyinstaller2#109]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
The wrong version of Ruby gets installed from the package downloader located here:
https://rubyinstaller.org/downloads/   or click [https://rubyinstaller.org/downloads/](url)

## Steps to reproduce
I selected and installed Ruby 2.4.3-2 (x64) and ran the installation. But I get a different version installed.
So then I tried to install Ruby 2.5.1-1(x64)

Neither package is installed on Windows 10 machine.

## What's the output from `ridk version`?
**What is  `ridk version`?**  How do I run this command?

I get these:
C:\Users\Bill Cory>ruby --version
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

C:\Users\Bill Cory>ruby -v
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]

**Comment by luislavena** [comment]
Hello @FodorTheMagnificent, receiving `ruby 2.2.6p396` might be an indicator that another Ruby was installed in the system, perhaps bundled with other software.

If you run the following command, you might be able to stop which is the guilty project that installed it:

```shell
C:\>where ruby.exe
C:\Path\To\Other\bin\ruby.exe
```

Based on the directory reported, you might need to uninstall that package, or make sure that is not in the PATH.

Please also note that during installation, you have the option to add RubyInstaller to the PATH, pay attention to that option.

Hope that helps.
