### ISSUE TITLE
Can't download rubyinstaller

### ISSUE THREAD

**Issue by alextwin** [oneclick/rubyinstaller2#116]
I am unable to download from https://rubyinstaller.org/downloads/.

When I try to download ruby 2.5.1 or 2.4.4, it says that my connection times out.  I am able to download 2.3.3 and before on the same page, but I would like to know if there was anything I could do to fix this issue

**Comment by larskanis** [comment]
The installer files are delivered by a distributed content delivery network. It sometimes happens that the download fails in some country. Does it still timeout?
