### ISSUE TITLE
Msys2 can't update (or install any package) including Pacman Syuu don't work

### ISSUE THREAD

**Issue by meisam2015** [oneclick/rubyinstaller2#121]
i was having this problem on my win 10 . i reinstalled the application twice to make it work when i was doing this i run "pacman -Syuu" command and at the same time i noticed my antivirus moved it to chase, as it was thinking it is a virus.
it was giving me "error and something is failed" don't remember the error now. also this command wasn't working too "update-core" and all other i mean.
to fix it disable your antvirus. 
hop this helps

**Comment by larskanis** [comment]
Thanks for letting us know!
