### ISSUE TITLE
incomplete "\xB3" on UTF-16LE

### ISSUE THREAD

**Issue by Luggruff** [oneclick/rubyinstaller2#122]
This project is for Ruby version 2.4 and newer.

## What problems are you experiencing?
ERROR:  While executing gem ... (Encoding::InvalidByteSequenceError)
    incomplete "\xB3" on UTF-16LE

## Steps to reproduce
gem install sass
(right after installation of rubyinstaller-devkit-2.4.4-2-x64.exe on 64 bit system with windows 10)

## What's the output from `ridk version`?
---
ruby:
  path: C:/Ruby25-x64
  version: 2.5.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.1-2
  git_commit: 1dfa3f5
msys2:
  path: C:\Ruby25-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(3)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.165]

**Comment by larskanis** [comment]
I can't tell you what's wrong here so far, but can you please run `gem install sass -V -​-backtrace` ? This should give more context to the error message. Can you please post the full output here?

**Comment by larskanis** [comment]
Closing due to no response.
