### ISSUE TITLE
New MSYS2/MinGW gdbm 1.16-2 package

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#123]
Lars,

I noticed that there was a new gdbm package on MSYS/MinGW (1.16), and ruby-loco is building & passing tests with it.  Haven't tried a 32 bit build with it.  FYI...

Thanks, Greg

**Comment by larskanis** [comment]
Thank you Greg! I'll try this, when I'm back from holidays.
-- 
Kind Regards,
Lars

**Comment by MSP-Greg** [comment]
I see you've updated for this...  Thanks, Greg
