### ISSUE TITLE
installing native gems deletes ruby.exe

### ISSUE THREAD

**Issue by daddie888** [oneclick/rubyinstaller2#131]
Whenever I install a native gem (eg ruby-prof, levenshtein) I get no error and it seems like the gem is installed but my bin\ruby.exe is gone and I can't copy it back because I'm not authorised.
I need to reboot the pc and copy the ruby.exe back in \bin folder.
First time i did a complete reinstall but the result is the same.
The gem's i tried to install don't work, can't require them.
I'm on Windows 7 64 bit and have the latest version of Rubyinstaller installed 2.5.3

output from the ConEmu console (cmd gives same result)
Gebruiker@PETER7 D:\Ruby\bin
$ gem install levenshtein
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...

Gebruiker@PETER7 D:\Ruby\bin

## What's the output from `ridk version`?
---
ruby:
  path: d:/Ruby
  version: 2.5.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.3-1
  git_commit: 16e7aa4
msys2:
  path: d:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 8.2.0
sh: GNU bash, versie 4.4.19(3)-release (x86_64-pc-msys)
os: Microsoft Windows [versie 6.1.7601]

**Comment by larskanis** [comment]
I had similar issues due to our AV scanner. It repeatedly moved `bsdtar.exe` into quarantine and I had to actively release the file through the corresponding dialog of the AV scanner. In the end I had to white list the file, so that it wasn't removed anymore.

**Comment by larskanis** [comment]
@daddie888 Have you been able to solve this issue?

**Comment by daddie888** [comment]
Yes, I believe you were right, I adapted my anti-virus settings and now the problems is gone.
Thanks for the suggestion.
