### ISSUE TITLE
RubyInstaller dosent work inside an Windows Docker Container

### ISSUE THREAD

**Issue by JohanSpannare** [oneclick/rubyinstaller2#132]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
When installing Ruby inside an Docker Container, randomly get an installation error.

> 2018-12-14 07:05:55.052   Value name: BuildPlatform
> 2018-12-14 07:05:55.052   Creating or opening the key.
> 2018-12-14 07:05:55.052   Creating or setting the value.
> 2018-12-14 07:05:55.052   Successfully created or set the value.
> 2018-12-14 07:05:55.052   Saving uninstall information.
> 2018-12-14 07:05:55.052   Deleting any uninstall keys left over from previous installs
> 2018-12-14 07:05:55.052   Creating new uninstall key: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\RubyInstaller-2.5-x64-mingw32_is1
> 2018-12-14 07:05:55.052   Fatal exception during installation process (Exception):
>                           Error creating registry key:
>                           HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\RubyInstaller-2.5-x64-mingw32_is1
> 
>                           RegCreateKeyEx failed; code 1018.
>                           Illegal operation attempted on a registry key that has been marked for deletion.
> 2018-12-14 07:05:55.052   Exception message:
> 2018-12-14 07:05:55.052   Message box (OK):
>                           Error creating registry key:
>                           HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\RubyInstaller-2.5-x64-mingw32_is1
> 
>                           RegCreateKeyEx failed; code 1018.
>                           Illegal operation attempted on a registry key that has been marked for deletion.

## Steps to reproduce
Dockerfile:

```
# escape=`
FROM microsoft/windowsservercore
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
LABEL Description="Ruby on Windows Server Core"
ADD https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.3-1/rubyinstaller-devkit-2.5.3-1-x64.exe .
RUN C:\\rubyinstaller-devkit-2.5.3-1-x64.exe /silent /tasks="assocfiles,modpath" /log="install.log"

```

docker build .

**Comment by larskanis** [comment]
I wrote a Dockerfile [here](https://github.com/oneclick/rubyinstaller2/blob/master/docker/Dockerfile), that makes use of RubyInstaller to build RubyInstaller. It worked to some extent, but at least on Windows-2016 I got random mount and other obscure error messages from docker which are not related to RubyInstaller, but are bugs in the Windows docker implementation.

For the installation it's important to use `cmd /c rubyinstaller.exe [...]`. Otherwise the installer runs in the background and the command doesn't wait for completion of the process.
