### ISSUE TITLE
Spec tests from release tarball ?

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#133]
After the recent failed spec tests for 2.6.0 & some discussion in ruby/spec, rather than use the spec repo as below, should the spec/mspec files from the release tarballs be used?

https://github.com/oneclick/rubyinstaller2/blob/ae21fb4e5740cd362fcb58cd52cd407056c12bd6/appveyor.yml#L48-L49

I looked at the the code, but wasn't sure where a change like this should go...  Thanks.

**Comment by larskanis** [comment]
I don't follow the discussions constantly on ruby core. So thank you for notifying me!

Reg. ruby/spec vs. specs from ruby/ruby: That's just a config option [run_mri_spec](https://github.com/oneclick/rubyinstaller2/blob/master/appveyor.yml#L127) versus [run_ruby_spec](https://github.com/oneclick/rubyinstaller2/blob/master/appveyor.yml#L120). It is intended to be distinct between development and release versions. However that is not a release blocker. I just didn't have the time yet and wanted to add a new (experimental) ruby version switch to the next release.

**Comment by MSP-Greg** [comment]
The reason I mentioned the tarball files is that you mentioned feeling more comfortable with tests from another location (ie, 'paranoid').  As a build check, the spec tests in the tarball should **always work**.

I've been involved with updates to both test-all & spec in terms of consistent results, reliable parallel testing, etc.  So, I keep an eye on both.

It was common for spec changes in trunk to break older Ruby versions.  Thankfully, trunk Travis CI now also tests the spec suite with 2.3, so changes must be properly 'guarded' as to Ruby versions.

Regardless, trunk is often failing in ruby/spec, as Benoit can't always move code between the repos immediately, especially during the Holiday season.  Combine that with (sometimes questionable) rushes to get code in the Ruby release...

I thought I implied it wasn't a firm 'release blocker', maybe I'll use the term 'release hindrance' from now on...

Finally, this whole issue only occurs with X.Y.0 releases, as any later teeny releases involve backports that take more time to 'flow thru the system'...

Have a good New Year, and thanks for your continuing work on RI2, Greg

**Comment by larskanis** [comment]
I leave `run_ruby_spec` in `appveyor.yml` for now, but I'll keep in mind to switch to `run_mri_spec`, when necessary. Thanks again!
