### ISSUE TITLE
cant do gem install bundler on ruby 2.0 , an SLL certificate error 

### ISSUE THREAD

**Issue by ahalrawi** [oneclick/rubyinstaller2#137]
Unable to download data from https://rubygems.org - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)

any fix for that with ruby 2.0

**Comment by larskanis** [comment]
This is fixed in RubyInstaller-2.4 and newer. Please upgrade!

**Comment by ahalrawi** [comment]
ya , but i need to use database gems and all the gems out there require 2.0 and less 

gem 'activerecord'
gem 'activerecord-oracle_enhanced-adapter'
gem 'oracle_enhanced'
gem 'ruby-oci8', '2.1.3'
