### ISSUE TITLE
what gems i can use for database connection , i am using Ruby 2.5

### ISSUE THREAD

**Issue by ahalrawi** [oneclick/rubyinstaller2#138]
the gems i was trying to use is 
gem 'activerecord'
gem 'activerecord-oracle_enhanced-adapter'
gem 'oracle_enhanced'
gem 'ruby-oci8', '2.1.3'

but those are for ruby 2.0 and less ..any suggestions or how can achieve that

**Comment by ahalrawi** [comment]
and keeping the Ruby 2.5 right ? 

so i might need to delete the gemfile.lock and put older version of the gems above ?

**Comment by larskanis** [comment]
@ahalrawi  Did you solve the above issue? I would like to close it, since I doubt, that we can do anything helpful here.

**Comment by ahalrawi** [comment]
Yes please close it
