### ISSUE TITLE
Module Profiler__ of Ruby2.6 output not correct?

### ISSUE THREAD

**Issue by vnluc** [oneclick/rubyinstaller2#142]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
Output from profiler example look not correct.
[Profiler__ docs](https://docs.ruby-lang.org/en/2.6.0/Profiler__.html)

## Steps to reproduce
Try running the Profiler example from documentation page.

```

require 'profile'

def slow_method
  5000.times do
    9999*999999999
  end
end

def fast_method
  5000.times do
    9999+999999999
  end
end

slow_method
fast_method

```

Output:
```
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
 79.49     0.06      0.06        2    31.00    39.00  Integer#times
 20.51     0.08      0.02     5001     0.00     0.01  Object#slow_method
  0.00     0.08      0.00        2     0.00     0.00  Module#method_added
  0.00     0.08      0.00        1     0.00     0.00  TracePoint#enable
  0.00     0.08      0.00     5001     0.00     0.01  Object#fast_method
  0.00     0.08      0.00        1     0.00     0.00  TracePoint#disable
  0.00     0.08      0.00        1     0.00     0.00  TracePoint#__enable
  0.00     0.08      0.00        1     0.00    78.00  #toplevel
```
By this output, the slow_method and fast_method is called 5000 times? I think this is not correct and not match with documentation page

## What's the output from `ridk version`?

D:\dev\ruby\prof>ridk version
---
ruby:
  path: D:/bin2/rubyinstaller-2.6.0-1-x64
  version: 2.6.0
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.0-1
  git_commit: 7688b64
msys2:
  path: D:\bin2\msys64
  title: MSYS2 64bit
  version: '20180531'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 8.2.1 20181214
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.590]

**Comment by MSP-Greg** [comment]
@vnluc

I ran this on Travis, and it's showing the same issue there using Ruby 2.0 thru trunk.  Note that output varies dependent on whether the require is in the script or added on the command line.  Either way, both methods show being called 5k times.

Log with require in script:
https://travis-ci.org/MSP-Greg/testing-travis/builds/504047314

Log with command line require:
https://travis-ci.org/MSP-Greg/testing-travis/builds/504051601

You could open an issue at:
https://bugs.ruby-lang.org/projects/ruby-trunk/issues

**Comment by vnluc** [comment]
Thank you, i reported a bug at
https://bugs.ruby-lang.org/issues/15652

Lets see if someone can help.

**Comment by vnluc** [comment]
They rejected this because no one maintained the module recommending rbspy. maybe we can take a look
https://bugs.ruby-lang.org/issues/15652

**Comment by larskanis** [comment]
I don't think we can do more on RubyInstaller side.
