### ISSUE TITLE
Ruby 2.6 - ArithmeticSequence#hash make ruby crash

### ISSUE THREAD

**Issue by vnluc** [oneclick/rubyinstaller2#145]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

(1..10).step(2).hash     # this make Ruby crash

## Steps to reproduce

>ruby -e "puts (1..10).step(2).hash"

ha.rb:4: [BUG] Unnormalized Fixnum value 0xd12e6bf7008f684f
ruby 2.6.1p33 (2019-01-30 revision 66950) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0005 p:---- s:0018 e:000017 CFUNC  :to_s
c:0004 p:---- s:0015 e:000014 CFUNC  :puts
c:0003 p:---- s:0012 e:000011 CFUNC  :puts
c:0002 p:0018 s:0007 E:000858 EVAL   ha.rb:4 [FINISH]
c:0001 p:0000 s:0003 E:001460 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
ha.rb:4:in `<main>'
ha.rb:4:in `puts'
ha.rb:4:in `puts'
ha.rb:4:in `to_s'

## What's the output from `ridk version`?
---
ruby:
  path: D:/bin2/rubyinstaller-2.6.1-1-x64
  version: 2.6.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.1-1
  git_commit: b23a0db
msys2:
  path: D:\bin2\msys64
  title: MSYS2 64bit
  version: '20180531'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 8.2.1 20181214
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.590]

**Comment by MSP-Greg** [comment]
See Ruby Issue [15757](https://bugs.ruby-lang.org/issues/15757)

Fixed by Ruby [r67468](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/trunk/revisions/67468) or git [ae6c195f](https://github.com/ruby/ruby/commit/ae6c195f30f76b1dc4a32a0a91d35fe80f6f85d3)

Marked for backport to 2.4 thru 2.6.

**Comment by vnluc** [comment]
Thank you @MSP-Greg , Its great to see that it fixed.

**Comment by larskanis** [comment]
Thanks @MSP-Greg for connecting the issues together!
