### ISSUE TITLE
Unable to install properly latest version RubyInstaller with DevKit on win 10

### ISSUE THREAD

**Issue by ejmm320** [oneclick/rubyinstaller2#148]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
Unable to install properly latest version RubyInstaller with DevKit on win 10

## Steps to reproduce
1) `C:\>ridk install`
2) Select 3 - MSYS2 and MINGW development toolchain
`Error: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
Error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
Error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))`

## Already tried in MSYS2 shell:
1) `pacman-key --refresh-keys`
With output:
`gpg: connecting dirmngr at '/etc/pacman.d/gnupg/S.dirmngr' failed: IPC "connect"`
2) Uninstall the whole thing over and over again, tried with older versions too.

## What's the output from `ridk version`?
`C:\>ridk version
---
ruby:
  path: C:/Ruby26
  version: 2.6.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.3-1
  git_commit: 779b05c
msys2:
  path: C:\Ruby26\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 8.3.0
sh: GNU bash, Version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17763.379]`

Any ideas?
Thnx in advance.

**Comment by larskanis** [comment]
This should work in that case:
```cmd
ridk exec sh -c "pacman-key --init"
ridk exec sh -c "pacman-key --populate"
```

Did you run the `ridk install` task on the last installer page (it is selected by default)?
