### ISSUE TITLE
question about rubyinstaller2

### ISSUE THREAD

**Issue by snow8gaia** [oneclick/rubyinstaller2#151]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
none

**Comment by snow8gaia** [comment]
If msys2 is already installed on a safe path or location(similar to `H:\asdmsys2`); is it essential to remove it in order to install rubyinstaller2? or will it recognize the previous msys2 installation and there will be no actual problems.

**Comment by larskanis** [comment]
Please have a look at #75 - it explains the possible options.

**Comment by snow8gaia** [comment]
# another question about rubyinstaller2
### possible ways to import public keys?

### verbatim example from https://wiki.manjaro.org/index.php?title=How-to_verify_GPG_key_of_official_.ISO_images ->


3.1 Download all keys from the Manjaro Developers from GitHub: 
`wget github.com/manjaro/packages-core/raw/master/manjaro-keyring/manjaro.gpg`
Next, import all the keys in the downloaded .GPG file into your gnupg keyring: 
`gpg --import manjaro.gpg`
