### ISSUE TITLE
New releases signing issues

### ISSUE THREAD

**Issue by XhmikosR** [oneclick/rubyinstaller2#159]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

It seems the digital signature for the newly released binaries isn't right

## Steps to reproduce

Download the official build from https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.5.6-1/rubyinstaller-2.5.6-1-x64.exe

<img src="https://user-images.githubusercontent.com/349621/65587942-591e8300-df8f-11e9-8007-7df209040efa.png" alt="2019-09-25_12-19-43" width="400">

rubyinstaller-2.5.5-1-x64.exe doesn't have this issue.

**Comment by XhmikosR** [comment]
https://www.virustotal.com/gui/file/ebd0ddf6676fe4d8a6e713006254b4889d8bea89de2ada9fee83aba8ff4b6b16/details

**Comment by XhmikosR** [comment]
Actually, I just noticed related fixes in master https://github.com/oneclick/rubyinstaller2/compare/RubyInstaller-2.6.4-1...master

@larskanis can you upload the new builds please?

**Comment by larskanis** [comment]
Sorry for the broken signature! It should be fixed in the latest release series: https://www.virustotal.com/gui/file/cd6498021fa842e31b8f054e9b8a7207b49832f966cb07aa9ab5f986eb5ee6d4/details
