### ISSUE TITLE
In windows 7 64 bit rails s doesn't start in development mode

### ISSUE THREAD

**Issue by flutteradv** [oneclick/rubyinstaller2#160]
I installed ruby using ruby+devkit 2.6.5-1 installer and I selected 3 to install MSYS2. later I installed rails using gem install rails which installed the latest rails 6.0.  I created demo app using rails new demo. The rails creates app and the last message is webpacker installed successfully .
when I run rails s It stuck in development mode forever like the  screenshot
![Untitled](https://user-images.githubusercontent.com/54617099/67156860-dd66ea80-f330-11e9-967b-566b39ce7371.png)

**Comment by sinankeskin** [comment]
Hi.

Default mode is always development. If you want to change the running mode you should set explicitly like `rails s -e production` or with env variable `RAILS_ENV=production rails s`.

**Comment by mohits** [comment]
HI, it seems that this issue has been addressed - so, I will close this now.
