### ISSUE TITLE
readline - 2.5 & 2.6 contain readline.so file, but no libreadline*.dll

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#162]
Lars,

Seemed odd...

Happy Holidays, Greg

**Comment by larskanis** [comment]
Hi Greg,

yes, it seemed odd, but I included it to allow easy testing of the GNU readline library, just by renaming some files. Now that RubyInstaller switched to Reline and GNU readline still doesn't properly work on Windows, I removed the C extension entirely.

Thank you!
