### ISSUE TITLE
New Ruby 2.7 available

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller2#165]
Hello project leaders,

I found on ruby-lang website has Ruby 2.7 released and eager to see the new features with Windows binaries.

Thanks a heap ;-)

**Comment by larskanis** [comment]
Sure, I'm on it. However I want to do some more testing and want to work on reline as replacement to readline-rb, so that the final release will take some days.

For the time being please use the RubyInstaller-head from the download page: https://rubyinstaller.org/downloads/

**Comment by tan-wei** [comment]
Waiting for the new release. Thanks for your working and testing.

**Comment by larskanis** [comment]
RubyInstaller-2.7.0-1 is there: https://rubyinstaller.org/2020/01/05/rubyinstaller-2.7.0-1-released.html
