### ISSUE TITLE
mingw32-make gives an error while developing C extension

### ISSUE THREAD

**Issue by akhilravuri1** [oneclick/rubyinstaller2#166]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
mingw32-make: *** No rule to make target '/C/Ruby26/include/ruby-2.6.0/ruby.h', needed by 'ibm_db.o'.  Stop.

and  If I change the path to windows format It installs but unable to find  .so file while requiring.

## Steps to reproduce
1) downloaded zip from https://github.com/ibmdb/ruby-ibmdb

2) cd to ext folder in ruby-ibm_db

3) ruby extconf.rb which creates make file

4) mingw32-make
 will give you error :-  mingw32-make: *** No rule to make target '/C/Ruby26/include/ruby-2.6.0/ruby.h', needed by 'ibm_db.o'.  Stop.

5) changed the path to windows format .

6) theh make will work fine but .so file is not found.

## What's the output from `ridk version`?

---
ruby:
  path: C:/Ruby26
  version: 2.6.5
  platform: i386-mingw32
ruby_installer:
  package_version: 2.6.5-1
  git_commit: d3e0c65
msys2:
  path: C:\Ruby26\msys32
cc: i686-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 9.2.0
sh: GNU bash, version 4.4.23(1)-release (i686-pc-msys)
os: Microsoft Windows [Version 10.0.15063]

##QUESTIONS

1) why mingw32-make is not creating windows path?

2) .so file is present in that path but it says that it is not able to find it?

I have googled a lot for more than 20 days but I could not find any solution.

Thanks,
Akhil

**Comment by larskanis** [comment]
This looks like the same issue as https://github.com/oneclick/rubyinstaller2/issues/105 . You shouldn't use `mingw32-make` but something like:
```
ridk enable
ruby extconf.rb
```

**Comment by akhilravuri1** [comment]
Thanks for the solution.
