### ISSUE TITLE
Error installing gem bson 4.7.0

### ISSUE THREAD

**Issue by limmet** [oneclick/rubyinstaller2#167]
When i try to install bson version 4.7.0 i get the following error stack.

gem install bson
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing bson:
        ERROR: Failed to build gem native extension.

    current directory: C:/git/dependencies/gems_2/gems/bson-4.7.0/ext/bson
C:/git/b360/tools/ruby_2/bin/ruby.exe -r ./siteconf20200121-15716-10kb4r5.rb extconf.rb
creating Makefile

current directory: C:/git/dependencies/gems_2/gems/bson-4.7.0/ext/bson
make "DESTDIR=" clean

current directory: C:/git/dependencies/gems_2/gems/bson-4.7.0/ext/bson
make "DESTDIR="
generating bson_native-x64-mingw32.def
compiling bytebuf.c
compiling endian.c
In file included from endian.c:18:0:
bson-endian.h:109:1: error: unknown type name 'uint16_t'; did you mean 'wint_t'?
 uint16_t __bson_uint16_swap_slow(uint16_t v);
 ^~~~~~~~
 wint_t
bson-endian.h:109:34: error: unknown type name 'uint16_t'; did you mean 'wint_t'?
 uint16_t __bson_uint16_swap_slow(uint16_t v);
                                  ^~~~~~~~
                                  wint_t
bson-endian.h:110:1: error: unknown type name 'uint32_t'; did you mean 'wint_t'?
 uint32_t __bson_uint32_swap_slow(uint32_t v);
 ^~~~~~~~
 wint_t
bson-endian.h:110:34: error: unknown type name 'uint32_t'; did you mean 'wint_t'?
 uint32_t __bson_uint32_swap_slow(uint32_t v);
                                  ^~~~~~~~
                                  wint_t
bson-endian.h:111:1: error: unknown type name 'uint64_t'; did you mean 'u_int64'?
 uint64_t __bson_uint64_swap_slow(uint64_t v);
 ^~~~~~~~
 u_int64
bson-endian.h:111:34: error: unknown type name 'uint64_t'; did you mean 'u_int64'?
 uint64_t __bson_uint64_swap_slow(uint64_t v);
                                  ^~~~~~~~
                                  u_int64
endian.c:35:1: error: unknown type name 'uint16_t'; did you mean 'wint_t'?
 uint16_t __bson_uint16_swap_slow(uint16_t v)
 ^~~~~~~~
 wint_t
endian.c:35:34: error: unknown type name 'uint16_t'; did you mean 'wint_t'?
 uint16_t __bson_uint16_swap_slow(uint16_t v)
                                  ^~~~~~~~
                                  wint_t
endian.c:56:1: error: unknown type name 'uint32_t'; did you mean 'wint_t'?
 uint32_t __bson_uint32_swap_slow(uint32_t v)
 ^~~~~~~~
 wint_t
endian.c:56:34: error: unknown type name 'uint32_t'; did you mean 'wint_t'?
 uint32_t __bson_uint32_swap_slow(uint32_t v)
                                  ^~~~~~~~
                                  wint_t
endian.c:80:1: error: unknown type name 'uint64_t'; did you mean 'u_int64'?
 uint64_t __bson_uint64_swap_slow(uint64_t v)
 ^~~~~~~~
 u_int64
endian.c:80:34: error: unknown type name 'uint64_t'; did you mean 'u_int64'?
 uint64_t __bson_uint64_swap_slow(uint64_t v)
                                  ^~~~~~~~
                                  u_int64
endian.c: In function '__bson_double_swap_slow':
endian.c:109:4: error: unknown type name 'uint64_t'; did you mean 'u_int64'?
    uint64_t uv;
    ^~~~~~~~
    u_int64
In file included from endian.c:18:0:
bson-endian.h:65:57: error: 'uint64_t' undeclared (first use in this function); did you mean 'u_int64'?
 #  define BSON_UINT64_SWAP_LE_BE(v) __builtin_bswap64 ((uint64_t)v)
                                                         ^
bson-endian.h:65:57: note: in definition of macro 'BSON_UINT64_SWAP_LE_BE'
 #  define BSON_UINT64_SWAP_LE_BE(v) __builtin_bswap64 ((uint64_t)v)
                                                         ^~~~~~~~
bson-endian.h:65:57: note: each undeclared identifier is reported only once for each function it appears in
 #  define BSON_UINT64_SWAP_LE_BE(v) __builtin_bswap64 ((uint64_t)v)
                                                         ^
bson-endian.h:65:57: note: in definition of macro 'BSON_UINT64_SWAP_LE_BE'
 #  define BSON_UINT64_SWAP_LE_BE(v) __builtin_bswap64 ((uint64_t)v)
                                                         ^~~~~~~~
endian.c:112:32: error: expected ')' before 'uv'
    uv = BSON_UINT64_SWAP_LE_BE(uv);
                                ^
bson-endian.h:65:66: note: in definition of macro 'BSON_UINT64_SWAP_LE_BE'
 #  define BSON_UINT64_SWAP_LE_BE(v) __builtin_bswap64 ((uint64_t)v)
                                                                  ^
make: *** [Makefile:242: endian.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/git/dependencies/gems_2/gems/bson-4.7.0 for inspection.
Results logged to C:/git/dependencies/gems_2/extensions/x64-mingw32/2.5.0/bson-4.7.0/gem_make.out

ridk version
---
ruby:
  path: C:/git/b360/tools/ruby_2
  version: 2.5.7
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.7-1
  git_commit: d3e0c65
msys2:
  path: C:\git\dependencies\msys64
  title: MSYS2 64bit
  version: '20180531'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(3)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.18362.592]

**Comment by larskanis** [comment]
I opened a pull request on the base project: https://github.com/mongodb/bson-ruby/pull/174

**Comment by larskanis** [comment]
This issue is fixed in bson-4.7.1.
