### ISSUE TITLE
OpenSSL 1.1.1e contains a breaking change, reverted in 1.1.1f

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#173]
Lars,

Re 2.5.8, 2.6.6 & 2.7.1,

You're probably aware of the OpenSSL issue.  Hopefully MSYS2 will release 1.1.1f shortly.  I've got PR there for it.

**Comment by larskanis** [comment]
Thank you for the hint! I noticed the issues, but didn't investigate them so far.

Note to self: PR is here https://github.com/msys2/MINGW-packages/pull/6326

**Comment by MSP-Greg** [comment]
Sorry, I should have included that...  Hope things are well.

**Comment by larskanis** [comment]
Mingw-OpenSSL-1.1.1f was published just after I built my own packages. So I revered my work and used the official package.

**Comment by larskanis** [comment]
Thanks again!
