### ISSUE TITLE
Release updated rubygems?

### ISSUE THREAD

**Issue by p-mongo** [oneclick/rubyinstaller2#176]
## What problems are you experiencing?

 bundler fails to install dependencies due to broken(?) requirements in an old versions of published gems. I reported this [to rubygems](https://github.com/rubygems/rubygems/issues/3690), I've been told this would be fixed automatically, the issue has gone away on linux builds but persists on our windows builds in appveyor.

Example failing build from today: https://ci.appveyor.com/project/p-mongo/bson-ruby/builds/33671317/job/sdac49l4om7pp0dv

Our appveyor config: https://github.com/mongodb/bson-ruby/blob/master/.appveyor.yml

Doe RubyInstaller include the fix for https://github.com/rubygems/rubygems/issues/3690 and do we need to do something for our builds to be back to green?

## Steps to reproduce

Clone https://github.com/mongodb/bson-ruby, run `gem install`   against ruby-head

**Comment by larskanis** [comment]
@p-mongo Thanks for notifying me! This issue was fixed upstream but the Rubyinstaller build was temporary broken due to a change in MSYS2. Now this is fixed and RubyInstaller-head is up-to-date.
