### ISSUE TITLE
Need a IDE

### ISSUE THREAD

**Issue by AGoh2019** [oneclick/rubyinstaller2#177]

**Comment by AGoh2019** [comment]
I need a Ruby IDE that look like DrJava or jGrasp.  Cannot program with just the command line.

**Comment by larskanis** [comment]
Try a google search for "ruby ide" and you'll get a plenty of them! I never became familiar with any IDE, but use a powerful editor and the command line - mostly on Linux. Since Windows has poor command line support many people prefer an IDE, but basic command line practice is always advantageous.

**Comment by MSP-Greg** [comment]
JFYI, not an IDE, but Windows Terminal can be helpful.  I've got it running with PowerShell, PowerShell Core, Cmd, Git bash, & MSYS2 bash.  I rarely use the standard MSYS2 shell any more.  It's helpful when one is testing against several Ruby versions at once...

**Comment by sroller** [comment]
The best IDE seems to be RubyMine https://www.jetbrains.com/ruby/
