### ISSUE TITLE
A dedicated Ruby IDE and not more repl-environment

### ISSUE THREAD

**Issue by AGoh2019** [oneclick/rubyinstaller2#179]
## What problems are you experiencing?
Well, how does one compile a Ruby source file.  I presume its ruby -file name- etc

## Steps to reproduce
Go to Windows Terminal. Type in ruby and file name to continue

## What's the output from `ridk version`?
Not using it.

There is so much work being done to the Repl online compiler.  Can't the maintainers of "Ruby Installer for Windows" put some effort into developing a IDE for Windows users. I think that every language inventor should add a IDE to the tool set.  In fact, this is not about Windows users being accustomed to a GUI environment but I like to point out that the future of computing is about graphical user interface and virtual reality, and we should stop going back to the command-line computing in the 1980s and early 1990s.   Linux as it stands now still has issues with connecting to the Internet via Wi-Fi routers (at home and out in the open and in offices) and setup and configuration issues with wireless printers from HP, Canon, Epson etc, which is still why I am using Windows. I have had past experience using Ubuntu Linux and I had trouble with networking.  I couldn't contact support because I wasn't online. Otherwise, I would say Linux is just as usable as Windows 10 and macOS.

**Comment by dmajkic** [comment]
@AGoh2019  JetBrains RubyMine is IDE dedicated to Ruby https://www.jetbrains.com/ruby/
It works on Windows, Linux, Mac. 

People here are not language inventors. Please visit Ruby lang official page at https://www.ruby-lang.org/en/

**Comment by larskanis** [comment]
@AGoh2019 You can simply double click on a text file with .rb or .rbw extension in order to execute it. There's no need to compile Ruby code. And you can use any text editor to write these Ruby files.

Also don't misinterpret poor command line support of Windows as something from the 80's. It has still lots of advantages compared to a GUI.

**Comment by AGoh2019** [comment]
Thanks for the update.  I found a Ruby Development Environment version 1.1.1.1 by sakasuki and the tool has not been updated for either 09-04-2013 or five years.  I wonder if anybody from Ruby Installer for Windows would like to take over the project.

**Comment by sroller** [comment]
@larskanis I think you should close this issue. The guy is just trolling you. He doesn't seem to read the responses and he doesn't understand that open source development means contributing to a project not demanding something from other people's free time.

**Comment by larskanis** [comment]
@AGoh2019 Feel free to pick up this or another IDE project, but for RubyInstaller it's beyond the project scope.
