### ISSUE TITLE
Ruby dependency package builders available

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#18]
@larskanis 

I've got the packagers up at [MSP-Greg/ruby-makepkg-mingw](https://github.com/MSP-Greg/ruby-makepkg-mingw).

Builds gdbm, libyaml, and openssl.  Provided some scripts also.

Since I've been working with RI, I've only done 32 bit builds.  Of the three packages, only the openssl package has x64 appended to dll file names.  Not sure if that's normal, or if I'm missing a build setting.

Anyway, see the readme.

Of course, I'm very interested in what you (and others?) find as far as building and testing...

Reminder, that one line in [PKGBUILD](https://github.com/larskanis/rubyinstaller2/blob/master/compile/ruby-2.4.0/PKGBUILD#L65).

Also, wondering if you and others can give the native readline some testing.  Seems to work on my builds, but there are some test issues.  They might be caused by the testing trying to mimic console input, which may be an issue with Windows.

**Comment by MSP-Greg** [comment]
@larskanis Update

Finally dumped RI and now building from local (Ruby trunk) with makepkg-mingw and PKGBUILD.

`test-all` has no failures/errors in any gdbm/dbm, libyaml, or OpenSSL tests, both on i686 & X86_64.

**Comment by MSP-Greg** [comment]
@larskanis 

I added a release, so I've got xz files for i686 and x86_64 packages at [MSP-Greg/ruby-makepkg-mingw Release v0.1](https://github.com/MSP-Greg/ruby-makepkg-mingw/releases/tag/v0.1)

Hence, no one needs to go to the trouble of building them.

**Comment by MSP-Greg** [comment]
@larskanis 

Yesterday I finished code to allow `relatively easy' building of Ruby trunk from a local repo.  It was essentially two files:

[build_utils.rb](https://github.com/MSP-Greg/ruby-makepkg-mingw/blob/master/mingw-w64-ruby/build_utils.rb) - run in a windows cmd window before build (or makepkg-mingw).  It used git to update the ruby repo, and also RI2 repo.  Three 'required' things it did to the `src` directory - bundled gems, revision.h, and cleaning previous build artifacts.  Since (originally) I thought I'd need git commands, I left it out of PKGBUILD, since I didn't want the potential conflicts between GitHub windows and similar commands in MSYS2, nor the seemingly large number of packages needed to run git in MSYS2.

You may have come across it already, but all the items added to src for and during build are contained in the ruby [.gitignore](https://github.com/ruby/ruby/blob/trunk/.gitignore) file.

[package_utils]((https://github.com/MSP-Greg/ruby-makepkg-mingw/blob/master/mingw-w64-ruby/package_utils.rb) - this ran from within PKGBUILD, two tasks - add dll's, and add RI2.

Now the moving to 'why all the info'.  With the gem branch, I can add RI2 to the list of bundled gems and have ruby's package system add it to the package files.

Hence, I would no longer need git, and I might be able to move build-utils.rb into PKGBUILD, thereby allowing ruby version detection (of a local repo) to be handled properly.

So now the question - is the RI2 gem branch far enough along so that I could build it and test it in a build?

**Comment by larskanis** [comment]
@MSP-Greg I roughly - but not fully - understand what you're doing.

Regarding the `gem` branch: This is the preparation of something called "RubyInstaller for Applications" or similar. It shall be possible to build customized Installer.exe or 7z files for particular Ruby applications or other Ruby use cases. It can be integrated per `rubyinstaller-build.gem` into Ruby applications and allows building of specialized installers. It shall also be possible to fine tune appearance and integration of the application by overloading almost all parts of the `rubyinstaller-build.gem` as needed. And of course it shall be possible to add arbitrary gems or msys2 packages to the installer package, so that everything works out of the box.

So, that's the vision. Now that it runs [green](https://ci.appveyor.com/project/larskanis/rubyinstaller2/build/1.0.127) again and I hope to have most of the required restructuring in place, I'll probably merge to the master branch soon. However there are still a lot more changes to do for the above feature set.

**Comment by MSP-Greg** [comment]
@larskanis 

Wow.  That's quite a jump in scope.  Thank you.

> I roughly - but not fully - understand what you're doing.

I probably could have been clearer.  Simple goal, to build ruby based on a local repo of trunk, along with integrating your work to allow gem extension installation and use.

First issue was getting source to match what is contained in the cache.ruby-lang.org bz2 files.  This was done by build_utils.rb (which probably should be named prepare_utils.rb).

Second issue was adding all the things (*.dlls, RI2 files) to the pkg directory, so makepkg-mingw would add them to the  xz file.  I don't have need for the xz file, but if someone else wanted it, it would contain what was needed.

When I saw the gem branch and gemspec file, I thought having an RI2 gem would make adding RI2 to a build much easier.

Two things --

1. Part of the reason I prefer to build from local source is that things go wrong.  I built with svn 57782, and all went as expected.  This morning I built with svn 57789, and check stopped (during the 'prep' stage) with a segfault.  With local, it's a bit easier to move around.

2. From a few messages, and the posting of my logs, the ruby core team has already made changes/fixes related to issues with mingw/MSYS2 builds.  A few have to do with readline.

**Comment by MSP-Greg** [comment]
It's not often that one wakes up, checks the recent ruby/ruby commits, and finds several referencing MinGW or Windows.  Thanks to @nobu and the core team for the work.

My local build code is now in [MSP-Greg/ruby-loco](https://github.com/MSP-Greg/ruby-loco).  I tried to make it run 'as close to windows' as possible, and it installs the RI2 runtime code (thanks to @larskanis).  

If you try it, please review the README, as it is definitely pre-release.  For v2.3, use the MinGW OpenSSL package, for v2.4+, I've used the 1.1.0f package in the [release](https://github.com/MSP-Greg/ruby-loco/releases).

Finally, I'm doing daily trunk builds, with results at [Ruby MinGW Test Results](https://msp-greg.github.io/file.mingw_test-all.html).  Build and test results have been stable, although there are several patches...

**Comment by larskanis** [comment]
As discussed in https://github.com/oneclick/rubyinstaller2/issues/55 , the official RI2 package repository is now https://github.com/oneclick/rubyinstaller2-packages .
