### ISSUE TITLE
Running ridk install doesn't install msys2

### ISSUE THREAD

**Issue by Kagayakashi** [oneclick/rubyinstaller2#181]
## What problems are you experiencing?
Install dont work

## Steps to reproduce
run ridk install
choose default

## What's the output from `ridk version`?
D:\my_dev\Ruby27-x64>ridk install
Which components shall be installed? If unsure press ENTER [1,3]

> sh -lc true

**Comment by larskanis** [comment]
What's the error message? Alternatively it's often less error-prone to use the [Ruby+Devkit](https://rubyinstaller.org/downloads/) version of RubyInstaller.

**Comment by Kagayakashi** [comment]
> What's the error message? Alternatively it's often less error-prone to use the [Ruby+Devkit](https://rubyinstaller.org/downloads/) version of RubyInstaller.

There is no Error.
Just one command executed sh -lc true and thats all.

I just closed CMD

**Comment by Kagayakashi** [comment]
Useless program
