### ISSUE TITLE
Ruby was not running like it used to

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller2#186]
## What problems are you experiencing?
from bash, I press "ruby" and [enter], nothing happened...

## What's the output from `ridk version`?
➜  ~ bash
(base) [hp@dv6 ~]$ ruby
^CTraceback (most recent call last):
ruby: Interrupt
(base) [hp@dv6 ~]$ ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
<pre>(base) <font color="#55FF55"><b>[hp@dv6</b></font><font color="#FFFFFF"><b> ~</b></font><font color="#55FF55"><b>]$</b></font> uname -a
Linux dv6 5.7.14-1-MANJARO #1 SMP PREEMPT Fri Aug 7 10:12:32 UTC 2020 x86_64 GNU/Linux</pre>

I used to practice with ruby some years ago. Now I come back with a newer version. Am I abit behind or something wrong with the newer version of ruby?
There used to be a prompt like this after running ruby in console mode: 
> 

but I waited for minutes but nothing happened.

Thank for advise

**Comment by larskanis** [comment]
Ruby is waiting for code on stdin in this case. You probably meant "irb" to start an interactive Ruby console?
