### ISSUE TITLE
Jekyll wont appear as a recognized interal or external command

### ISSUE THREAD

**Issue by DonBeleren** [oneclick/rubyinstaller2#188]

**Comment by MSP-Greg** [comment]
@DonBeleren

See https://github.com/oneclick/rubyinstaller2/issues/96#issuecomment-679206413

**Comment by MSP-Greg** [comment]
@DonBeleren

I don't use (or have installed) Jekyll.

> ERROR: Failed to build gem native extension.

Somewhere in the console output it should say what gem failed.  Could you post that info?  Do you know if you have the 'DevKit/MSYS2' installed?  Run `ridk exec gcc --version` from the console should show output.

**Comment by DonBeleren** [comment]
Here are two images. The first when the Jekyll command fails. The second looks like an error from running that "ridk exec pacman -Sy openssl" command. I ran the command you gave just now and got version 9.3.0.
![Screenshot (58)](https://user-images.githubusercontent.com/54925059/92756789-21a11600-f35b-11ea-9f68-4d7d77fed485.png)
![Screenshot (57)](https://user-images.githubusercontent.com/54925059/92756804-25cd3380-f35b-11ea-86fa-ef7fce983609.png)

**Comment by MSP-Greg** [comment]
@DonBeleren

I think the following should help:
```
gem install http_parser.rb --platform=ruby
```

**Comment by larskanis** [comment]
@DonBeleren There's a space in the path on your E drive. This leads to failures at gem install.

**Comment by MSP-Greg** [comment]
Thanks Lars.  I always forget about that, even though my RubyGems `user-install` path (deliberately) has a space...

**Comment by XhmikosR** [comment]
Just uninstall any Ruby versions + MSYS2, and start again from scratch. The reason for the second image is that MSYS2 changed some package mirror URLs hence the errors. You could probably just change the URLs, but starting from scratch is the best IMHO.
