### ISSUE TITLE
Add support for Ruby 2.7.2

### ISSUE THREAD

**Issue by eregon** [oneclick/rubyinstaller2#193]
Ruby 2.7.2 was released yesterday:
https://www.ruby-lang.org/en/news/2020/10/02/ruby-2-7-2-released/

Could RubyInstaller make a build for it? Thanks!

**Comment by larskanis** [comment]
RubyInstaller-2.7.2-1 is released. I'll add a release post shortly.

**Comment by eregon** [comment]
Thanks!
