### ISSUE TITLE
x86-Ruby Start Command Prompt with Ruby on Windows x64 disappers in Windows Start Menu View

### ISSUE THREAD

**Issue by naoki-akamatsu** [oneclick/rubyinstaller2#194]
## What problems are you experiencing?
There is 'Ruby Start Command Prompt' in installed-Ruby 2.7.2-1-x86 with 
MSYS2 Start menu folder but it disappears from Start menu view on Windows10(x64).

## Steps to reproduce
1 Install Ruby+Devkit 2.7.2-1(x86) on Windows 10 (x64).
2  Click 'Ruby 2.7.2-1-x86 with MSYS2' folder in Windows Start Menu View, 
then 'Interactive Ruby', 'Ruby 2.7.2 API Reference' and 'RubyGems Documentation Server' 
icons appear but 'Start Command Prompt with Ruby' disappear.
3 Open the short cut folder,  'Start Command Prompt with Ruby' short cut exists.
4 This short cut links 'System32 cmd.exe' but 'SysWOW64 cmd.exe'.
5 I try to modify this short cut to 'SysWOW64 cmd.exe', then it appears in Windows Start Menu View.

## What's the output from `ridk version`?
ruby:
  path: C:/ruby/Ruby27
  version: 2.7.2
  platform: i386-mingw32
  cc: i686-w64-mingw32-gcc.exe (Rev1, Built by MSYS2 project) 10.2.0
ruby_installer:
  package_version: 2.7.2-1
  git_commit: df3bebb
msys2:
  path: C:\ruby\Ruby27\msys32
cc: i686-w64-mingw32-gcc (Rev4, Built by MSYS2 project) 10.2.0
sh: GNU bash, バージョン 4.4.23(2)-release (i686-pc-msys)
os: Microsoft Windows [Version 10.0.18363.1082]

**Comment by mohits** [comment]
Hi @naoki-akamatsu - this issue is almost 2 years old. Should we close this?

**Comment by mohits** [comment]
Hi @naoki-akamatsu - I will close this issue. If you or @larskanis feel that we should re-open it, we'll do that. Thanks!

**Comment by larskanis** [comment]
Some start menu entries were broken. Current master branch has several fixes to them. I hope that fixes this issue as well. Nevertheless Windows-10 seems to have some own rules to what it presents in the start menu.

**Comment by naoki-akamatsu** [comment]
Thank you.
