### ISSUE TITLE
Builds for Ruby 3.0.0

### ISSUE THREAD

**Issue by eregon** [oneclick/rubyinstaller2#202]
Ruby 3.0.0 is released. It would be great to have RubyInstaller builds for it.

I noticed c991edb4af2f251803f09a002f2a8b524e139b77 but the Ruby 3.0.0 builds don't seem on the website or https://raw.githubusercontent.com/oneclick/rubyinstaller.org-website/master/_data/downloads.yaml yet.

Mostly an issue to keep track of it so I can update https://github.com/ruby/setup-ruby once the RubyInstaller builds are there.

**Comment by ParadoxV5** [comment]
A reminder that Ruby 3 is “released” on [the Releases page](https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.0.0-1) but neither it nor the website has binary builds for generic users to install.

**Comment by larskanis** [comment]
RubyInstaller-3.0.0-1 is out!
