### ISSUE TITLE
Do we have mirror address?

### ISSUE THREAD

**Issue by ccmywish** [oneclick/rubyinstaller2#209]
## What problems are you experiencing?
Chinese users have been visiting GitHub very slowly. All the download links in [rubyinstaller.org](rubyinstaller.org) point to Github release page so that beginners in China always have severe network trouble on Windows before they can install Ruby successfully.

These days we are considering a mirror of rubyinstaller.org in China. We find that we lack of a sync method to download all and get the newest releases of RubyInstaller2. Do we have a rsync address, s3 bucket or others? If not, we'll  think about other methods to download directly from Github release page.

**Comment by larskanis** [comment]
Unfortunately there's currently nothing but the github releases storage. I didn't check if there are any methods for syncing a mirror from it.

I could upload the signed release files to another storage host as part of the release procedure, if that is helpful.

There is already a Russian translation of rubyinstaller.org online called https://rubyinstaller.ru . They update and translate the pages more or less promptly, but link to the original installer files on github releases. See the corresponding issue: https://github.com/oneclick/rubyinstaller.org-website/issues/13

**Comment by ccmywish** [comment]
@larskanis  Thanks for your reply! Could you provide a rsync address for all signed releases files? I think `rsync` is the simplest and an efficient way to sync.

**Comment by skyzh** [comment]
TUNA / SJTUG could mirror rubyinstaller by using existing mirroring tool of github-releases. You may wait until we add this to our mirror server.

**Comment by ccmywish** [comment]
Thank you very much for your help! We'll later put TUNA/SJTUG in a prominent position on our [website](https://rubyinstaller.cn)

**Comment by skyzh** [comment]
SJTUG now synchronizes most recent 3 version every day. https://mirror.sjtu.edu.cn/github/rubyinstaller2/

**Comment by ccmywish** [comment]
@skyzh Great work! But I'm wondering why "most recent 3 versions" are 
1. rubyinstaller-head
2. RubyInstaller-3.0.0-1
3. RubyInstaller-2.5.8-2

As you can see in https://github.com/oneclick/rubyinstaller2/tags , the most recent versions should be 
1. rubyinstaller-head-old
2. RubyInstaller-3.0.0-1
3.  RubyInstaller-2.7.2-1
4. RubyInstaller-2.6.6-2
5. RubyInstaller-2.5.8-2 

But I'm sure you should use `rubyinstaller-head` to substitute `rubyinstaller-head-old`

And most people now will use RubyInstaller-2.7.2-1 as it's a recommendation by community. Could you provide this version?

**Comment by skyzh** [comment]
It's weird that GitHub Release API gives these 3 versions as most recent... I'll look into that.

By the way, now we have synchronized all version you have mentioned.

**Comment by skyzh** [comment]
By the way, for the case of `rubyinstaller-head-old`, is it possible that artifacts are updated with their filenames unchanged? If this is possible, we will for now remove releases for head branch, as our program currently can't handle this situation.

**Comment by ccmywish** [comment]
I think it'll be OK to remove `head branch` if your sync program can't support it, because only very few expert users will download that version. 

[rubyinstaller.cn](https://rubyinstaller.cn) is online now, we thank SJTUG greatly. And we will keep up with [rubyinstaller.org](https://rubyinstaller.org) step by step since today.

**Comment by larskanis** [comment]
You're right, the files of release `rubyinstaller-head` change daily, but in order to provide a stable download link for CI the tag name isn't changed.

**Comment by larskanis** [comment]
I removed tag `rubyinstaller-head-old` since it's unused now.
