### ISSUE TITLE
Installer tries to write to nonexisting dir and fails (Windows 10)

### ISSUE THREAD

**Issue by Sofvig** [oneclick/rubyinstaller2#212]
The ruby installer fails for me. I have also seen many other users since last year, posting the same problem in different forums!
The result being we cannot use Interactive Ruby.
I wanted to use Ruby for work. 

I tried installing **version 27 once and 30 twice** (admin user), and got an error message which also pops up in irb:
![image](https://user-images.githubusercontent.com/50195960/106584391-69ad1900-6546-11eb-910e-3c1fa52063fd.png)

The error happens during installation:

MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autogen automake-wrapper diffutils file gawk grep libtool m4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git
(then lots of warnings that it simply keeps stuff that was previously installed since they are of the latest version)
 Inget behöver göras.  (nothing to do)
Install MSYS2 and MINGW development toolchain succeeded

**> sh -lc true
mkdir: kan inte skapa katalog ”/h/”: No such file or directory
/h/ could not be created.
Setting HOME to /tmp.**

("kan inte skapa katalog" is Swedish for Cannot create directory. )
MSYS2 seems to be properly installed
------------////////--------------

When the installer asks for what to install (options 1,2,3) I have made different selections for each install, Enter and choosing all.
"Which components shall be installed? If unsure press ENTER [] "

Thanks!
Sofie

## What's the output from `ridk version`?
C:\>ridk version
---
ruby:
  path: C:/Ruby30-x64
  version: 3.0.0
  platform: x64-mingw32
ruby_installer:
  package_version: 3.0.0-1
  git_commit: a672f87
msys2:
  path: C:\Ruby30-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev6, Built by MSYS2 project) 10.2.0
sh: GNU bash, version 5.1.4(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.18363.1316]

**Comment by i-s-o** [comment]
Check the value of your environment variable `HOME` (i.e. `ECHO %HOME%` or `SET H` on the Command Prompt): It seems to be pointing to non-existing `H:\`. This variable is not set by default in a standard Windows installation: it may have been set by your network admin to point to a [possibly read-only] "home" directory (hence the name `H:`) e.g. on a network share. Maybe it is no longer available/accessible, or it is read only. It is also possible that another app set it to that value.

If your `HOME` is indeed set to `H:\`, you have a couple of options:
1. Change it to something that is more commonly set, e.g. `SET HOME=%HOMEDRIVE%%HOMEPATH%`, note however that if another app needs it to be set to `H:\`, you may break it.
2. Tell IRB where to save its [`rc` file](https://en.wikipedia.org/wiki/Run_commands), e.g. `SET IRBRC=C:\tools\ruby-dev\.irbrc` or `SET IRBRC=%HOMEDRIVE%%HOMEPATH%\.irbrc`.

Note that you will need to set those variables in your System Environment, User Environment, or use `SETX` on Command Prompt  to make them permanent.

**Comment by Sofvig** [comment]
Thank you,I have no HOME variable defined.
And it is not in the PATH:

It seems that the installer tries to write to H:// by default in the installer code?
Med vänlig hälsning,




Sofie Vigström









 

    Den lördag 6 februari 2021 19:41:40 CET, i-s-o <notifications@github.com> skrev:  
 
 


Check the value of your environment variable HOME (i.e. ECHO %HOME% or SET H on the Command Prompt): It seems to be pointing to non-existing H:\. This variable is not set by default in a standard Windows installation: it may have been set by your network admin to point to a [possibly read-only] "home" directory (hence the name H:) e.g. on a network share. Maybe it is no longer available/accessible, or it is read only. It is also possible that another app set it to that value.

If your HOME is indeed set to H:\, you have a couple of options:
   
   - Change it to something that is more commonly set, e.g. SET HOME=%HOMEDRIVE%%HOMEPATH%, note however that if another app needs it to be set to H:\, you may break it.
   - Tell IRB where to save its rc file, e.g. SET IRBRC=C:\tools\ruby-dev\.irbrc or SET IRBRC=%HOMEDRIVE%%HOMEPATH%\.irbrc.

Note that you will need to set those variables in your System Environment, User Environment, or use SETX on Command Prompt to make them permanent.

**Comment by i-s-o** [comment]
Ruby or Oneclick RubyInstaller2 (or ridk) may be setting this variable. Check from within Ruby, e.g. in Command Prompt, run this:
`ruby -e "puts ENV['HOME']"`

**Comment by Sofvig** [comment]
Thanks! I got this output. Not sure what I can do?
C:\Windows\System32>ruby -e "puts ENV['HOME']"H:/


Med vänlig hälsning,




Sofie Vigström










 

    Den måndag 8 februari 2021 17:45:50 CET, i-s-o <notifications@github.com> skrev:  
 
 


Ruby or Oneclick RubyInstaller2 (or ridk) may be setting this variable. Check from within Ruby, e.g. in Command Prompt, run this:
ruby -e "puts ENV['HOME']"

**Comment by i-s-o** [comment]
In case you haven't figured it out yet: one solution to your problem is to set the `HOME` variable's value in the active Command Prompt session by using the `SET` command like `SET HOME=%HOMEDRIVE%%HOMEPATH%`:
![image](https://user-images.githubusercontent.com/1661549/109551928-2d1a0200-7a9f-11eb-9774-cd08323b3924.png)

This should then let you use `IRB` without the issue you currently have. Since this change to your `HOME` variable will only be applicable during the current session of the Command Prompt, it will not interfere with other programs that might need it to be set to `H:\`.

**Comment by Sofvig** [comment]
Thanks,but that does not seem to work

ruby 2.4.10p364 (2020-03-31 revision 67879) [x64-mingw32]
C:\Windows\System32>SET HOME=%HOMEDRIVE%%HOMEPATH%
C:\Windows\System32>echo %home%H:\
C:\Windows\System32>irbC:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/irbrc_predefiner.rb:6:in `write': No such file or directory @ rb_sysopen - H:\/.irbrc (Errno::ENOENT)        from C:/Ruby24-x64/lib/ruby/site_ruby/2.4.0/irbrc_predefiner.rb:6:in `<top (required)>'        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'        from C:/Ruby24-x64/bin/irb.cmd:17:in `<main>'
C:\Windows\System32>echo %home%H:\




Med vänlig hälsning,




Sofie Vigström


Mob: 072-012 10 18

https://se.linkedin.com/in/sofievigstrom






 

    Den måndag 1 mars 2021 21:08:30 CET, i-s-o <notifications@github.com> skrev:  
 
 


In case you haven't figured it out yet: one solution to your problem is to set the HOME variable's value in the active Command Prompt session by using the SET command like SET HOME=%HOMEDRIVE%%HOMEPATH%:


This should then let you use IRB without the issue you currently have. Since this change to your HOME variable will only be applicable during the current session of the Command Prompt, it will not interfere with other programs that might need it to be set to H:\.

**Comment by i-s-o** [comment]
That [sort of] makes sense: something is setting all your "HOME" variables at the same time. This might happen on a corporate computer where a system admin might redirect your home directory to a network drive via a logon script (though, in your case it is pointing to a non-existent location).

You could use `%USERPROFILE%` for your `HOME` variable: I think it is supposed to point to a local folder (e.g. on my computer, it points to `C:\Users\[my logon name]`). Nevertheless, just to keep things simple, I recommend creating a new folder using only ASCII characters and no spaces. Then, you can point your home variable to it to and test if IRB works with this simple folder name.

```
mkdir C:\home
pushd C:\home
set HOME=C:\home
irb
```
![image](https://user-images.githubusercontent.com/1661549/110379319-afb53b00-8024-11eb-8d5e-c3ae3fa3b7ec.png)

**Comment by JohnMoehrke** [comment]
I have this same problem. Setting HOME as described did allow irb to work, but installing jekyll still fails the same
