### ISSUE TITLE
Some dlls in bin\ruby_builtin_dlls does not have the version information

### ISSUE THREAD

**Issue by narayani28** [oneclick/rubyinstaller2#214]
## What problems are you experiencing?
Some dlls in bin\ruby_builtin_dlls does not have the version information.

## Steps to reproduce
Install rubyinstaller-devkit-2.7.2-1-x64 and look at the installed location\bin\ruby_builtin_dlls. Some of the dlls in this directory does not have version information. Since there are no version information, there are security issues rised with unknown dlls. 

## What's the output from `ridk version`?
NA

**Comment by MSP-Greg** [comment]
Most (all?) of the dll's in that folder are dll's provided by the MSYS2 build system/packages, they're not generated by code contained in RubyInstaller2...

**Comment by narayani28** [comment]
Yes, agree. But it's a mandatory ask and hence would like to know how to find the dll versions.

**Comment by MSP-Greg** [comment]
I believe some have version info available as constants, e.g.
```
OpenSSL::OPENSSL_LIBRARY_VERSION
Psych::LIBYAML_VERSION
Zlib::ZLIB_VERSION
```
I'm not sure which are determined at run time.  For example, OpenSSL has constants for both the version of OpenSSL Ruby was built with, and the version it's running with...

**Comment by narayani28** [comment]
Where do I see these constants?

**Comment by MSP-Greg** [comment]
Selfish plug - a doc site with Ruby docs - https://msp-greg.github.io/

```ruby
require 'openssl'
puts "OpenSSL version - build    #{OpenSSL::OPENSSL_VERSION}"
puts "OpenSSL version - runtime  #{OpenSSL::OPENSSL_LIBRARY_VERSION}"

require 'psych'
puts "libyaml version #{Psych::LIBYAML_VERSION}"

require 'zlib'
puts "zlib    version #{Zlib::ZLIB_VERSION}"

puts '', 'gcc info:', RbConfig::CONFIG['CC_VERSION_MESSAGE']
```

My system outputs:
```
OpenSSL version - build    OpenSSL 1.1.1j  16 Feb 2021
OpenSSL version - runtime  OpenSSL 1.1.1j  16 Feb 2021
libyaml version 0.2.5
zlib    version 1.2.11

gcc info:
x86_64-w64-mingw32-gcc.exe (Rev6, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by larskanis** [comment]
The DLLs in question are provided by the MSYS2 project. If they provide version information we'll use it for RubyInstaller. However I don't plan to add this information on the RubyInstaller side.
Please use the version information provided by the Ruby API of the gems.
