### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by timy189** [oneclick/rubyinstaller2#219]
## What problems are you experiencing?
Jekyll not installed even after rebooting system

## Steps to reproduce
run jekyll -v in windoes command prompt

## What's the output from `ridk version`?
'jekyll' is not recognized as an internal or external command,
operable program or batch file.

**Comment by larskanis** [comment]
Please make sure, that the ruby bin path is part of the PATH environment variable. This is done by the RubyInstaller by default, but might need logoff and login to the current user to become effective
