### ISSUE TITLE
OpenSSL version update

### ISSUE THREAD

**Issue by swatosh** [oneclick/rubyinstaller2#221]
Any chance of updating the embedded OpenSSL version with the release of 2.7.3?

Thanks!

**Comment by larskanis** [comment]
Sure, it will be Openssl-1.1.1-k. It's just that I have little to no spare time, due to pandemic restrictions. But I'll release the new Ruby versions within the next days.

**Comment by swatosh** [comment]
Immediately after creating this issue, I suspected that it would be automatically updated by your process. I have no intention of hurrying the release process and I greatly appreciate everything you do! Thanks!
