### ISSUE TITLE
releases before 2.4.1 not available for download anymore

### ISSUE THREAD

**Issue by jbrekle** [oneclick/rubyinstaller2#228]
## What problems are you experiencing?
i wanted to install and old ruby on a new machine, but it seems like ruby 2.3.3 is no longer available for download on the official site
https://rubyinstaller.org/downloads/archives/
the links to versions before 2.4.1. return a 401 forbidden error

**Comment by larskanis** [comment]
All old releases are available in the meantime. See https://github.com/oneclick/rubyinstaller/issues/400
