### ISSUE TITLE
Problem when trying to install rubyinstaller2 on windows

### ISSUE THREAD

**Issue by rubyFeedback** [oneclick/rubyinstaller2#229]
The first commands all work fine:
    git clone https://github.com/larskanis/rubyinstaller2
    cd rubyinstaller2
    bundle install

No errors there.

But when doing:

    bundle exec rake

I get this error:

    rake aborted!
    Don't know how to build task 'default' (See the list of available tasks with `rake --tasks

Odd error; I followed the main README but it does not work at that point hmm.

Should not "bundle exec rake" suffice to build the latest "default"?

It suggest ri:default instead. At any rate, the "bundle exec rake" instruction in the
main README does not work for me; tried today.

**Comment by net1957** [comment]
you can download all versions from https://rubyinstaller.org/downloads/
