### ISSUE TITLE
README.md improvement - path packages/ri-msys/recipes/installer-inno/rubyinstaller-devkit-<VERSION>-<ARCH>.exe does not seem to exist

### ISSUE THREAD

**Issue by rubyFeedback** [oneclick/rubyinstaller2#238]
I do not have packages/ri-msys/recipes/installer-inno/rubyinstaller-devkit-<VERSION>-<ARCH>.exe after building;
the directory only has a sandbox directory and then a .rake file
but no .exe file. Is it somewhere else perhaps? The .7z file exists at the location the README mentions.

**Comment by larskanis** [comment]
Use `rake -T` to inspect all available build targets. `rake ri-msys:ruby-3.0.2-x86-msvcrt` should do the trick.
