### ISSUE TITLE
32 and 64 bit installations using the same registry section

### ISSUE THREAD

**Issue by hurricup** [oneclick/rubyinstaller2#242]
## What problems are you experiencing?
Only one registry entry may present when 32 and 64 bit rubies are installed

## Steps to reproduce
1. Install ruby 2.7 64 bit.
2. Ensure data is correct at `HKEY_CURRENT_USER\SOFTWARE\RubyInstaller\MRI\2.7.4`
3. Install same ruby version 32 bit
4. Ensure that data was overwritten with 32-bit installation information.

**Comment by mohits** [comment]
Hi @hurricup - do you imagine that the problem is when we try to uninstall the package, or something else? In general, I have found that Ruby works fine as long as the Ruby you want to use is ahead in the PATH on WIndows, but I'm not sure if the registry entries have any specific role. I don't use the 32-bit Ruby on my side, but I'm quite sure that your observation must be correct.

**Comment by hurricup** [comment]
In my personal case we use registry to enumerate rubies installed on our CI machine. 
But still this feels not right, make this registy entry kinda meaningless. 
But yes, I'm not aware if this affects anything else.

**Comment by mohits** [comment]
Thanks for the reply. Hopefully, someone else has an opinion on whether that could be changed.

As for multiple Rubies, on Windows, I use pik which stores a file in the user profile folder for the Rubies that you have identified to it. In case you're not familiar with pik, I have a related post here: https://notepad.onghu.com/2021/ruby3-windows-pik-multiple-installations/

**Comment by rubyorails** [comment]
Hi can you help me . i am not able to run my application on rails server.

**Comment by rubyorails** [comment]
booting puma 
rails 6.1.4.1 application starting in development 
rails 'bin/rails server --help' for more startup option
exiting
C:/ruby30-64 ....

this is the error

**Comment by rubyorails** [comment]
booting puma 
rails 6.1.4.1 application starting in development 
rails 'bin/rails server --help' for more startup option
exiting
C:/ruby30-64 ....

this is the error
help me solver this error please
