### ISSUE TITLE
install ruby

### ISSUE THREAD

**Issue by rubyorails** [oneclick/rubyinstaller2#247]

**Comment by rubyorails** [comment]
booting puma 
rails 6.1.4.1 application starting in development 
rails 'bin/rails server --help' for more startup option
exiting
C:/ruby30-64 ....

this is the error

**Comment by larskanis** [comment]
Please don't post unrelated comments to other issues!

Reg. your rails issue, could you please post the full error message and stack trace? Otherwise it's impossible to give any help.
