### ISSUE TITLE
Unable to locate Ruby 2.3 DevKit

### ISSUE THREAD

**Issue by krisbristol40** [oneclick/rubyinstaller2#252]
## What problems are you experiencing?
Having Trouble locating Ruby 2.3.~ Devkit. Would it be possible to provide a link or download attachment?

Thank you!

**Comment by MSP-Greg** [comment]
See https://rubyinstaller.org/downloads/archives/ or https://github.com/oneclick/rubyinstaller/releases/tag/devkit-4.7.2 for the DevKit.

I believe most of the 'packages' are at https://github.com/oneclick/knapsack-recipes/tags

**Comment by krisbristol40** [comment]
Thank you!
