### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Kimo11335** [oneclick/rubyinstaller2#253]
## What problems are you experiencing?
Installation

## Steps to reproduce
Just install and run the command  --> pacman -Syu

## What's the output from version`?

![Capture](https://user-images.githubusercontent.com/49946924/145882041-0eca7574-6e60-4060-8f73-ff7ffc25758d.JPG)

**Comment by larskanis** [comment]
This is a MSYS2 issue. Just google for it or (re-)install a RubyInstaller-Devkit version.
