### ISSUE TITLE
ruby 3.1 download

### ISSUE THREAD

**Issue by dsisnero** [oneclick/rubyinstaller2#255]
## What problems are you experiencing?
Trying to get latest ruby

## Steps to reproduce
Go to https://rubyinstaller.org/downloads/ and no option to download latest ruby

**Comment by rubyFeedback** [comment]
Oh yes I just came here because of the same issue, asking how difficult it would be
to add a ruby 3.1.0 variant for the downloads.

I already tested this version on my Linux box, and the improvements made are quite
nice; I love the improvements to irb or mame's better error reporting.

Would be great to have this on windows available too.

**Comment by MSP-Greg** [comment]
Check the releases here.

https://github.com/oneclick/rubyinstaller2/releases/tag/RubyInstaller-3.1.0-1

**Comment by larskanis** [comment]
Downloads and release post on https://rubyinstaller.org are online now. You should use the release section of this project with caution before it's on rubyinstaller.org. I sometimes revoked it, when there was an issue at final testing. And when it's online, then the downloads.yml can be used to generate the ruby-setup files.

**Comment by larskanis** [comment]
I'm curious about the UCRT change. I hope it works, but let me know if not!

**Comment by MSP-Greg** [comment]
> I hope it works

It works, but Actions & setup-ruby do not...

**Comment by MSP-Greg** [comment]
@larskanis

Have you thought of a PR to ruby/ruby for win32/dll_directory?  Seems reasonable for all the dll resolution issues that come up with Windows...  Thanks for your work on 3.1.0.

Between Christmas and New Years should be a relaxing week.  But, for a few...

**Comment by larskanis** [comment]
> Have you thought of a PR to ruby/ruby for win32/dll_directory?

Yes, could make sense. For now I just wanted a proper and fast solution. For inclusion into ruby it probably requires some discussion about the API first.

**Comment by larskanis** [comment]
> Between Christmas and New Years should be a relaxing week. But, for a few...

In addition I always have two birthdays to celebrate in this week. So yes, a busy week.

**Comment by MSP-Greg** [comment]
> probably requires some discussion about the API first.

True.  Given the issues with dll resolution when relying on `ENV['Path']`, one would think the core team would approve.  A common issue is the OpenSSL dll's installed in `C:/Windows/System32` by whatever that VC build is called...
