### ISSUE TITLE
`ridk install 2 3` fails to install MSYS2 and MINGW development toolchain

### ISSUE THREAD

**Issue by goalkeeper007** [oneclick/rubyinstaller2#258]
## What problems are you experiencing?
On windows server (tried 2012/2019) editions, we have started seeing failures when our scripts run `ridk install 2 3`. 
Error snippet-

`Install MSYS2 and MINGW development toolchain
> pacman -S --needed --noconfirm autoconf autoconf2.13 autogen automake-wrapper automake1.10 automake1.11 automake1.12 a
utomake1.13 automake1.14 automake1.15 automake1.6 automake1.7 automake1.8 automake1.9 diffutils file gawk grep libtool m
4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64
-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthrea
d-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git
error: target not found: automake1.10
error: target not found: automake1.6
error: target not found: automake1.7
error: target not found: automake1.8
error: target not found: automake1.9
warning: file-5.41-2 is up to date -- skipping
warning: gawk-5.1.0-2 is up to date -- skipping
warning: grep-1~3.0-3 is up to date -- skipping
warning: sed-4.8-2 is up to date -- skipping
warning: wget-1.21.2-1 is up to date -- skipping
Install MSYS2 and MINGW development toolchain failed
Traceback (most recent call last):
        16: from C:/tools/ruby26/bin/ridk.cmd:39:in `<main>'
        15: from C:/tools/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/ridk.rb:14:in `run!'
        14: from C:/tools/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/ridk.rb:99:in `install'
        13: from C:/tools/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/components_installer.rb:34:in `install'
        12: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
        11: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
        10: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
         9: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
         8: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
         7: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
         6: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
         5: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
         4: from C:/tools/ruby26/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
         3: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
         2: from C:/tools/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/components/03_dev_tools.rb:55:in `execute'
         1: from C:/tools/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/msys2_installation.rb:197:in `with_msys_apps_enabled'
C:/tools/ruby26/lib/ruby/site_ruby/2.6.0/ruby_installer/runtime/components/03_dev_tools.rb:62:in `block in execute': pacman failed (RuntimeError)`

## Steps to reproduce
1. We install msys2 using `choco install msys2 -y --params "/NoUpdate"`
2. Update pacman using `ridk exec pacman -Syu --noconfirm`
3. `ridk install 2 3`

I have tried to upgrade msys2 version from 

## What's the output from `ridk version`?
PS C:\Users\SVC-QA> ridk version
---
ruby:
  path: C:/tools/ruby26
  version: 2.6.5
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.5-1
  git_commit: d3e0c65
msys2:
  path: C:\tools\msys64
sh: GNU bash, version 5.1.8(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.3.9600]

**Comment by goalkeeper007** [comment]
upgrading to ruby 2.7 fixed the issue for us.

**Comment by larskanis** [comment]
Latest releases fix this issue.
