### ISSUE TITLE
Encoding? Problem in irb 3.1.0 (Windows 10)

### ISSUE THREAD

**Issue by nerdcraft-muc** [oneclick/rubyinstaller2#259]
## What problems are you experiencing?

Since the update to 3.1.0 via RubyInstaller under Win 10 there is a problem with alt gr in irb. When I try to enter "{" ( German keyboard "alt gr + {" ) I get "^[{".

 3.0.2 was working fine.

## Steps to reproduce

open irb 
enter alt gr + {

## What's the output from `ridk version`?

ruby:
  path: C:/Ruby31-x64
  version: 3.1.0
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.0-1
  git_commit: a1972fd
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev5, Built by MSYS2 project) 11.2.0
sh: GNU bash, Version 5.1.8(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.1415]

![irb](https://user-images.githubusercontent.com/95968772/150947720-6b3cdb13-d962-46ad-9016-80e7fd290f05.PNG)

**Comment by larskanis** [comment]
This issue is [fixed in reline](https://github.com/ruby/reline/pull/425). There's no release yet, but for the time being, you can update reline like so:

```sh
git clone https://github.com/ruby/reline
cd reline
rake install
```

**Comment by nerdcraft-muc** [comment]
Thanks a lot!
