### ISSUE TITLE
not able to install jekyll

### ISSUE THREAD

**Issue by AndreLau11** [oneclick/rubyinstaller2#261]
## What problems are you experiencing?
Windows

## Steps to reproduce
does not found the jekyll package, so I can not run anything.

## What's the output from `ridk version`?
jekyll: command not found

**Comment by mohits** [comment]
@AndreLau11 - did you install the ruby gem for Jekyll?

You would need to open a command prompt and then do:
`gem install jekyll`

After that, you would be able to do `jekyll` something.

Hope this helps.

Cheers!

**Comment by AndreLau11** [comment]
it gives me this issue
[image: image.png]

**Comment by mohits** [comment]
Hi @AndreLau11  - I'm sorry that you image did not make it through to GitHub for some reason. Could you paste it into the web page at: https://github.com/oneclick/rubyinstaller2/issues/261#issuecomment-1066216562

**Comment by mohits** [comment]
Hi @AndreLau11, I am closing this issue. Please feel free to reopen it if you still have this problem.
