### ISSUE TITLE
not able to install jekyll

### ISSUE THREAD

**Issue by aadil42** [oneclick/rubyinstaller2#262]

**Comment by aadil42** [comment]
3.0.3-1

**Comment by mohits** [comment]
hi @aadil42 -  you install the ruby gem for Jekyll?

You would need to open a command prompt and then do:
gem install jekyll

After that, you would be able to do jekyll something.

Hope this helps.

Cheers!

This is same as #261 probably.

**Comment by mohits** [comment]
Hi @aadil42 - I am closing this issue. Please feel free to reopen it if you still have this problem.

**Comment by aadil42** [comment]
Sure man, you can close it.
