### ISSUE TITLE
could not be found

### ISSUE THREAD

**Issue by AbdullahKarson** [oneclick/rubyinstaller2#263]

**Comment by mohits** [comment]
Hi @AbdullahKarson - could you be a bit more specific on what could not be found?

I was able to download Ruby 3.1.1 for Windows from: https://rubyinstaller.org/downloads/ as expected.

**Comment by mohits** [comment]
Hi @larskanis - since we have not heard back from @AbdullahKarson for about 10+ days, let's assume we can close this.
