### ISSUE TITLE
SL verification error at depth 4: unable to get local issuer certificate (20)

### ISSUE THREAD

**Issue by MiPi12** [oneclick/rubyinstaller2#270]
Hi, when I try to install eyaml tool. First I installed Ruby which worked.
The i try to install the tool gem install hiera-eyaml and get the error message 
ERROR:  SSL verification error at depth 4: unable to get local issuer certificate (20)
ERROR:  You must add /C=US/ST=Texas/L=Austin/O=Forcepoint LLC/CN=Forcepoint Cloud CA to your local trusted store

I tried updateing the Certificate but still got the error. Any ideas how to fix this or is my Forcepoint blocking this?

**Comment by larskanis** [comment]
Yes, Forcepoint seems to fool you. Check out [this instruction](https://github.com/oneclick/rubyinstaller2/blob/master/resources/ssl/README-SSL.md) about how to adjust RubyInstaller's certificate stores.

**Comment by MiPi12** [comment]
That fixed the first issue.
