### ISSUE TITLE
[Documentation] Would it be possible to mention which stdlib and add-ons are available on the ruby one click installer?

### ISSUE THREAD

**Issue by rubyFeedback** [oneclick/rubyinstaller2#278]
Hey there Lars,

I am using ruby on linux most of the time, things work fine there.

On windows I use the one click installer.

Now I spend most of my time writing on linux, so I have only limited time to
test on windows. I have a windows machine at home so it is not a big deal.

Right now I am working with readline. But I don't know whether readline
support is available in the one click installed ruby.exe for windows. Same
with openssl. I can test at a later time, so it's not a high priority thing.

But, if you'd have some time, could you perhaps add some document or
something that explains which is all available on default on windows? 
Perhaps readline support is available via some add-on or something so 
any primer in this regard may be useful, just to specify.

**Comment by mohits** [comment]
hi @rubyFeedback - do you mean a list of gems that are installed by default? I did a `gem list` and this is what I got

```*** LOCAL GEMS ***

abbrev (default: 0.1.0)
base64 (default: 0.1.1)
benchmark (default: 0.2.0)
bigdecimal (default: 3.1.1)
bundler (default: 2.3.7)
cgi (default: 0.3.1)
csv (default: 3.2.2)
date (default: 3.2.2)
debug (1.4.0)
delegate (default: 0.2.0)
did_you_mean (default: 1.6.1)
digest (default: 3.1.0)
drb (default: 2.1.0)
english (default: 0.7.1)
erb (default: 2.2.3)
error_highlight (default: 0.3.0)
etc (default: 1.3.0)
fcntl (default: 1.0.1)
fiddle (default: 1.1.0)
fileutils (default: 1.6.0)
find (default: 0.1.1)
forwardable (default: 1.3.2)
getoptlong (default: 0.1.1)
io-console (default: 0.5.11)
io-nonblock (default: 0.1.0)
io-wait (default: 0.2.1)
ipaddr (default: 1.2.4)
irb (default: 1.4.1)
json (default: 2.6.1)
logger (default: 1.5.0)
matrix (0.4.2)
minitest (5.15.0)
mutex_m (default: 0.1.1)
net-ftp (0.1.3)
net-http (default: 0.2.0)
net-imap (0.2.3)
net-pop (0.1.1)
net-protocol (default: 0.1.2)
net-smtp (0.3.1)
nkf (default: 0.1.1)
observer (default: 0.1.1)
open-uri (default: 0.2.0)
open3 (default: 0.1.1)
openssl (default: 3.0.0)
optparse (default: 0.2.0)
ostruct (default: 0.5.2)
pathname (default: 0.2.0)
power_assert (2.0.1)
pp (default: 0.3.0)
prettyprint (default: 0.1.1)
prime (0.1.2)
pstore (default: 0.1.1)
psych (default: 4.0.3)
racc (default: 1.6.0)
rake (13.0.6)
rbs (2.1.0)
rdoc (default: 6.4.0)
readline (default: 0.0.3)
reline (default: 0.3.0)
resolv (default: 0.2.1)
resolv-replace (default: 0.1.0)
rexml (3.2.5)
rinda (default: 0.1.1)
rss (0.2.9)
ruby2_keywords (default: 0.0.5)
securerandom (default: 0.1.1)
set (default: 1.0.2)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
stringio (default: 3.0.1)
strscan (default: 3.0.1)
tempfile (default: 0.1.2)
test-unit (3.5.3)
time (default: 0.2.0)
timeout (default: 0.2.0)
tmpdir (default: 0.1.2)
tsort (default: 0.1.0)
typeprof (0.21.2)
un (default: 0.2.0)
uri (default: 0.11.0)
weakref (default: 0.1.1)
win32ole (default: 1.8.8)
yaml (default: 0.2.0)
zlib (default: 2.1.1)
```

List also online at: https://notepad.onghu.com/2022/ruby3.1-windows-day0-install-hello_world/

On `readline` and `reline`, this is what it says:
```
readline (default: 0.0.3)
reline (default: 0.3.0)
```

**Comment by MSP-Greg** [comment]
@rubyFeedback

openssl - it has always been included in Windows Rubies.  Currently, Rubies 2.5 and later are built with OpenSSL 1.1.1.

readline - since it's been problematic in the past, it is removed in RubyInstaller2 builds, which then loads reline.  I have built master with OpenSSL 3.

If you want to work with readline, it is installed (both readline.so file and readline dll) in the ruby-loco master builds.  Note that the `readline.so` file is renamed `readline.so_`.  The mingw & ucrt builds use the MSYS2 readline package, the mswin build uses the vcpkg package.

Builds are at:

https://github.com/MSP-Greg/ruby-loco/releases/tag/ruby-master

I use the builds locally, and generate https://msp-greg.github.io/ with them, but most of my 'Ruby' time is spent on WSL2/Ubuntu.  I haven't worked with readline at all...
