### ISSUE TITLE
Add artifacts: devkit.7z and rubyinstaller-devkit.7z

### ISSUE THREAD

**Issue by ccmywish** [oneclick/rubyinstaller2#281]
Hi @larskanis 

I'm currently working on https://github.com/ccmywish/rbenv-for-windows

Please see what problem I have met and why I issue this:  #ccmywish/rbenv-for-windows/issues/3

As the issue describes, could you help add another two build artifacts to GitHub release?
1. devkit.7z
2. rubyinstaller-devkit-.7z

Thanks 

<br>

**Comment by larskanis** [comment]
I think `rubyinstaller-devkit-.7z` should contain what the corresponding exe file contains. This is already in the rake tasks, but not executed in the CI. I can enable this file creation and upload.

What shall the devkit-.7z file contain?

**Comment by ccmywish** [comment]
> I think `rubyinstaller-devkit-.7z` should contain what the corresponding exe file contains. This is already in the rake tasks, but not executed in the CI. I can enable this file creation and upload.
> 
> What shall the devkit-.7z file contain?

Thanks for replying! 

`devkit-.7z` should be the `rubyinstaller-devkit-.7z` minus the `Ruby` part, that is the `msys64` directory only.

**Comment by ccmywish** [comment]
Hi, @larskanis 

I've done it another way:
1. Directly download the `rubyinstaller-devkit-.exe` 
2. Install it
3. Remove the registry info
4. Move msys64 out

So, this issue can be closed without doing anything else.

I think the main features of `rbenv for Windows` are completed (though with obvious flaws), it uses the great of `RubyInstaller`, thank you for developing and maintaining this awesome software for Ruby community for so many years!
 

I would be very happy if you could give it a try~
https://github.com/ccmywish/rbenv-for-windows
