### ISSUE TITLE
ridk install command failing

### ISSUE THREAD

**Issue by Seraph27** [oneclick/rubyinstaller2#286]
## What problems are you experiencing?
I'm following steps in order to use jekyll, but when I run ridk install, it says pacman failed. Using solutions provided online doesn't work. 
![image](https://user-images.githubusercontent.com/42664208/174052654-9c602a89-3481-4878-9e19-dfd3e0b859c6.png)
![image](https://user-images.githubusercontent.com/42664208/174052766-cf5b3f4c-f4a1-435c-b41d-b8bf0dfb041c.png)

## Steps to reproduce
running `ridk install`, then Enter on my machine

## What's the output from `ridk version`?
![image](https://user-images.githubusercontent.com/42664208/174052838-74b88d60-70f4-4d75-a2a1-a40e083a3d4f.png)

**Comment by mohits** [comment]
Hi @Seraph27 - sorry for the delay in getting to you. Did you install the Devkit with Ruby 3.1 or are you using msys2 from a different directory? In general, I would recommend doing the full installation using the package from the RubyInstaller2 site and setting up DevKit (with msys2) as part of that to avoid subtle incompatibilities.

My installation notes are here (if it helps): https://notepad.onghu.com/2022/ruby3.1-windows-day0-install-hello_world/

**Comment by mohits** [comment]
Hi @Seraph27 - since we did not hear back from you, I hope that this issue is resolved, and this is no longer relevant. I will close the issue but feel free to re-open it if it needed.
