### ISSUE TITLE
Could not find valid gem "jekyll"

### ISSUE THREAD

**Issue by adridos** [oneclick/rubyinstaller2#289]
## What problems are you experiencing?
Following the steps on Jekyllrb to install jekyll on my windows laptop. When typing gem install jekyll bundler, output reads "Unable to download data from https://rubygems.org/ - SocketError: Failed to open TCP connection to rubygems.org:443 (getaddrinfo: No such host is known. ) (https://rubygems.org/specs.4.8.gz)
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SocketError: Failed to open TCP connection to rubygems.org:443 (getaddrinfo: No such host is known. ) (https://rubygems.org/specs.4.8.gz)"

## Steps to reproduce
in terminal, type:     gem install jekyll bundler
you can then type jekyll -v to see nothing was installed

## What's the output from `ridk version`?

bash.exe: warning: could not find /tmp, please create!
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.2
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.2-1
  git_commit: 17502f9
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.1706]

**Comment by MSP-Greg** [comment]
@adridos Maybe an issue with Windows Firewall?  Is Ruby listed as an 'allowed app'?

**Comment by mohits** [comment]
@adridos - It could also be an issue if you are required to use a proxy to access HTTP endpoints. If that's the case, the answer at: https://stackoverflow.com/a/29784068 might help a bit.

**Comment by adridos** [comment]
Would working remotely using a VPN be an issue when it comes to the proxy accessing HTTP endpoints?

**Comment by larskanis** [comment]
> Would working remotely using a VPN be an issue when it comes to the proxy accessing HTTP endpoints?

If the VPN is down, the proxy will probably be unreachable. But those are kind of questions you have to ask your system administrators.

**Comment by mohits** [comment]
Hi @adridos - may I close this issue?

**Comment by adridos** [comment]
yes thank you!
________________________________
