### ISSUE TITLE
Lint code with Rubocop

### ISSUE THREAD

**Issue by ashmaroli** [oneclick/rubyinstaller2#29]
Lets lint the Ruby code with Rubocop and maintain uniformity throughout the codebase, especially acting as a guideline for future contributors to write consistent code with current style.

Additionally, conform to Community Style Guidelines followed by Rubocop.

**Comment by larskanis** [comment]
Do you work on anything related to the above ideas? For now I don't plan to implement or enforce any of these. Rather I think commenting the code would be more helpful. However feel free to open a pull request, for any practical additions.
