### ISSUE TITLE
jekyll is not recogonized as an internal or external command

### ISSUE THREAD

**Issue by Athila-Salim** [oneclick/rubyinstaller2#297]

**Comment by mohits** [comment]
Hi, could you share a bit more about your problem? What did you install? Did you install the Jekyll gem?

**Comment by Athila-Salim** [comment]
Hi
First I installed Ruby and ruby is correctly installed in my laptop but 1
gem only installed and then I enter jekyll -v  in command prompt but the
system view this "jekyll is not recogonized as an internal or external
command". This is my issue. How did I resolve this problem?
Thank you

**Comment by mohits** [comment]
Great.

So, from a command prompt, I guess you are able to do:
$ ruby -v
(Could you share the output you see?)

Then, could you do:
gem install jekyll

Let us know if you see an error.

After that, you should be able to do:
jekyll -v
Or other commands.

Good luck. We are here to help 👍

**Comment by mohits** [comment]
Hi @Athila-Salim - once you confirm that this is OK, I will close it... or next week if we don't hear from you.

**Comment by mohits** [comment]
Hi @Athila-Salim - we have not heard from you, so I hope that it's all working fine for you. I will close this issue now.
