### ISSUE TITLE
Jekyll not installed properly

### ISSUE THREAD

**Issue by Kanika637** [oneclick/rubyinstaller2#300]
## What problems are you experiencing?

After following all the steps, when I write `jekyll -v` , I get this error `'jekyll' is not recognized as an internal or external command,
operable program or batch file.`

## What's the output from `ridk version`?
It gives me 3 options and I enter the third one and then it installs it successfully.

**Comment by mohits** [comment]
Hi @Kanika637 - after installing Ruby using the OneClick Installer, did you also install jekyll?

It's done by opening a command prompt, and then doing:
gem install jekyll 

After that, you should be able to do:
jekyll -v

If something fails, could you also share the output or errors you are seeing?

**Comment by mohits** [comment]
Hi @Kanika637 - we have not heard from you, so I hope that it's all working fine for you. I will close this issue now.

**Comment by Kanika637** [comment]
Yes, it did work, Thanks!
