### ISSUE TITLE
Failure to install jekyll

### ISSUE THREAD

**Issue by sqak-sqak-izardrone** [oneclick/rubyinstaller2#301]
## What problems are you experiencing?

I installed ruby and Devkit by the steps of jekyll instruction, then ran

gem install bundler

first, it worked, but then when running 

gem install jekyll

it failed, giving 
"
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.
" and
"
Assembler messages:
Error: can't open C:\Users\����\AppData\Local\Temp\ccWoFZzs.s for reading: Illegal byte sequence
"

## Steps to reproduce

As above

## What's the output from `ridk version`?

ruby:
  path: D:/Ruby31-x64
  version: 3.1.2
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.2-1
  git_commit: 17502f9
msys2:
  path: D:\Ruby31-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 11.2.0
sh: GNU bash，版本 5.1.16(1)-release (x86_64-pc-msys)
os: Microsoft Windows [�汾 10.0.19044.1889]

**Comment by mohits** [comment]
Hi @sqak-sqak-izardrone - were you able to resolve this?

**Comment by larskanis** [comment]
I think this is the same issue as #320. The next release series will fix this.
