### ISSUE TITLE
Package Windows Ruby 3.1 with latest Bundler + Rubygems

### ISSUE THREAD

**Issue by johnnyshields** [oneclick/rubyinstaller2#302]
In the version of Bundler and Rubygems packaged with Windows Ruby 3.1, they seem to be treating `x64-mingw-ucrt` as `"ruby"` platform, and as a result, out-of-the-box they fail to `bundle install` a gemfile with mixed-platform gems.

Upgrading Rubygems and Bundler fixes the problem (myself and others did some commits to fix this.) It would be nice if Ruby Windows Installer could Ruby 3.1 with the latest versions to work around this issue.

**Comment by larskanis** [comment]
It took a while, but RubyInstaller-3.1.3-1 updates bundler and rubygems.
