### ISSUE TITLE
I've got an error while try installing jekyll on windows 10

### ISSUE THREAD

**Issue by krdsah** [oneclick/rubyinstaller2#304]
C:\Users\Nrechel>gem install jekyll bundler
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/eventmachine-1.2.7/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r ./siteconf20220915-8492-43l96a.rb extconf.rb
checking for -lcrypto... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby31-x64/bin/$(RUBY_BASE_NAME)
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
        --with-crypto-dir
        --without-crypto-dir
        --with-crypto-include
        --without-crypto-include=${crypto-dir}/include
        --with-crypto-lib
        --without-crypto-lib=${crypto-dir}/lib
        --with-cryptolib
        --without-cryptolib
C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:498:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:591:in `try_link0'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:609:in `try_link'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:837:in `try_func'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1065:in `block in have_library'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1007:in `block in checking_for'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:362:in `block (2 levels) in postpone'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:362:in `block in postpone'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:332:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:358:in `postpone'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1006:in `checking_for'
        from C:/Ruby31-x64/lib/ruby/3.1.0/mkmf.rb:1060:in `have_library'
        from extconf.rb:8:in `block in check_libs'
        from extconf.rb:8:in `all?'
        from extconf.rb:8:in `check_libs'
        from extconf.rb:95:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/eventmachine-1.2.7/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/eventmachine-1.2.7 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/eventmachine-1.2.7/gem_make.out
Successfully installed bundler-2.3.22
Parsing documentation for bundler-2.3.22
Done installing documentation for bundler after 2 seconds
1 gem installed

C:\Users\Nrechel>jekyll -v
'jekyll' is not recognized as an internal or external command,
operable program or batch file.

**Comment by mohits** [comment]
Hi @krdsah - could you try this on a command prompt

```
C:\Ruby31-x64\ridk_use\ridk.cmd enable
... you will see lots of stuff showing including your PATH...

gem install jekyll bundler
```

**Comment by CheapMeow** [comment]
> Hi @krdsah - could you try this on a command prompt
> 
> ```
> C:\Users\Nrechel>C:\Ruby31-x64\ridk_use\ridk.cmd enable
> ... you will see lots of stuff showing including your PATH...
> 
> C:\Users\Nrechel>gem install jekyll bundler
> ```
> 
> I hope that works for you.

It is worth mentioned that, as for me, only when I use cmd for ruby in Admin mode, then `gem install jekyll bundler`, can I get jekyll truly indexed.

**Comment by peacefulbyte** [comment]
> Hi @krdsah - could you try this on a command prompt
> 
> ```
> C:\Users\Nrechel>C:\Ruby31-x64\ridk_use\ridk.cmd enable
> ... you will see lots of stuff showing including your PATH...
> 
> C:\Users\Nrechel>gem install jekyll bundler
> ```
> 
> I hope that works for you.

I've tried it , and it works for me.
