### ISSUE TITLE
'jekyll' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

### ISSUE THREAD

**Issue by wandtsks** [oneclick/rubyinstaller2#305]

**Comment by ParadoxV5** [comment]
您安装了`jekyll`没？ / Have thee installed `jekyll`?

`gem install jekyll`

**Comment by wandtsks** [comment]
_Download and install a Ruby+Devkit version from [RubyInstaller Downloads](https://rubyinstaller.org/downloads/). Use default options for installation.
Run the step on the last stage of the installation wizard. This is needed for installing gems with native extensions. You can find additional information regarding this in the [RubyInstaller Documentation](https://github.com/oneclick/rubyinstaller2#using-the-installer-on-a-target-system). From the options choose .ridk installMSYS2 and MINGW development tool chain
Open a new command prompt window from the start menu, so that changes to the environment variable becomes effective. Install Jekyll and Bundler using **PATHgem install jekyll bundler**
Check if Jekyll has been installed properly: **jekyll -v**_



I have done the third step, but the fourth part  when I entering "jekyll - v"   will display ['jekyll' 不是内部或外部命令，也不是可运行的程序 或批处理文件。]
