### ISSUE TITLE
./io/event/selector/selector.c:26:10: fatal error: sys/wait.h: No such file or directory

### ISSUE THREAD

**Issue by rxa1031** [oneclick/rubyinstaller2#306]
Hi,

Unable to install _github_changelog_generator_ after installing **Ruby + DevKit**. I've used both the Ruby + DevKit versions 3.1.2-1 x64 and 3.0.41 x64.

Reported error:
![image](https://user-images.githubusercontent.com/18160755/192227650-4c60862d-9e4f-4ce6-8ebe-8a68e80bc330.png)

Regards,
Rajeev

**Comment by larskanis** [comment]
This is an issue of the `io-event` gem. There seems to be some [experimental Windows support](https://github.com/socketry/io-event/pull/37), that you could try out by inserting that into your `Gemfile`:

```ruby
gem "io-event", git: "https://github.com/sevenc-nanashi/io-event", branch: "add/support-windows"
```

**Comment by ioquatix** [comment]
`io-event` now works on Windows. Whether Async works is another question, most of the tests are passing but not all of them.

![image](https://user-images.githubusercontent.com/30030/195801323-13952eee-ba12-4a3b-a910-cb9ef2b27202.png)
