### ISSUE TITLE
Issues installing Jekyll

### ISSUE THREAD

**Issue by pbrowne011** [oneclick/rubyinstaller2#312]
## What problems are you experiencing?
Hi! I'm having trouble installing jekyll onto my Windows laptop. Every time I do, there is an error to "build gem native extension". I believe it occurs because the file path is \(x86\)GnuWin32docmake3.81, which combines it all into one string rather than GnuWin32\doc\make\3.81

Full documentation:

Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:/Ruby31-x64/bin/ruby.exe -I C:/Ruby31-x64/lib/ruby/3.1.0 -r ./siteconf20221015-16400-1c7giv.rb extconf.rb
creating Makefile

current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:Program Files \(x86\)GnuWin32docmake3.81 DESTDIR\= clean
current directory: C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0/ext
C:Program Files \(x86\)GnuWin32docmake3.81 DESTDIR\=
make failedNo such file or directory - C:Program

Gem files will remain installed in C:/Ruby31-x64/lib/ruby/gems/3.1.0/gems/sassc-2.4.0 for inspection.
Results logged to C:/Ruby31-x64/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/sassc-2.4.0/gem_make.out
Successfully installed bundle-0.0.1
Parsing documentation for bundle-0.0.1
Done installing documentation for bundle after 0 seconds
1 gem installed

## Steps to reproduce
I installed Ruby this morning, made sure g++ and gcc were installed, also installed make, and then tried installing jekyll

## What's the output from `ridk version`?
ruby:
  path: C:/Ruby31-x64
  version: 3.1.2
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.2-1
  git_commit: 17502f9
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.22000.1098]

**Comment by larskanis** [comment]
This looks like you `PATH` environment variable has this `GnuWin32` path in front of ruby`s path. This doesn't work. You should have a look into the system and per-user environment variables and make sure, the ruby path is before any other make executables. You can also try to set ruby environment variables by entering `ridk enable` in the console before installing jekyll.

**Comment by pbrowne011** [comment]
Shoot, thanks for letting me know! I'll work on that now (sorry, a bit new to this at the moment, should've posted on StackOverflow first).
