### ISSUE TITLE
Where do I find the CLI for rdik install?

### ISSUE THREAD

**Issue by echochalet** [oneclick/rubyinstaller2#316]
I'm a newbie and want to learn how to use Jekyll.   My first question is whether to use the "Deploy Jekyll site using AWS Amplify" or should I use the Windows installer on my local machine?   I was successful in installing but can't figure out how to run the rdik install command.    How do I invoke the CLI in windows for Ruby?  When I use my normal Windows CLI it does not work.
![rdik](https://user-images.githubusercontent.com/46800471/203024298-36325a74-6763-49a6-b956-981c7aee41f4.jpg)

## Steps to reproduce

![rdik](https://user-images.githubusercontent.com/46800471/203024645-a955caec-6d40-4365-81dd-aea467dcc156.jpg)

## What's the output from `ridk version`?
Should I switch to a Linux computer as the documentation for using Jekyll seems imcomplete.

**Comment by larskanis** [comment]
You can use a normal Windows command prompt. Either `cmd` or `powershell`. But it's `ridk` not `rdik`! Jekyll should work as described here under "Installation via RubyInstaller": https://jekyllrb.com/docs/installation/windows/
