### ISSUE TITLE
Ruby for windows installation

### ISSUE THREAD

**Issue by stepapu** [oneclick/rubyinstaller2#318]
## What problems are you experiencing?

Hello, I am following this guide - https://jekyllrb.com/docs/installation/windows/

I have problems after step 4.

## What's the output from `ridk version`?

ridk version
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.3
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.3-1
  git_commit: a09714d
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev6, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.2251]

Thank you for any help.

**Comment by larskanis** [comment]
You get an output from `ridk version` - that's good. Then just repeat the jekyll installation like so: `gem install jekyll`

If that succeeds, then the `jekyll` command should work as well. If not, then it could be a network issue.

**Comment by mohits** [comment]
Hi @stepapu - has this worked for you? Could you close the issue if it has? Else, I will assume all is well and close it next week. Thanks.
