### ISSUE TITLE
Install ruby machine wide

### ISSUE THREAD

**Issue by bokkabonga** [oneclick/rubyinstaller2#321]
Hey everyone,

i was just wondering if it is possible to install ruby machine wide for all users. The Installer always just seems to make ruby available for the user that launched the installer. The uninstall regsitry key will also be created in that users registry hive.

Is there any way to make the installation machine wide?

**Comment by larskanis** [comment]
Yes, the installer uses machine wide entries if you login with an administrator account and run the installer file per right click and "Run as administrator". 

I already wondered if there could be a way to request a system wide install within the installer, but so far it is not implemented. If I remember right, the installer used to open the UAC dialog and did a system wide installation, when run by an user from the administrator group. But I noticed that this isn't done now (on Windows 10) but instead a single user installation is done.

So you can keep this ticket open as a reminder to introduce a more intuitive way to install system wide.

**Comment by bokkabonga** [comment]
Can´t confirm that. I have been testing a silent Install via CMD (with admin privilege) before that to test the options for our software deployment.

But not beeing able to install for all users on the system is a definite no-go.

**Comment by larskanis** [comment]
> Can´t confirm that.

What can't you confirm?

**Comment by larskanis** [comment]
Next release series of RubyInstaller will get a selection dialog to decide between per-user and machine wide installation. The latter one requires Administrator privileges and shows up a UAC dialog.

This is implemented in commit 4382f99bf21608a3e37b6eabe861dca5e1f015f5 . The silent install options are described in https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-silent-install .

I plan to release these changes within the next week.

**Comment by larskanis** [comment]
The RubyInstaller version 3.2.0-1 has support for machine wide installation: https://rubyinstaller.org/2022/12/29/rubyinstaller-3.2.0-1-released.html

Could you give it a try? I'd like to get some feedback before the older stable branches are updated accordingly.

**Comment by bokkabonga** [comment]
Sorry for the late reply. As far as i tested it, it seems to work just fine. Thanks a lot!
