### ISSUE TITLE
switch for user vs machine install?

### ISSUE THREAD

**Issue by baywet** [oneclick/rubyinstaller2#326]
## What problems are you experiencing?

I've been working to make the devkit 3.2 version available on winget https://github.com/microsoft/winget-pkgs/pull/92456
The validation is failing because 3.2 introduces a new choice user install vs machine install. Which results in a prompt, hanging the machine.

## Steps to reproduce

Make sure you're on windows 10 1809 or later.
Make sure [winget is installed](https://www.microsoft.com/p/app-installer/9nblggh4nns1)

1. clone https://github.com/baywet/winget-pkgs/
2. `git switch feature/ruby-with-devkit-3-2`
3. run an admin prompt
4. `winget install -m <path to repo>/manifests/r/RubyInstallerTeam/RubyWithDevKit/3/2/3.2.0-1`

A prompt asking you to choose between user or machine install shows up. Even though the installation is silent.

## What's the output from `ridk version`?

not sure, it'd be nice if the issue template included the steps to get that information.

**Comment by larskanis** [comment]
You have to use `/currentuser` or `/allusers` options of the installer.

The Wiki is already up-to-date regarding the new dialog: https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-silent-install

**Comment by baywet** [comment]
thanks for the blazing fast response, I was able to fix the manifest. Closing.
