### ISSUE TITLE
Support Ruby 2.3 on rubyinstaller2 MSYS2

### ISSUE THREAD

**Issue by johnnyshields** [oneclick/rubyinstaller2#33]
There are certain gems, e.g. [bson-ruby](https://jira.mongodb.org/browse/RUBY-1200) which fail to build on Ruby 2.3 without MSYS2.

It would be nice to switch the Ruby 2.3 build to use rubyinstaller2 if possible.

**Comment by larskanis** [comment]
It is not difficult to add Ruby-2.3 to RubyInstaller2. But it is difficult to tell the people which version of Ruby requires which version of Devkit/MSYS2. So IMHO we should provide Ruby-2.4 only as "official" release based on RubyInstaller2.

**Comment by johnnyshields** [comment]
@larskanis that's fine by me, if there could be just an internally built (but not advertised) place I can download the .msi installer for Ruby 2.3 it would be perfect.

**Comment by larskanis** [comment]
You can download RubyInstaller2 based Ruby-2.3.4 from appveyor: https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor/build/1.0.25
