### ISSUE TITLE
downloaded ruby installer and then did gem install jekyll bundler, but cannot find jekyll -v it says 'jekyll' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Dolphins07** [oneclick/rubyinstaller2#339]

**Comment by mohits** [comment]
Hi @Dolphins07 - could you try https://jekyllrb.com/docs/installation/windows/ and see if there are still problems? if this is no longer relevant would you close it? I'll close it on 27th Dec if we don't hear by then. Thanks!
