### ISSUE TITLE
Wrong interpreter in rake script

### ISSUE THREAD

**Issue by barkerest** [oneclick/rubyinstaller2#34]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

Included bin/rake script is using "/mingw64/bin/ruby.exe" for the interpreter.
Issue was resolved by changing the interpreter to "/usr/bin/env ruby" to match the other scripts.

## Steps to reproduce

Open mingw64 msys shell, execute "rake".

## What's the output from `ridk version`?

---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1rc2
  git_commit: 1b324f5
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)

**Comment by larskanis** [comment]
From powershell or cmd usually the file `rake.cmd` is executed instead of `rake`. So you're using bash as shell?

**Comment by barkerest** [comment]
I prefer bash over cmd.

**Comment by larskanis** [comment]
Can you please try out the artifact when the build is finished: https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor/build/1.0.22/job/gd5pwj5hi9bq0w54

**Comment by barkerest** [comment]
Extracted the artifact and it fixes the issue.
