### ISSUE TITLE
Missing JS Files

### ISSUE THREAD

**Issue by ghost** [oneclick/rubyinstaller2#341]
## What problems are you experiencing?
In terminal in VS Code, I'm getting a lot of "FIle Not Found" errors on some JS files. All of them seem to be located in the /assets/js/dist folder. Also, instead of a blank copy of Chirpy with no preinstalled blog entries, like I'm expecting to see. Instead, I see blog entries from the About Chirpy like what you see on GitHub.

## Steps to reproduce
First enounter. I didn't reproduce the issue thinking I can simply erase the extra content and then add my own.
![Screenshot 2023-04-29 130506](https://user-images.githubusercontent.com/131908010/235314850-4c41f359-e44b-4590-81b6-b7c82310f396.png)

## What's the output from `ridk version`?
I installed Ruby on Windows. At the end of the installation with the progress bar, I was then asked if I wanted ridk? So I said yes.

**Comment by mohits** [comment]
hi @HirohitoHigashi - this was opened quite a while back. Should we close this? If we don't hear back by 27th, I will close this!

**Comment by HirohitoHigashi** [comment]
This is not an issue I opened, so I have no opinion.

**Comment by mohits** [comment]
> This is not an issue I opened, so I have no opinion.

I'm sorry @HirohitoHigashi. I meant to tag the original poster and made a mistake since I think I was on mobile. The user's account has been deleted, so I will close the issue. 👍
