### ISSUE TITLE
503 error on attempted RubyInstaller download

### ISSUE THREAD

**Issue by n8jhj** [oneclick/rubyinstaller2#346]
## What problems are you experiencing?
When attempting to download the latest version of RubyInstaller at https://rubyinstaller.org/downloads/, I get a 503 error:

Error 503 Backend unavailable, connection timeout
Backend unavailable, connection timeout

Error 54113
Details: cache-bfi-kbfi7400048-BFI 1688061404 2016711213

Varnish cache server

## Steps to reproduce
Try downloading RubyInstaller from the above-mentioned link via Firefox or Edge.

## What's the output from `ridk version`?
NA.

**Comment by n8jhj** [comment]
The issue seems to have resolved itself. I just had a successful download.

**Comment by larskanis** [comment]
Ok, good to know.
