### ISSUE TITLE
0001-mingw-w64-time-functions.patch

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#35]
I'm fairly certain that `__MINGW64_VERSION_MAJOR` is defined for the current release of MinGW / MSYS2.

See https://gist.github.com/jonforums/968522.

Hence, I suspect the patch [0001-mingw-w64-time-functions.patch](https://github.com/oneclick/rubyinstaller2/blob/master/recipes/compile/ruby-2.4.1/0001-mingw-w64-time-functions.patch) is no longer needed.

I haven't been using it with my local builds for quite a while, and I'm around ten total failures and errors using `--with-out-ext=pty,syslog`.

Again, thanks for all your work.

**Comment by MSP-Greg** [comment]
@larskanis Thank you
See 46e1803

**Comment by larskanis** [comment]
@MSP-Greg Thanks for the hint! This issue has been the trigger to re-check the patches, but I didn't remember it.

**Comment by MSP-Greg** [comment]
@larskanis Not being a c type, I thought having you check it would be appropriate.

I've been building parallel for while, but at some point I added [include_ruby_defines.h.patch](https://github.com/MSP-Greg/ruby-loco/blob/master/patches/include_ruby_defines.h.patch).  It's very similar to [0002-use-gnu-printf.patch](https://github.com/oneclick/rubyinstaller2/blob/master/recipes/compile/ruby-2.4.1/0002-use-gnu-printf.patch), but changes [include/ruby/defines.h](https://github.com/ruby/ruby/blob/trunk/include/ruby/defines.h#L87).

I haven't tried a recent build with it removed, but it doesn't seem to cause any issues.  If you get a chance to look at it, let me know if it's required...

FYI, there are a few recent trunk commits that affected encoding and temp files.  My `test-all` has gone from 5 failures & 0 errors to 6 failures & 1 errors.  `test-rubyspec` ran parallel previously, now it will not...  ruby-loco...

Lastly, I recently build [eventmachine](https://github.com/eventmachine/eventmachine) with SSL support using my [MinGW OpenSSL 1.1.0f package](https://github.com/MSP-Greg/ruby-loco/releases).  I should probably update it, as OpenSSL stable has had quite a few commits.  Should work with the standard MinGW package also.

**Comment by larskanis** [comment]
@MSP-Greg Did you file the gnu-printf issue on the ruby bug tracker, already?

**Comment by MSP-Greg** [comment]
@larskanis 

I mentioned them right at the top of [13542](https://bugs.ruby-lang.org/issues/13542) as the only two patches used for building.  All my other patches are for testing.

Considering that the configure.in patch has been around for quite a while, I assumed (possibly incorrectly) that the issue had already been addressed.

@luislavena is listed as a [maintainer](https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/SupportedPlatforms) for MinGW and he's listed as a [committer/developer](https://bugs.ruby-lang.org/projects/ruby-trunk).

If he has time to look at it, the patches are: [configure.in](https://github.com/MSP-Greg/ruby-loco/blob/master/patches/configure.in.patch) and [defines.h](https://github.com/MSP-Greg/ruby-loco/blob/master/patches/include_ruby_defines.h.patch)...

**Comment by luislavena** [comment]
> @luislavena is listed as a maintainer for MinGW and he's listed as a committer/developer.

I'm no longer actively involved with Ruby to be able to weight in or commit any changes. It will be better reach out to nobu instead.

**Comment by MSP-Greg** [comment]
@luislavena thanks for the reply.  Nobu has helped with several commits affecting parallel builds and more.
