### ISSUE TITLE
Conflicting Ruby and Jekyll PATHs?

### ISSUE THREAD

**Issue by Stoic-Student** [oneclick/rubyinstaller2#359]
## What problems are you experiencing?

I'm trying to install Ruby and Jekyll to create a local environment for testing my website.

When following installation instructions, Jekyll doesn't work.

I've already uninstalled and reinstalled several times and on two machines (both Windows). I get the same issue.

## Steps to reproduce

I follow the instructions from GitHub and Jekyll to install the packages.
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll
https://jekyllrb.com/docs/installation/windows/

Installation of Ruby with RubyInstaller works fine. (run as administrator)
When I install Jekyll according to the instructions and run 'jekyll -v', I get the error that jekyll command doesnt exist.
I edit the PATH settings to the directory given by 'gem env' as EXECUTABLE DIRECTORY, where the actual bin folder for jekyll is located.
After a restart, the error changes to: 
/c/Users/xx/.local/share/gem/ruby/3.2.0/bin/jekyll: line 6: /c/Users/xx/.local/share/gem/ruby/3.2.0/bin/ruby: No such file or directory
It looks to me like Jekyll is looking for Ruby in the wrong place. Ruby is located here, as listed in the PATH settings: C:/Ruby32-x64/bin/

The 'gem env' gives the following output:

RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.10
  - RUBY VERSION: 3.2.2 (2023-03-30 patchlevel 53) [x64-mingw-ucrt]
  - INSTALLATION DIRECTORY: C:/Users/xx/.local/share/gem/ruby/3.2.0
  - USER INSTALLATION DIRECTORY: C:/Users/xx/.local/share/gem/ruby/3.2.0
  - RUBY EXECUTABLE: C:/Ruby32-x64/bin/ruby.exe
  - GIT EXECUTABLE: C:\Program Files\Git\mingw64\bin/git.EXE
  - EXECUTABLE DIRECTORY: C:/Users/xx/.local/share/gem/ruby/3.2.0/bin
  - SPEC CACHE DIRECTORY: C:/Users/xx/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
     - ruby
     - x64-mingw-ucrt
  - GEM PATHS:
     - C:/Users/xx/.local/share/gem/ruby/3.2.0
     - C:/Ruby32-x64/lib/ruby/gems/3.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Users\xx\bin
     - C:\Program Files\Git\mingw64\bin
     - C:\Program Files\Git\usr\local\bin
     - C:\Program Files\Git\usr\bin
     - C:\Program Files\Git\usr\bin
     - C:\Program Files\Git\mingw64\bin
     - C:\Program Files\Git\usr\bin
     - C:\Users\xx\bin
     - C:\Ruby32-x64\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0
     - C:\Windows\System32\OpenSSH
     - C:\Program Files\dotnet
     - C:\Program Files\nodejs
     - C:\Program Files\Git\cmd
     - C:\Program Files\Calibre2
     - C:\Users\xx\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip
     - C:\Users\xx\AppData\Local\Programs\Python\Python311\Scripts
     - C:\Users\xx\.local\share\gem\ruby\3.2.0\bin
     - C:\Ruby32-x64\bin
     - C:\Users\xx\AppData\Local\Programs\Python\Python311\Scripts
     - C:\Users\xx\AppData\Local\Programs\Python\Python311
     - C:\Program Files\MySQL\MySQL Shell 8.0\bin
     - C:\Users\xx\AppData\Local\GitHubDesktop\bin
     - C:\Users\xx\AppData\Local\Programs\Microsoft VS Code\bin
     - C:\Users\xx\AppData\Roaming\npm
     - C:\Program Files\Git\usr\bin\vendor_perl
     - C:\Program Files\Git\usr\bin\core_perl

## What's the output from `ridk version`?

bash: ridk: command not found

**Comment by mohits** [comment]
Hi @Stoic-Student - Could you try using the Windows Command shell instead of bash. I remember reading that some things work better 
from the command line shell. Thanks!

**Comment by Stoic-Student** [comment]
@mohits Thanks for the directions. I've changed the approach entirely and mostly followed this guide to install ruby and jekyll. This seems to work for me: https://gist.github.com/arthurattwell/281a5e1888ffd89b08b4861a2e3c1b35
