### ISSUE TITLE
Upgrading Ruby installation on Windows

### ISSUE THREAD

**Issue by metaad** [oneclick/rubyinstaller2#360]
## What problems are you experiencing?
I am not sure if this is correct forum, Please redirect to the correct one if any.
I am silently upgrading Ruby installation on Windows 10 machine from version 3.1.4-1 to version 3.2.2-1 but they coexists.
Is it intended behaviour or is there any option to upgrade it from old to new version silently?
Also if we have to uninstall old version before installing new version then are there any settings which will be retained and applied to new version?

## Steps to reproduce
Install 3.1.4-1
Install 3.2.2-1

**Comment by mohits** [comment]
The general recommendation is to update patch versions to the same directory and "Ruby" versions (2.6, 2.7, 3.0, 3.1, 3.2, etc.) to separate directories. So, it's normal for 3.1.4 to overwrite 3.1.3 but not have 3.2.1 overwrite 3.1.3, for example.

**Comment by mohits** [comment]
HI @metaad - would you close this issue if there is nothing else we can help with? If we don't hear back by 27th, I will close this!
