### ISSUE TITLE
Fork me on GitHub 403

### ISSUE THREAD

**Issue by akirataguchi115** [oneclick/rubyinstaller2#363]
## What problems are you experiencing?
Fork me on GitHub image is 403.

## Steps to reproduce
Go to https://rubyinstaller.org/ and check the top right corner.

![image](https://github.com/oneclick/rubyinstaller2/assets/31825085/625077b1-3ec8-46ef-bb5c-0692debf3bcc)

**Comment by mohits** [comment]
hi @akirataguchi115 - it seems to be ok, now?

![image](https://github.com/oneclick/rubyinstaller2/assets/56816/0716e64f-dd1c-484c-a2c4-653f5cc4ecc5)

**Comment by akirataguchi115** [comment]
hi @mohits I'll check that at home when I get to my PC but on mobile it's still broken ![image](https://github.com/oneclick/rubyinstaller2/assets/31825085/9d8f9db0-443f-4dbc-8931-a4b4e5b33457)

**Comment by akirataguchi115** [comment]
![image](https://github.com/oneclick/rubyinstaller2/assets/31825085/c5035e93-3b28-4c44-b7eb-d97340a7b233)
nope it's still broken for me on chrome.
```
Failed to load resource: the server responded with a status of 502 () https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67
```
and that address throws 403. Have you tried to force reload?

**Comment by mohits** [comment]
Thanks for clarifying @akirataguchi115. 

So far, I have tried:
* Firefox Focus (private) on Android mobile - it is OK
* Chrome (PC) including force reload - it is OK
* Samsung Internet on Android including force reload - it is OK

I am able to open that image URL on PC and mobile also. I added that link as an image tag to this reply and I wonder if you are able to see the image (I can).

![image](https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67)

This is very strange (and interesting). The URL is 211 characters which also is not a known size limit on iOS 😔

**Comment by akirataguchi115** [comment]
Nope can't see that image. (invalid upstream response 403). My Chrome also says that on Debian and Windows. Could someone else non-contributor try to replicate this?

**Comment by flavorjones** [comment]
I'm getting a 502 response for https://camo.githubusercontent.com/365986a132ccd6a44c23a9169022c0b5c890c387/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f7265645f6161303030302e706e67

I'm on Linux running Chrome 120.0.6099.109

**Comment by mohits** [comment]
Thanks @flavorjones and @akirataguchi115 - I found something that is a bit of progress?. Are you both in the US? 

I found that from Singapore (where I am) or with a VPN to Japan, it works fine. If I VPN to the US, I see the error that you're reporting on the URL of the image. 

Now, it seems to be a GitHub issue?

**Comment by akirataguchi115** [comment]
I'm in Finland, Europe. We should probably start using the ribbon recommended by GitHub since 2008: https://github.blog/2008-12-19-github-ribbons/

**Comment by mohits** [comment]
So, I did look at the code:
https://github.com/oneclick/rubyinstaller.org-website/blob/fb2b2416c384e7fa14815bc1dd281e35d19d3b54/_includes/header.html#L12C1-L12C1

and that has this comment: `GitHub Ribbon taken from: https://github.com/blog/273-github-ribbons` which expands to the link that you shared.

However, the image source is set to a camo.githubusercontent.com URL and it seems that it is that link which is giving problems in some parts of the world.

**Comment by akirataguchi115** [comment]
Any reasoning for using the camo subdomain, @larskanis ?

**Comment by larskanis** [comment]
> Any reasoning for using the camo subdomain, @larskanis ?

I guess it was the recommendation to that time. I just updated it to the code snip that is recommended now.

Does it work now?

**Comment by akirataguchi115** [comment]
Works perfectly. Thank you! <3
