### ISSUE TITLE
I downloaded Ruby Installer but the command prompt keeps giving me this message when I try to check for jekyll "'jekyll-v' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Frank-Adu** [oneclick/rubyinstaller2#364]

**Comment by MSP-Greg** [comment]
jekyll is not part of Ruby.  I'm sure there are instructions on installing jekyll on Windows somewhere...

**Comment by mohits** [comment]
Hi! Could you try following the instructions here - https://jekyllrb.com/docs/installation/windows/ and seeing if something does not work for you? After that, you should be able to Jekyll. I'll close this now but please open it again if you still have problems.
