### ISSUE TITLE
UTF-8 patch in Ruby 2.4

### ISSUE THREAD

**Issue by Iristyle** [oneclick/rubyinstaller2#38]
I'm interested to understand the rationale behind https://github.com/oneclick/rubyinstaller2/blob/master/recipes/compile/ruby-2.4.1/0005-utf-8-default-encoding.patch

Ruby has a long history of using the systems codepage for [Encoding.default_external](https://ruby-doc.org/core-2.3.3/Encoding.html#method-c-default_external) on Windows as the default as it influences (amongst other things):

* File reads / writes
* CSV files
* StringIO

UTF-8, while commonly the default on Linux, is a bit of a peculiar default on Windows for a few reasons:

* Non Unicode file content is likely to be written using the local codepage (i.e. the value returned by `chcp` or the Windows codepage APIs) - a lot of legacy applications still use the active codepage when encoding files on Windows
* Windows default file content is more likely to be UCS-2 (a predecessor to / mostly the same as UTF-16LE) rather than UTF-8, when the content is Unicode
* NOTE: Windows *does have* a UTF-8 codepage (65001) (and its the default for Nano Server for instance), but it has many known issues (particularly with the console) when using Windows APIs / CRT APIs.  I believe MS is working on fixing some of these problems, but not sure how far along they are.  For now, its generally recommended to avoid 65001 - but if you do set the active codepage to 65001 on Windows using `chcp`, Ruby should set `Encoding.default_external` to UTF-8

There are a few problems I see with the change to use UTF-8 as the default for Ruby on Windows:

* This is a pretty major breaking change being introduced in a `.y` release (arguably should be a Ruby 3.y change)
* It's now very difficult within Ruby code to see what the current system codepage is without making Windows API calls yourself (Ruby itself normally uses a combination of [GetConsoleCP](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683162\(v=vs.85\).aspx) / [GetACP](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318070\(v=vs.85\).aspx) to figure things out).  It's much easier to be able to just use `Encoding.default_external`
* Ruby already has the ability to start in a specific codepage by using the `-E` switch - for instance, `ruby -E UTF-8`, without patching the Ruby source
* Making this decision in packaging seems to run counter to the Ruby teams expectations that they've expressed / built into Ruby on Windows

My recommendation would be to revert the UTF-8 patch so that Ruby behaves as originally intended.

**Comment by larskanis** [comment]
> I'm interested to understand the rationale behind utf-8-default-encoding.patch

I'm working in a company which has to exchange text files with a lot of different customers and partners based in western Europe. Ruby runs here with
```ruby
> Encoding.find("locale")   # => #<Encoding:CP850>
> Encoding.find("filesystem")   # => #<Encoding:Windows-1252>
```

I did not do serious statistics about it, but from memory the distribution of encodings used for text files (excluding XML) is roughly:
* 40% Windows-1252
* 5% CP850
* 40% UTF-8
* 5% UTF-16 or UCS-2
* 10% other (often mixed encodings)

So using the console code page (cp850) as `default_external` is almost certainly wrong. It also complicates compatibility with other operating systems. That's what I tried to explain [here](https://bugs.ruby-lang.org/issues/13488).

> There are a few problems I see with the change to use UTF-8 as the default for Ruby on Windows:
>
>* This is a pretty major breaking change being introduced in a .y release (arguably should be a Ruby 3.y change)

I don't agree. Just set `RUBYOPT=-Elocale` to revert to the console code page. This is only a minor change compared to the Integer unification (which required changes to thousands of gems).

>* It's now very difficult within Ruby code to see what the current system codepage is without making Windows API calls yourself (Ruby itself normally uses a combination of GetConsoleCP / GetACP to figure things out). It's much easier to be able to just use Encoding.default_external

Use `Encoding.find("locale")` or `Encoding.find("filesystem")` to retrieve the locale OEM and ANSI encodings. Windows makes use of so many encodings that it's not enough to just use `Encoding.default_external`.

>* Ruby already has the ability to start in a specific codepage by using the -E switch - for instance, ruby -E UTF-8, without patching the Ruby source

This is still the same with RubyInstaller-2.4. It only changes the default to the `default_external`.

>* Making this decision in packaging seems to run counter to the Ruby teams expectations that they've expressed / built into Ruby on Windows

But they expressed to follow later on.


What do you think about a check button in the installer to give the possibility to opt out and use the locale code page?

**Comment by Kjarrigan** [comment]
AS #37  is basically the same @JunichiIto what do you think?

**Comment by larskanis** [comment]
There some more reasons to default to UTF-8 for `Encoding.default_external`:

* All string literals in ruby source code are UTF-8 encoded, by default. This means writing text to a file and read it back changes the encoding and results in a different (invalid) string. It only works correct if UTF-8 is set as `default_external` or if `default_internal` is set, so that the encoding gets converted:
  ```ruby
  a = "\u00E4\u0416\u3042"
  File.write("f", a)
  p File.read("f") == a   # => prints 'false' if default_external is != UTF-8
  ```

* Many gems default to UTF-8 for external strings, regardless of `Encoding.default_external`. Take nokogiri, sqlite3, pg or mysql2 - they all return UTF-8 only. So sent strings and returned strings differ, if you're using non UTF-8 encoding for data. Write it to a file, read it back and you'll get garbage when using locale `Encoding.default_external`.

* Strings returned from `inspect` are not printed as characters but as escape sequences. This is true at least on Windows with western Europe localization. On Japanese Windows it seems to be vice versa. See #37 .

**Comment by MSP-Greg** [comment]
@larskanis Re your first point, I mentioned this in a ruby-lang issue --

The documentation for [Encoding.default_internal](https://msp-greg.github.io/ruby_trunk/Core/Encoding.html#default_internal-class_method) states:

"The locale encoding (\_\_ENCODING\_\_), not default_internal, is used as the encoding of created strings."

Seems to imply that string literals, etc should not necessarily be utf-8.  Then again, the doc may be incorrect...

**Comment by larskanis** [comment]
@MSP-Greg Yes, the doc is a bit misleading. I opened a [pull request](https://github.com/ruby/ruby/pull/1611) to name it better. However it means that strings are encoded according to `__ENCODING__` which is UTF-8 unless defined otherwise per magic comment, as described [here](https://msp-greg.github.io/ruby_trunk/Core/Encoding.html#label-Script+encoding).

**Comment by MSP-Greg** [comment]
@larskanis 

Interesting.  On my system `__ENCODING__` is `IBM437`.  I don't recall any magic comments, and I would never change my encoding to `IBM437`. windows 7 US-English

**Comment by MSP-Greg** [comment]
@larskanis 

Just to make sure (although from a build perspective, your/RI2 builds are the same as my builds), I ran up probably the most recent appveyor artifact  --
```
__ENCODING__ == `chcp`
```

**Comment by larskanis** [comment]
@MSP-Greg Don't get fooled by irb - it changes a lot about encodings. Try running a .rb file.

**Comment by MSP-Greg** [comment]
@larskanis 

```ruby
# encoding.rb
txt = 'ABCDEF_äÖü'
puts  "ENV['RUBYOPT'] #{ENV['RUBYOPT']}" \
    "\nfilesystem     #{Encoding.find('filesystem')}" \
    "\nexternal       #{Encoding.default_external}" \
    "\n`chcp`         #{`chcp`}" \
      "locale         #{Encoding.find('locale')}" \
    "\n__ENCODING__   #{__ENCODING__}" \
    "\ninternal       #{Encoding.default_internal}" \
    "\ntxt            #{txt.encoding.to_s}" \
    "\n'ABCDEF_äÖü'   #{'ABCDEF_äÖü'.encoding.to_s}"
```

Output

```
E:\r_misc>ruby encoding.rb

ENV['RUBYOPT'] -EWindows-1252
filesystem     Windows-1252
external       Windows-1252
`chcp`         Active code page: 437
locale         IBM437
__ENCODING__   UTF-8
internal
txt            UTF-8
'ABCDEF_äÖü'   UTF-8

E:\r_misc>
```

So --
```
Encoding.find('locale') == `chcp`
__ENCODING__ == UTF-8
```

**Comment by MSP-Greg** [comment]
@larskanis 

You're probably aware of it, but I just saw [Encodings - Script Encoding](https://msp-greg.github.io/ruby_trunk/Core/Encoding.html#label-Script+encoding)

which states --

"The `__ENCODING__` keyword returns the script encoding of the file which the keyword is written:"

I've never tried a script/*.rb file that wasn't UTF-8...

BTW, I added [Nokogiri docs](https://msp-greg.github.io/nokogiri/index.html) to my site. If you have a need to review docs, please let me know if I've got any c code parsed incorrectly.  First extension gem that I needed to doc...

**Comment by Iristyle** [comment]
> I did not do serious statistics about it, but from memory the distribution of encodings used for text files (excluding XML) is roughly:
>
> 40% Windows-1252
> 5% CP850
> 40% UTF-8
> 5% UTF-16 or UCS-2
> 10% other (often mixed encodings)

I don't think that your statistics really make a clear case for using UTF-8 encoding by default.  On US Windows the codepage is often IBM437 and text files will generally either be in that encoding OR in UCS-2 as I mentioned.  In other countries it can be totally different.

What these statistics do demonstrate is that interoperability does not necessarily have a sensible default - that is, it's application dependent, so a default isn't always helpful, except for for naive Ruby-only cases.

Fundamentally, to interoperate with files produced by other applications requires some knowledge of that application.  I work on Puppet and we handle this (cross-platform) by explicitly specifying encodings any time we're touching stream (file) content.  In some cases that encoding is `Encoding.default_external` because the file may be managed by the operating system and we want to use the appropriate codepage, but sometimes it may be other encodings (for instance, Puppet manifest files are always UTF-8).

I do agree with you that a UTF-(8|16LE) encoding is an ideal situation, but I don't believe Ruby is ready for this just yet.  Note that UTF-8 is better for European countries, but UTF-16 can be better for Asian countries giving its 2-byte representation of characters is often better than the 3-byte representation of characters in UTF-8, decreasing file size by 50%.  In a perfect world, being able to rely on everything being UTF-8 would make our lives easier - but unfortunately, we're not in a perfect world.

My problem is that changing the default is an outright breaking change at this point in time. Consider the situation where an old version of your Ruby application built on 2.3 has written files to disk and a new 2.4 application must read them.  If they were written in a multibyte encoding (like CP932), an attempt to read them as the new default UTF-8 (without explicitly specifying encoding) will corrupt their contents, without introducing new code changes to handle that.

> I don't agree. Just set RUBYOPT=-Elocale to revert to the console code page. This is only a minor change compared to the Integer unification (which required changes to thousands of gems).

Thanks for the info on `-Elocale`- I've missed that.  However, it's still a significant breaking change.

The scope of the Integer change is not relevant here (Puppet also had to make changes as a result of this change).  Making a bad decision once does not justify future behavior.

> What do you think about a check button in the installer to give the possibility to opt out and use the locale code page?

Given the ability to switch to UTF-8 with `-E UTF-8` for interested parties, I believe the burden should be put on users who desire a new UTF-8 behavior to opt-in to that default (this is a pretty common feature flag style approach), rather than putting a burden on existing users to address a breaking change.

I don't believe deviating from core Ruby in a Windows package, for what amounts to a personal preference, is the right move to make.


Thanks for hearing out the objectors to this change!

**Comment by McdonaldSeanp** [comment]
> Given the ability to switch to UTF-8 with -E UTF-8 for interested parties, I believe the burden should be put on users who desire a new UTF-8 behavior to opt-in to that default (this is a pretty common feature flag style approach), rather than putting a burden on existing users to address a breaking change.

I agree with @Iristyle here on the idea that this is a breaking change and that the new behavior should be opt-in, not opt-out.

I do like the idea of using a check button in the installer for the opt-in to this behavior.

**Comment by Iristyle** [comment]
I'd also like to add that Puppet ships a custom built Ruby (that would not add this patch) in the Puppet Agent MSI for Windows, but this issue is still important to us for a few reasons:

* Puppet runs pull requests against AppVeyor, and AppVeyor relies on the RubyInstaller MSI
* Local Windows based development on Puppet (whether in-house or 3rd party module development) currently relies on RubyInstaller packages (often by way of Chocolatey) - it's preferable to have a Ruby install that doesn't deviate drastically from what's embedded in the Puppet Agent MSI

**Comment by kubo** [comment]
> I don't think that your statistics really make a clear case for using UTF-8 encoding by default. On US Windows the codepage is often IBM437 and text files will generally either be in that encoding OR in UCS-2 as I mentioned. In other countries it can be totally different.

In Japan, almost all text files (excluding html and xml) for Windows users are in CP932. Almost all text files created before a decade for unix users are in [EUC-JP](https://en.wikipedia.org/wiki/Extended_Unix_Code#EUC-JP). Recent text files for unix users are in UTF-8. As a result CP932 is in the majority on Japanese Windows.

> Given the ability to switch to UTF-8 with -E UTF-8 for interested parties, I believe the burden should be put on users who desire a new UTF-8 behavior to opt-in to that default (this is a pretty common feature flag style approach), rather than putting a burden on existing users to address a breaking change.

I agree with this.

**Comment by umesh-acquia** [comment]
exporting global variables like this
LANGUAGE = "en_US.UTF-8",
LC_ALL ="en_US.UTF-8",
LC_CTYPE = "en_US.UTF-8",
LANG = "en_US.UTF-8"
would resolve.

**Comment by larskanis** [comment]
RubyInstaller sets the default encoding to UTF-8 as an opt-in since 3 years and as an opt-out since [almost one year](https://rubyinstaller.org/2020/01/05/rubyinstaller-2.7.0-1-released.html). So most systems using RubyInstaller are using UTF-8 as the default external encoding already. I opened https://bugs.ruby-lang.org/issues/16604 to finally make the switch in ruby-core. This will remove the crutch to set it per `RUBYOPT=-Eutf-8`.
