### ISSUE TITLE
Questions about automatic "system gemrc" file creation

### ISSUE THREAD

**Issue by deivid-rodriguez** [oneclick/rubyinstaller2#388]
## What problems are you experiencing?

No problems, but I was investigating an issue about the `etc` gem being activated too soon on Windows, and eventually run into some code in the `operating_system.rb` file shipped by RubyInstaller2 that automatically creates an empty "system gemrc" file if it does not exist already: 

https://github.com/oneclick/rubyinstaller2/blob/3f896e7e05d196b3a9c4a57fa46ecb38938660b8/resources/files/operating_system.rb#L56-L74

I got curious about the potential security issue. Does it affect more platforms other than Windows? The way I see it, system configuration is precisely intended for sharing a configuration with all users, so it's intended that a user with permissions to write files in `Gem::ConfigFile::SYSTEM_WIDE_CONFIG_FILE` can setup RubyGems configurations for all users. Also, it seems that the current implementation will still respect this global file if it's already there.

So I'm not fully clear about the security issue and I'm looking for a bit more insights.

## Steps to reproduce

Create an empty Gemfile and observe that `ruby -rbundler/setup -e 'puts Gem.loaded_specs["etc"]'` activates the `etc` gem on Windows.

**Comment by larskanis** [comment]
`Gem::ConfigFile::SYSTEM_WIDE_CONFIG_FILE` refers to `C:/ProgramData` on Windows. Everyone can create a new file in this directory, but the file can not be changed by anyone other than the owner subsequently. But everyone can read the file.

This is a security risk, since Rubygems reads this `gemrc` file, if it is present. When an attacker creates this file, it can hijack the configuration of some other user. It could inject different sources urls for instance.

I had a discussion with @hsbt and @unak about this topic on hackerone in 2022. They concluded about not to change anything in Rubygems. So I went further and implemented [this simple solution](https://github.com/oneclick/rubyinstaller2/commit/f558a3834f8f6f63becfe02981924cde9e59b4a2), that the very first call of `gem` creates this `gemrc` file and closes the attack vector.

The issue doesn't affect platforms other than Windows.

**Comment by larskanis** [comment]
We had an issue with fiddle in the past, that looks like this issue with etc loaded too soon: https://github.com/oneclick/rubyinstaller2/issues/251 . The way I solved it was to build a RubyInstaller specific Ruby C extension, which can call the Win32 API functions without fiddle.

Now that etc is gemified, we have the same issue here. The etc gem loading is triggered by accessing the constant `Gem::ConfigFile::SYSTEM_WIDE_CONFIG_FILE`. The etc gem reads the  path [here](https://github.com/ruby/etc/blob/11677318ac3b88128a056a434c3a9bf4f574a575/ext/etc/etc.c#L712). But it is usually alternatively available in the environment variable `ProgramData`. So I think about switching to `ENV['ProgramData']` in [operating_system.rb](https://github.com/oneclick/rubyinstaller2/blob/3f896e7e05d196b3a9c4a57fa46ecb38938660b8/resources/files/operating_system.rb#L57).

**Comment by daipom** [comment]
@larskanis 
I understand that it prevents malicious users from creating or editing this file.

I have one question.
How should we edit this config?

> Feel free to add any rubygems config options as described on: 

This config file is YAML.
However, looks like the default content is not YAML.
So, I can't append a new setting to this file by simply using `echo gem: --no-document >> c:\ProgramData\gemrc`.

```
---
{}
gem: --no-document
```

This doesn't work.

Why is there the default content `---\n{}`?

Do we need to overwrite this file completely?

`echo gem: --no-document > c:\ProgramData\gemrc`

I am not familiar with Windows permissions, but is this safe?

**Comment by daipom** [comment]
Sorry, this is YAML.

```
---
{}
```

But I can't add key-value to this content because `{}` closes the hash.
Do we need `{}`?

> Feel free to add any rubygems config options

It prevents us from adding a config. We need to overwrite this file to do it.

**Comment by mohits** [comment]
hi @daipom  and @deivid-rodriguez - what's the next step here? Is this OK or are you still looking for some other change? Accordingly, I will leave this open or recommend to close it.

Thanks!

**Comment by deivid-rodriguez** [comment]
I had some questions about this in https://github.com/oneclick/rubyinstaller2/issues/388#issuecomment-2233589018, which I'd still be interested in, but I'm fine to close this since as of now, there's no specific action to be taken in RubyInstaller2. This issue was mainly a question to try understand things better.

**Comment by mohits** [comment]
Closing this for now. Thanks!

**Comment by daipom** [comment]
Thanks! Sorry for my late response.

My question was resolved, so I'm OK with closing this.

If there could be other users who are as troubled as I am, it might be a good idea to improve this comment.
(Clarify how the option should be added. Overwriting the file or replacing lines? At least, appending is not possible.)

https://github.com/oneclick/rubyinstaller2/blob/3f896e7e05d196b3a9c4a57fa46ecb38938660b8/resources/files/operating_system.rb#L56-L74
