### ISSUE TITLE
[request] - ruby 3.3.5 package

### ISSUE THREAD

**Issue by YOU54F** [oneclick/rubyinstaller2#389]
👋🏾 

Ruby 3.3.5 was released yesterday (3rd Sept 2024) - https://www.ruby-lang.org/en/news/2024/09/03/3-3-5-released/

Just politely requesting a release when possible 🙏🏾 

Rationale: I maintain a fork of [traveling-ruby](https://github.com/YOU54F/traveling-ruby) and would like to release packages for linux/macos/windows for 3.3.5.

**Comment by larskanis** [comment]
RubyInstaller-3.3.5-1 is released. The summertime is better suited to go to the beach than sitting in front of the computer, so that there can be a delay sometimes...

**Comment by YOU54F** [comment]
cheers dude and 😅 wasn't in a rush, just raised a ticket to help me track without having to keep another thing in my head. 

appreciate the speed is resolving, means i can box off the update and get on with other more interesting things 🙏
