### ISSUE TITLE
Can't install MSYS2 and MINGW

### ISSUE THREAD

**Issue by ArztVielfrass** [oneclick/rubyinstaller2#391]
![image](https://github.com/user-attachments/assets/213ea16f-01b4-493d-bb4a-5848c91efb10)

This is after installing ruby with [this](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.3.5-1/rubyinstaller-devkit-3.3.5-1-x64.exe)

**Comment by larskanis** [comment]
`forked process died` means that there's some serious issue executing MSYS2 binaries, probably caused by a virus scanner or some security software. Could that be true? Can you disable it?

**Comment by ArztVielfrass** [comment]
Installs fine using Windows Sandbox, maybe because it doesn't use Defender... Only using Windows Defender as the anti-virus, I kinda don't want to test to confirm if it's because of SmartScreen or SmartApp Control. But it's the fix to my issue. Thanks for the help
