### ISSUE TITLE
Ruby 2.4 Stable Releases

### ISSUE THREAD

**Issue by luke-hill** [oneclick/rubyinstaller2#40]
We are currently upgrading to Ruby 2.3 at the moment, and we plan on then staying at 2.3 not for long before going to 2.4

At the moment, every release candidate is a pre-release candidate, and I have not found any stable exe's online.

At what point do you plan on Releasing Ruby 2.4.0 for Windows as a stable RC, or 2.4.1?

If you have already done so, you should mark these releases using the same version so I can point non-tech people where to go to get installers.

**Comment by larskanis** [comment]
Sorry for the delays regarding the RubyInstaller-2.4.1 release! Now that
the new website for https://rubyinstaller.org is up and running and there
haven't been any issues since rc3, I'll push the final release today or
tomorrow. Stay tuned!

**Comment by luke-hill** [comment]
Is there a stable 2.4.0? If so can you advise which link it is? - We're not pushing for a 2.4.1 to be available as I'm aware this was only released as a ruby version recently

**Comment by larskanis** [comment]
There's no RubyInstaller-2.4.0.

**Comment by larskanis** [comment]
RubyInstaller-2.4.1-1 is finally released!
