### ISSUE TITLE
Ruby 2.4.1-1 is not fully silent - MSYS2 window opens (non-blocking)

### ISSUE THREAD

**Issue by ferventcoder** [oneclick/rubyinstaller2#43]
## What problems are you experiencing?
Greetings! Just ran across this issue today. It's a minor annoyance as it doesn't block the installation from finishing, however there is a window that pops open for MSYS2, even when you install Ruby with `/VERYSILENT`. This was not seen in earlier versions of Ruby using the legacy (?) RubyInstaller. 

![image](https://cloud.githubusercontent.com/assets/63502/26527831/49d9f242-4362-11e7-923f-a64a5309fd5a.png)

I reviewed the wiki to see if any new switches have been added but found none.
https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-silent-install

## Steps to reproduce
1. Try installing ruby installer 2.4.1-1 silently. 
    `/verysilent /dir="c:\ruby24" /tasks="assocfiles,modpath"`
1. Note at the end that it opens a window. 

A fully silent install should not have any windows come up. With `/SILENT` it is probably okay, but with `/VERYSILENT` the common expectation is that nothing should show up.

**Comment by ferventcoder** [comment]
If there is something that can be passed to keep this from stopping at this point, that would be great. Otherwise, I think if `/VERYSILENT` is selected, one of these options should automatically be selected and acted upon without any Windows coming up.

Perhaps allow changing these options with a silent switch.

**Comment by ferventcoder** [comment]
One important detail - the windows does show up, but it does not block the installation from finishing. If this is not a necessary step for finishing the Ruby install, perhaps have it come up on first use when a silent option of installation is selected.

**Comment by larskanis** [comment]
Please try using `noridkinstall` as described in the faq.

**Comment by ferventcoder** [comment]
I will give that a shot (lilely Monday). Provided that works, can the inno script be enhanced to set that automatically for silent installs? Any window opening breaks the contract of `VERYSILENT`.

**Comment by larskanis** [comment]
@ferventcoder You're right - it's better to set the default based on the silent flag: https://github.com/oneclick/rubyinstaller2/commit/9fc8fb06717321f380094a41ddf5216e327bdc37

**Comment by ferventcoder** [comment]
Much appreciated!

**Comment by larskanis** [comment]
@ferventcoder Thank you for providing RubyInstaller per chocolatey! It should already work with chocolatey's MSYS2 installation, but if not, don't hesitate to contact me.

**Comment by ferventcoder** [comment]
It's the core community maintainers team that ensures the availability of Ruby nowadays. I'm part of that team but the kudos go to @admiringworm and @majkinetor for the day to day work there.
