### ISSUE TITLE
readline support

### ISSUE THREAD

**Issue by dsisnero** [oneclick/rubyinstaller2#48]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

"readline is one of the external dependencies that the ruby stdlib depends on. The RubyInstaller distribution uses a pure-ruby implementation of readline in lieu of GNU-readline"

I feel we need readline installed as part of the download.  Should we be using the pure ruby readline or should we use libreadline with the new rubinstaller2

**Comment by larskanis** [comment]
The C-based readline library compiles, but doesn't work properly on Windows. This is why RubyInstaller2 already ships https://github.com/ConnorAtherton/rb-readline (the pure ruby readline implementation), equally to RubyInstaller1.

What is your issue with it?

**Comment by larskanis** [comment]
Closed due to no response.
