### ISSUE TITLE
file for Paperclip

### ISSUE THREAD

**Issue by richpeck** [oneclick/rubyinstaller2#49]
[Paperclip requires `file`](https://github.com/thoughtbot/paperclip#file) to content-type checks.

With `RubyInstaller 1.x`, we used to get this with `devkit`, which was included in the `PATH`:
![adsfadsf](https://user-images.githubusercontent.com/1104431/27023419-63a4c014-4f4a-11e7-9a82-7c6ff428d44c.png)

But as `RubyInstaller 2.x` doesn't give `file` in `cmd` shell (it exists in `msys64`), what is the recommended way to get it working? Since it's required at runtime, Windows needs direct access to the binaries.

I have got it working by copying `file` to a folder & adding to PATH, but defeats purpose of `msys2`.

**Comment by richpeck** [comment]
I also got it working by using `ridk exec` in front of `rails s` -- `ridk exec rails s -b lvh.me -p 4200` but obviously this adds complexity.

**Comment by larskanis** [comment]
You can either include `c:/msys64/usr/bin/` into your `PATH` or place `require "devkit"` in you application. The latter calls [this file](https://github.com/oneclick/rubyinstaller2/blob/master/lib/devkit.rb) which sets several environment variables including `PATH`.

**Comment by larskanis** [comment]
Yes `ridk exec` is another option. It runs `RubyInstaller::Runtime.enable_msys_apps` as well, with the same result.

**Comment by larskanis** [comment]
You can also run `ridk enable` once in cmd or powershell, to set the variables before running `rails s`.

**Comment by richpeck** [comment]
Thanks, let me test these out.
