### ISSUE TITLE
installing mingw-w64-x86_64-gcc (6.3.0-3) breaks dependency 'mingw-w64-x86_64-gcc=6.2.0-2'

### ISSUE THREAD

**Issue by sschuberth** [oneclick/rubyinstaller2#50]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

When pressing *ENTER* on the

```
   1 - MSYS2 base installation
   2 - MSYS2 repository update
   3 - MSYS2 and MINGW development toolchain
Which components shall be installed? [1,2,3]
```
prompt to use the default to install all components, I get

    installing mingw-w64-x86_64-gcc (6.3.0-3) breaks dependency 'mingw-w64-x86_64-gcc=6.2.0-2'
    ...
    Install MSYS2 and MINGW development toolchain failed
    Installation failed: pacman failed

## Steps to reproduce

Run `rubyinstaller-2.4.1-1-x64.exe` and accept all defaults.

## What's the output from `ridk version`?

I don't get that far.

**Comment by larskanis** [comment]
You need to upgrade MSYS2. `ridk install` doesn't do this so far, so you currently have to do this manually:
```
ridk enable
pacman -Syu
pacman -Su
```

**Comment by sschuberth** [comment]
But when, at what stage? When running the installer I don't even get a prompt to enter these commands.

**Comment by larskanis** [comment]
Use `cmd` or `powershell` after installing RubyInstaller-2.4.1-1. The `ridk install` step is optional and can be repeated anytime later.

**Comment by sschuberth** [comment]
So for idiots like me the full instructions are:

- Run `rubyinstaller-2.4.1-1-x64.exe` accepting all defaults, except in the end opt-out of running `ridk install`.
- From the Start Menu, choose "Start Command Prompt with Ruby".
- Run these commands in order:
    - `ridk enable`
    - `pacman -Syu` (accepting all defaults)
    - Close the terminal window as instructed
    - "Start Command Prompt with Ruby" (again)
    - `ridk enable` (again)
    - `pacman -Su`

**Comment by larskanis** [comment]
@sschuberth Looks like your issue is solved. RubyInstaller-2.4.1-2 is changed to do the described system update as part of `ridk install`. This should solve the issue for other people as well.
