### ISSUE TITLE
Run gem update and receive errors

### ISSUE THREAD

**Issue by duytrung** [oneclick/rubyinstaller2#54]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
So many error screen

## Steps to reproduce
C:\Ruby\dev>gem update
Updating installed gems
Updating bigdecimal
Fetching: bigdecimal-1.3.2.gem (100%)
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing bigdecimal:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.2/ext/bigdecimal
C:/Ruby/bin/ruby.exe -r ./siteconf20170706-10832-1eiibdu.rb extconf.rb
checking for labs() in stdlib.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
C:/Ruby/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:542:in `try_link0'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:557:in `try_link'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:768:in `try_func'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:1055:in `block in have_func'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:1054:in `have_func'
        from extconf.rb:6:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/bigdecimal-1.3.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby/lib/ruby/gems/2.4.0/gems/bigdecimal-1.3.2 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/bigdecimal-1.3.2/gem_make.out
Updating did_you_mean
Fetching: did_you_mean-1.1.2.gem (100%)
Successfully installed did_you_mean-1.1.2
Parsing documentation for did_you_mean-1.1.2
Installing ri documentation for did_you_mean-1.1.2
Installing darkfish documentation for did_you_mean-1.1.2
Done installing documentation for did_you_mean after 0 seconds
Parsing documentation for did_you_mean-1.1.2
Done installing documentation for did_you_mean after 0 seconds
Updating json
Fetching: json-2.1.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
C:/Ruby/bin/ruby.exe -r ./siteconf20170706-10832-16c4tcz.rb extconf.rb
creating Makefile

current directory: C:/Ruby/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/Ruby/lib/ruby/gems/2.4.0/gems/json-2.1.0/ext/json/ext/generator
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby/lib/ruby/gems/2.4.0/gems/json-2.1.0 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-2.1.0/gem_make.out
Updating minitest
Fetching: minitest-5.10.2.gem (100%)
Successfully installed minitest-5.10.2
Parsing documentation for minitest-5.10.2
Installing ri documentation for minitest-5.10.2
Installing darkfish documentation for minitest-5.10.2
Done installing documentation for minitest after 2 seconds
Parsing documentation for minitest-5.10.2
Done installing documentation for minitest after 0 seconds
Updating openssl
Fetching: openssl-2.0.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing openssl:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby/lib/ruby/gems/2.4.0/gems/openssl-2.0.4/ext/openssl
C:/Ruby/bin/ruby.exe -r ./siteconf20170706-10832-6jjv43.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
        --with-openssl-dir
        --without-openssl-dir
        --with-openssl-include
        --without-openssl-include=${openssl-dir}/include
        --with-openssl-lib
        --without-openssl-lib=${openssl-dir}/lib
        --with-kerberos-dir
        --without-kerberos-dir
        --with-kerberos-include
        --without-kerberos-include=${kerberos-dir}/include
        --with-kerberos-lib
        --without-kerberos-lib=${kerberos-dir}/lib
C:/Ruby/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:572:in `block in try_compile'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:525:in `with_werror'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:572:in `try_compile'
        from C:/Ruby/lib/ruby/gems/2.4.0/gems/openssl-2.0.4/ext/openssl/deprecation.rb:5:in `deprecated_warning_flag'
        from extconf.rb:23:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/openssl-2.0.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby/lib/ruby/gems/2.4.0/gems/openssl-2.0.4 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/openssl-2.0.4/gem_make.out
Updating power_assert
Fetching: power_assert-1.0.2.gem (100%)
Successfully installed power_assert-1.0.2
Parsing documentation for power_assert-1.0.2
Installing ri documentation for power_assert-1.0.2
Installing darkfish documentation for power_assert-1.0.2
Done installing documentation for power_assert after 0 seconds
Parsing documentation for power_assert-1.0.2
Done installing documentation for power_assert after 0 seconds
Updating psych
Fetching: psych-2.2.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing psych:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4/ext/psych
C:/Ruby/bin/ruby.exe -r ./siteconf20170706-10832-1sdr9j7.rb extconf.rb
checking for yaml.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby/bin/$(RUBY_BASE_NAME)
        --with-libyaml-dir
        --without-libyaml-dir
        --with-libyaml-include
        --without-libyaml-include=${libyaml-dir}/include
        --with-libyaml-lib
        --without-libyaml-lib=${libyaml-dir}/lib
        --enable-bundled-libyaml
        --disable-bundled-libyaml
C:/Ruby/lib/ruby/2.4.0/mkmf.rb:457:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:588:in `try_cpp'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:1148:in `block in find_header'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:945:in `block in checking_for'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:321:in `open'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:347:in `postpone'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:944:in `checking_for'
        from C:/Ruby/lib/ruby/2.4.0/mkmf.rb:1147:in `find_header'
        from extconf.rb:10:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/psych-2.2.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby/lib/ruby/gems/2.4.0/gems/psych-2.2.4 for inspection.
Results logged to C:/Ruby/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/psych-2.2.4/gem_make.out
Updating rdoc
Fetching: rdoc-5.1.0.gem (100%)
rdoc's executable "rdoc" conflicts with C:/Ruby/bin/rdoc
Overwrite the executable? [yN]  y
rdoc's executable "ri" conflicts with C:/Ruby/bin/ri
Overwrite the executable? [yN]  y
Successfully installed rdoc-5.1.0
Parsing documentation for rdoc-5.1.0
Installing ri documentation for rdoc-5.1.0
Installing darkfish documentation for rdoc-5.1.0
Done installing documentation for rdoc after 16 seconds
Parsing documentation for rdoc-5.1.0
Done installing documentation for rdoc after 8 seconds
Updating test-unit
Fetching: test-unit-3.2.5.gem (100%)
Successfully installed test-unit-3.2.5
Parsing documentation for test-unit-3.2.5
Installing ri documentation for test-unit-3.2.5
Installing darkfish documentation for test-unit-3.2.5
Done installing documentation for test-unit after 4 seconds
Parsing documentation for test-unit-3.2.5
Done installing documentation for test-unit after 2 seconds
Updating xmlrpc
Fetching: xmlrpc-0.3.0.gem (100%)
Successfully installed xmlrpc-0.3.0
Parsing documentation for xmlrpc-0.3.0
Installing ri documentation for xmlrpc-0.3.0
Installing darkfish documentation for xmlrpc-0.3.0
Done installing documentation for xmlrpc after 1 seconds
Parsing documentation for xmlrpc-0.3.0
Done installing documentation for xmlrpc after 0 seconds
Gems updated: bigdecimal did_you_mean json minitest openssl power_assert psych rdoc test-unit xmlrpc

C:\Ruby\dev>

## What's the output from `ridk version`?
C:\Ruby\dev>ridk version
---
ruby:
  path: C:/Ruby
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
msys2:
  path: C:\MyPrograms\MSYS2
  title: MSYS2 32bit
  version: '20161025'
sh: GNU bash, version 4.4.12(1)-release (i686-pc-msys)

**Comment by gluons** [comment]
Same issue.

**Log:** [mkmf.log](https://github.com/oneclick/rubyinstaller2/files/1171758/mkmf.log.txt)

`ridk version`:
```
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.1.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
```

**Comment by MSP-Greg** [comment]
@gluons 

What output do you get from
```
E:\>ridk exec pacman -Qs openssl
```

**Comment by gluons** [comment]
@MSP-Greg 

```
> ridk exec pacman -Qs openssl
local/libopenssl 1.0.2.k-1 (libraries)
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
local/openssl 1.0.2.k-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
```

**Comment by MSP-Greg** [comment]
@glouns

Interesting.  You don't have the OpenSSL package.  try
```
ridk exec pacman -S mingw-w64-x86_64-openssl
```
Then try
```
gem update openssl -- --use-system-libraries
```

**Comment by gluons** [comment]
@MSP-Greg Thank you very much. It work!

**Comment by MSP-Greg** [comment]
@gluons

You're welcome, glad I could help.  You should have a file `.gemrc` in the root of your user account folder.  I might suggest that it should have the following in it:
```
--- 
:verbose: true
install: --no-document --env-shebang --platform ruby -- --use-system-libraries
update:  --no-document --env-shebang --platform ruby -- --use-system-libraries

```

It might need a blank like at the end, not sure.  remove the `--no-document` if you want docs generated.

**Comment by MSP-Greg** [comment]
@duytrung

Don't know if you still have issues.  If when running the following, you see several items, you do have gcc installed.  If so, try the above addition to your `.gemrc` file.

```
ridk exec pacman -Qs gcc
```

**Comment by MSP-Greg** [comment]
@duytrung 

Also (kind of skipping around right now), I just noticed 
```
platform: x64-mingw32
title: MSYS2 32bit
sh: GNU bash, version 4.4.12(1)-release (i686-pc-msys)
```

I think you've got a 64 bit version of Ruby (`x64-mingw32`), but your MSYS is 32 bit.  I have never tried that before...

**Comment by larskanis** [comment]
Looks like this issue is solved. Thank you @MSP-Greg for help and tracking it down!
