### ISSUE TITLE
MSYS2 installation failure: 'MSYS2 seems to be unavailable'

### ISSUE THREAD

**Issue by ahirschberg** [oneclick/rubyinstaller2#56]
## What problems are you experiencing?
I'm running into an issue with the MSYS2 installer, running on a Windows .NET Core (v4.6) box, where the installation will not begin/complete

## Steps to reproduce
Download the latest ruby 2.4 via chocolatey
Execute C:\tools\ruby24\ridk.cmd or ridk.ps1
Press 1 to perform base MSYS2 installation
Observe output `MSYS2 seems to be unavailable` and `Installation failed: MSYS2 installer failed`

## Output from `ridk version` and `ridk install`:
```
C:\tools\ruby24>C:\tools\ruby24\bin\ridk.cmd version
---
ruby:
  path: C:/tools/ruby24
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
```

Output of `ridk install`:
```
C:\tools\ruby24>C:\tools\ruby24\bin\ridk.cmd install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,2,3] 1

MSYS2 seems to be unavailable
Verify integrity of msys2-x86_64-20161025.exe ... OK
Run the MSYS2 installer ...
> C:\Users\ADMINI~1\AppData\Local\Temp\2/msys2-x86_64-20161025.exe
 Failed
Installation failed: MSYS2 installer failed
```

The install is failing, so I can't resolve gem dependencies relying on them. For example, libyajl2:
```
C:\tools\ruby24\alex>..\bin\gem install libyajl2
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
```

**Comment by larskanis** [comment]
You can download the MSYS2 tar file from http://repo.msys2.org/distrib/x86_64/ , extract it on c:/msys64/ and run `ridk install` afterwards.

Alternatively you could use the unofficial "rubybundle" installer, which installs MSYS2 inside the ruby directory: https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor/build/job/qmnwg9008xf53m8i/artifacts

I'll think about using the tar file for `ridk install` in the future.

**Comment by larskanis** [comment]
Any success with using RubyInstaller on Windows .NET core?

**Comment by optimax** [comment]
msys2.org seems to be down/unavailable.

**Comment by larskanis** [comment]
There is proper support for installation of ruby and MSYS2 in chocolatey now: https://chocolatey.org/packages/msys2

**Comment by yuliu** [comment]
I'm on Windows 7 x64.
It seems that MSYS2 has to be install C:\msys64. If installed elsewhere, MSYS2 cannot be detected by ``ridk install''.

If this is true, I suggest adding a description regarding MSYS2 installation directory somewhere.

**Comment by mpcjanssen** [comment]
You can update the default path in `/ruby_installer/runtime/msys2_installation.rb`. I had the same issue with `ridk install` not detecting a scoop installed msys2.

**Comment by ru5lan** [comment]
фыв
