### ISSUE TITLE
error: target not found: mingw-w64-x86_64-winstorecompat-git

### ISSUE THREAD

**Issue by agross** [oneclick/rubyinstaller2#57]
## What problems are you experiencing?

I cannot install the MINGW development toolchain using `ridk`. (I assume I need both MSYS2 and MINGW?)

## Steps to reproduce

1. Clean Ruby install
1. Run Ruby installer 
1. Run ridk at the end, select option 3 (MSYS2 and MINGW development toolchain)
1. Wait for MSYS2 to finish

```
Which components shall be installed? If unsure press ENTER [1,2,3] 3

MSYS2 seems to be unavailable
Download http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe
  to C:\Users\agross\AppData\Local\Temp/msys2-x86_64-20161025.exe
Downloading msys2-x86_64-20161025.exe (100%)
Verify integrity of msys2-x86_64-20161025.exe ... OK
Run the MSYS2 installer ...
> C:\Users\agross\AppData\Local\Temp/msys2-x86_64-20161025.exe
 Success
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autoconf2.13 autogen automake-wrapper automake1.10 automake1.11 automake1.12 automake1.13 automake1.14 automake1.15 automake1.6 automake1.7 automake1.8 automake1.9 diffutils file gawk grep libtool m4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git mingw-w64-x86_64-winstorecompat-git
warning: file-5.28-2 is up to date -- skipping
warning: gawk-4.1.4-1 is up to date -- skipping
warning: grep-2.26-1 is up to date -- skipping
warning: m4-1.4.17-4 is up to date -- skipping
warning: sed-4.2.2-2 is up to date -- skipping
warning: wget-1.18-1 is up to date -- skipping
error: target not found: mingw-w64-x86_64-winstorecompat-git
Install MSYS2 and MINGW development toolchain failed
Installation failed: pacman failed
```

However, I was able complete the installation by running `pacman` with the package list above minus `mingw-w64-x86_64-winstorecompat-git`.

## What's the output from `ridk version`?

```sh
$ ridk version
---
ruby:
  path: C:/Ruby
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
msys2:
  path: C:\Ruby\sdk
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.2.0
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
```

**Comment by larskanis** [comment]
Hi Alex! All three options must be taken to make sure everything is up-to-date. It is enough to press ENTER without typing any numbers.

Background: MSYS2 is a rolling release distribution. It is common to ship ABI breaking changes whenever packages are updated. It is therefore required to keep all packages on a consistent state by updating the whole MSYS2/MINGW system. So whenever package installation fail, try `ridk install` again.

**Comment by agross** [comment]
Hi Lars, long time no see! :-)

Sems like I didn't read the "if unsure press ENTER" part. I now reran the installer without selecting any option and the install was successful. Many thanks, seems I need new glasses ;-)

**Comment by Wurstnase** [comment]
Maybe the hint is not big enough. I didn't see this also :)

**Comment by phoenixfangor** [comment]
I agree with agross and Wurstnase. It's not obvious that all three need to be installed and that you should probably just hit "ENTER".

**Comment by krystan** [comment]
Well done updated the environment and this fixed the issue for me
