### ISSUE TITLE
Error when installing json gem

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [oneclick/rubyinstaller2#62]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
Running `gem install json -v 1.8.3` throws error:

    C:\Users\Daniq>gem install json -v '1.8.3'
    Temporarily enhancing PATH for MSYS/MINGW...
    Building native extensions.  This could take a while...
    ERROR:  Error installing json:
            ERROR: Failed to build gem native extension.

    current directory: D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
    D:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170803-8620-1dnxxx8.rb extconf.rb
    creating Makefile

    current directory: D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
    make "DESTDIR=" clean

    current directory: D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.8.3/ext/json/ext/generator
    make "DESTDIR="
    generating generator-x64-mingw32.def
    compiling generator.c
    generator.c: In function 'generate_json':
    generator.c:861:25: error: 'rb_cFixnum' undeclared (first use in this function); did you mean 'mFixnum'?
         } else if (klass == rb_cFixnum) {
                                     ^~~~~~~~~~
                                     mFixnum
    generator.c:861:25: note: each undeclared identifier is reported only once for each function it appears in
    generator.c:863:25: error: 'rb_cBignum' undeclared (first use in this function); did you mean 'rb_cFixnum'?
         } else if (klass == rb_cBignum) {
                                     ^~~~~~~~~~
                                     rb_cFixnum
    make: *** [Makefile:242: generator.o] Error 1

    make failed, exit code 2

    Gem files will remain installed in D:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.8.3 for inspection.
    Results logged to D:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/json-
    1.8.3/gem_make.out

## Steps to reproduce
Running `gem install json -v 1.8.3`

## What's the output from `ridk version`?
---
    ruby:
      path: D:/Ruby24-x64
      version: 2.4.1
      platform: x64-mingw32
    ruby_installer:
      package_version: 2.4.1-2
      git_commit: a2667ee
    msys2:
      path: D:\msys64
      title: MSYS2 64bit
      version: '20161025'
    cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.1.0
    sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)

**Comment by MSP-Greg** [comment]
@SuperMasterBlasterLaser

I don't believe 1.8.3 is compatible with 2.4.1, as the errors reference Fixnum & Bignum.  In the [JSON CHANGES FILE - 2015-09-11 (2.0.0)](https://github.com/flori/json/blob/master/CHANGES.md#2015-09-11-200), you'll see the line stating 'Implements compatibiliy to ruby 2.4 integer unification.'

Since this Ruby change happened after 1.8.3 was released, most gems would not update a previously released gem...

So, you can install older gems, but the may not correctly report that they're incompatible with 2.4.x.

**Comment by larskanis** [comment]
Yes, @MSP-Greg is right - json-2.0.0 fixes this issue. Please upgrade the json gem!

**Comment by MSP-Greg** [comment]
@larskanis 

FYI, the 2.4.1 build on [Appveyor](https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby)  (used gcc 6.3.0) has json 2.0.2.

**Comment by SuperMasterBlasterLaser** [comment]
So you mean that gem itself is not compatible with new version of interpreter?

**Comment by MSP-Greg** [comment]
@SuperMasterBlasterLaser 

json 1.8.3 is not compatible with 2.4.1.  2.4.1 has json 2.0.2 installed as a default gem.  If you haven't noticed, `gem list` should show it installed.  The Appveyor page linked to above shows the gems installed in several ruby versions...

**Comment by rivalak** [comment]
> Yes, @MSP-Greg is right - json-2.0.0 fixes this issue. Please upgrade the json gem!

Yes, @MSP-Greg is right, json-2.0.0 works for me too. Thank you guys.
