### ISSUE TITLE
The rubyinstaller web page says checksums are available from bintray, but there's no checksums for the latest release

### ISSUE THREAD

**Issue by jmfgdev** [oneclick/rubyinstaller2#63]
## What problems are you experiencing?

I want a checksum for rubyinstaller-2.4.1-2-x64.exe

The website says to check the bintray repos in the files tab for the latest checksums, but I'm not finding them there.

I apologize if I'm just not looking hard enough,
Could someone who has a copy quickly provide me with a sha256?
Thanks.

**Comment by MSP-Greg** [comment]
From most recent [appveyor](https://ci.appveyor.com/project/larskanis/rubyinstaller2-hbuor/build/1.0.165/job/60t4mn5avy9oygwl/artifacts)

SHA 75cf277730ee89c74882a6bd42255d0cbf9e2f703110eb81fff5e239cfdb4a24

Note - I downloaded it just like you...

**Comment by jmfgdev** [comment]
@MSP-Greg 

Thanks Greg,

That helps to know we have the same one but this doesn't really make us much safer, Ideally, we would have access to gpg signed sha256+sums from the developers when they release the installers.

**Comment by jmfgdev** [comment]
A little odd:

When I tried verifying the build you got from appveyor, it has the same name as the one from github but a different sum:

This is the sum of the github release:
6A09B3E912C1598E1AC3C1319427D888FF72933B2B19FC737406298228D39B94

This is the sum of the appveyor release:
75CF277730EE89C74882A6BD42255D0CBF9E2F703110EB81FFF5E239CFDB4A24

Both files are named:
rubyinstaller-2.4.1-2-x64.exe

**Comment by MSP-Greg** [comment]
They're different files.  The Appveyor artifacts are based on the last commit, and the files are build artifacts.  GitHub releases are created by the repo owners, who then can upload files.

So, if someone were to obtain credentials for the repo, they could easily upload files to GitHub.  Conversely, Appveyor would be a bit more difficult, as I don't think one can upload artifacts.  Then again, one could hide code in patch files, which could then be used for an Appveyor build, then when that's done, switch the patch files back to normal in GitHub.

So really, at some point, trust is involved, both in the owners and GitHub and Appveyor....

**Comment by jmfgdev** [comment]
I really hope someone who can make this possible sees this issue, because while at some point trust is involved is true, we can prolong that point farther back without much inconvenience

**Comment by larskanis** [comment]
@jmfgdev You're absolutely right - we currently don't provide checksums for RubyInstaller-2.4 downloads. More release automation is still on my agenda and I plan to add PGP signatures while being over it.

**Comment by jmfgdev** [comment]
Awesome, good to know it's in the works. Just for reference, this is my current sums signed with my key, obviously let me know if they're wrong but they should be right, downloaded on a freshly installed computer with https

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

This is the sum of the github release:
6A09B3E912C1598E1AC3C1319427D888FF72933B2B19FC737406298228D39B94

This is the sum of the appveyor release:
75CF277730EE89C74882A6BD42255D0CBF9E2F703110EB81FFF5E239CFDB4A24
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQIcBAEBCAAGBQJZiecUAAoJEE27bo5dd+wXEaAP+waud0UgrRKnJlznthg4AfU0
myysJjwuBbh9GhySM4z9BQeGLbD2FVznGtVbN7boSHaRyHY1msVeQGzV0Q/FaY4d
bWtCDKPCXUzas6smD5NNsQhdFzClYoDa6KPV4PvRfLlKAhlY7OK/coecywXop3I4
JnIoz7i+bR4ObcGLX9fXBtBq3vbx0HSsQ41fGymnvINHEn+gZ4UhYE+0jnfe23a2
Chp80e3xpikJ2c+vvSKuAvD2KhjkeYb4YV5V7k9BwDyyK2WGdovhqa12phW+vN/Y
57RQ3EhrbOFDGyqlqm5F6cUaXC7+rB0ww8xuSKVEBseONhIbxMbLJ55uHpudGKRR
axWAIxHIu13P3XOCxRL/iHvfZhqmonsWtGasgnaFsH8KAJeCTWsCzq/sbtqv5yQh
XcHA5ZcvrkVl4IDzjTRJ3peyTFdqZvQ8MK/ePPZ64h3019YvZGFB+wEZ5hpCBQdI
eBUToJwbA2nwlw8OpBzhvMOBMp7slMXGMj5XZJamOUwBZQR6Vig0j5ur8GMCDeGT
uuQj7J+v8OPbHRPub4dpEbZKNeBM/hWnlTeL69Dxwjnl2SDTslnzqFkc6d7LX+XF
azzeuEM8AiK0z/YnUDR4Z4vPm5pAbt9OiLqAT/MmRDhMQe+x8+PGKxSbhXYTgRQ2
sj/4ZhtAkPmV2uNf2u1t
=/JEP
-----END PGP SIGNATURE-----```
I hope this helps the next person out until sums from a developers trusted copy are posted

**Comment by larskanis** [comment]
First steps to signed release files are done https://github.com/oneclick/rubyinstaller2/commit/4ad61cc9cd0ce7068b8d26ce495350bcab71131c and documented [in the wiki](https://github.com/oneclick/rubyinstaller2/wiki/Maintainers%27-corner#release-a-new-rubyinstaller-version). I'll add the remaining parts to [the website](https://github.com/oneclick/rubyinstaller.org-website) later.

**Comment by jmfgdev** [comment]
Great to hear @larskanis

**Comment by larskanis** [comment]
It took awhile to provide GPG signatures and SHA-256 hashs, but now it's finished:

1. GPG signed release files are generated since https://github.com/oneclick/rubyinstaller2/commit/4ad61cc9cd0ce7068b8d26ce495350bcab71131c.
1. Hashs for all previous releases were verified in https://github.com/oneclick/rubyinstaller.org-website/commit/0810f0aa7df8b0311a351d60df6d41375a2c3575 (and it was 100% successfully) and signatures and SHA-256 hashs are shown since https://github.com/oneclick/rubyinstaller.org-website/commit/1af69c87c78a36bcb72c77b81c0cf1af8337a822 .
1. New releases can be published mostly automatic with their signatures and SHA-256 hashs since https://github.com/oneclick/rubyinstaller.org-website/commit/e0f99bd5ad21d217b150ae6b14c98d8f88baace3 .
1. The release procedure is documented [in the wiki](https://github.com/oneclick/rubyinstaller2/wiki/Maintainers%27-corner#release-a-new-rubyinstaller-version).
