### ISSUE TITLE
spec.metadata["msys2_mingw_dependencies"] may cause re-install over local packages

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#67]
Long story (someone wants to try it), but I'm trying to shove OpenSSL 1.1.0 into Ruby 2.3x by installing the OpenSSL gem.

I patched the not-really-started `digest` gem repo to build, then moved to Ruby OpenSSL.

I've got the 1.1.0f package installed locally.  Ran `geminstall`, and it started downgrading to 1.0.2l.

I think maybe [Ruby Installer:: Build:: Msys2Installation#install_packages](https://github.com/oneclick/rubyinstaller2/blob/master/lib/ruby_installer/build/msys2_installation.rb#L251-L265) should be querying for packages before installing?

I guess this is somewhat cryptic, but I suspect you know all the versions I'm referring to.  Too tired tonite, I'll look at it more tomorrow am...

**Comment by larskanis** [comment]
This is probably due to using `pacman -U mingw-openssl-1.1.0.tar.xz` instead of installing from a pacman repository. The downgrade shouldn't happen when OpenSSL is installed as described here: https://github.com/oneclick/rubyinstaller2-packages/blob/master/README.md#install-packages

**Comment by MSP-Greg** [comment]
Okay, then maybe the link shouldn't mention locally installed packages?

What happens when someone wants to test a locally created new version of one of the dependent packages (maybe OpenSSL 1.1.0g or gdbm 1.13)?

Finally, looking at the code, if this is patched, querying should probably be done in [resources/files/operating_system.rb](https://github.com/oneclick/rubyinstaller2/blob/4ad61cc9cd0ce7068b8d26ce495350bcab71131c/resources/files/operating_system.rb), not in `#install_packages`..

**Comment by MSP-Greg** [comment]
I've got code querying correctly, need to finish some version code.  When I'm finished, I'll post a link somewhere for you to consider.  Thanks,

**Comment by larskanis** [comment]
Issues should be closed when the corresponding fix is applied and with a link to it.

**Comment by MSP-Greg** [comment]
Your response was two sentences, and both could be construed to imply "you're doing it wrong".  It did not give me the impression that you felt a fix was required.

IMHO, MSYS2 is a separate piece of software and RI2 should not be defining how it's used or for what purposes, nor whether multiple copies should be installed/maintained.

**Comment by larskanis** [comment]
> It did not give me the impression that you felt a fix was required.

You're right:
1. I think this is a bug, that should be fixed
2. I didn't explain this so far

I would be pleased to receive a PR to fix this. However please note, that version strings like `libusb>=1.0.20` should still work as described [here](https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency).

**Comment by MSP-Greg** [comment]
I'm okay.  Going forward, if I think things are unclear, I'll say so, rather than closing an issue.

Back to this.  I read the description, and stopped.

1. The `>=` operator is listed.  I think it should it support a `<` operator, example being OpenSSL, especially when `digest` also compiles with it. One might want to update the OpenSSL gem, but match the `digest` OpenSSL version.  Should any other operators be supported?

2. The versions listed are what one might call the library version.   Should the MSYS2/MinGW revision (as in `-2` of `gdbm-1.10-2` be supported?  I vote no, but I'm open.  It's just more code...

3. Are you okay with a local query for the package, and if it exists, that nothing be done (assuming it meets version specs if included)?

RI has 217 forks.  Maybe that's not a lot given how long its been around, but it still represents a few hundred people that might have wanted something other than the standard builds.

Hence, I think we need `metadata["msys2_mingw_dependencies"]` to support newbies installing Ruby and Rails for the first time, but also not get in the way of advanced users wanting to control what packages are used in builds or gem updates.

I'll admit a bias, as having used trunk as my daily ruby, I have wrestled with bad version constraints in gems much too often.  Once we decide,  I'll have a look at revising the WIKI page.  Of course, given my bias, I'd want you to look at it...

Thanks.

**Comment by larskanis** [comment]
My intention was to simply use the [pacman semantics](https://www.archlinux.org/pacman/pacman.8.html) for dependency version requirements. So I added a link to [the wiki page](https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#msys2-library-dependency) to make that clear. I would like to avoid inventing anything new.

The only issue with the current state is, that `pacman --needed` should not install a package, if there's already a matching package installed. But it does, unless the version fits exactly the very first version of the named package in the pacman repository. Unfortunately I doubt, that this will be considered a pacman bug. I think this is a feature.

Regarding versioning: It is true that it's annoying when version requirements are overly pessimistic, especially when working on daily builds, but it prevents the ordinary user from struggling with mysterious error messages due to library incompatibilities. And it helps build systems (rubygems, bundler, pacman etc.) to pick the right versions.

**Comment by larskanis** [comment]
@MSP-Greg I finally fixed this issue in https://github.com/oneclick/rubyinstaller2/commit/b57236b24b702eced2bb79d84930f642883dca92 , so that you might remove [your patch](https://github.com/MSP-Greg/ruby-loco/blob/5c932d469a906f38c7bd1310bfc11f2759ac071c/patches/__operating_system.rb.patch) now.
