### ISSUE TITLE
gems - .so files not stripped

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#69]
When installing extension gems, none of the *.so files are stripped.

I'm not familiar enough with the gem/bundler build systems to know where the code should go.  I assume one could hook into a Gem callback/event?

I've tested several that I manually stripped, and all behave exactly as before.

**Comment by larskanis** [comment]
This is equal on all other platforms. Binary gems for Windows are often stripped before packages, like [in the ffi gem](https://github.com/ffi/ffi/blob/master/Rakefile#L192-L200), but this is not done for local builds.

If it shall be changed, that is something for the `mkmf.rb` file or possibly rubygems. Anyway this is not an issue of RubyInstaller.

**Comment by MSP-Greg** [comment]
Using trunk, I always have to build extension gems.  I may add code for strip to `operating_system.rb` and work with it for a while.  Given the wide variance in adoption of windows specific code (isn't that a nice way of saying...), it could be added to RI2.

Also, if 'we' used it for while, it gives credence to it working correctly.  Kind of like my using all the 'time' patches in my trunk builds, which still haven't been accepted <sigh>.

**Comment by larskanis** [comment]
If I remember correctly, there is also a gcc option to strip shared libraries at link time. It could be easily used as part of LDFLAGS.
