### ISSUE TITLE
Packman was installed with rubyinstaller additional product

### ISSUE THREAD

**Issue by dupls** [oneclick/rubyinstaller2#70]
I downloaded rubyinstaller-2.4.1-2-x86 and checked the box for additional components to be installed. My virus protector popped up preventing packman.exe being installed on my computer. I removed the folder and tried the same installer again this time without checking the box for additional components. Ruby installer downloaded without problems.
To confirm I have ruby 2.4.1p111 (2017-03-22 revision 58053 [i386-mingw32]

**Comment by larskanis** [comment]
It's true that AV products sometimes block downloads of exe files. In this case it's possible to install MSYS2 manually from http://msys2.org either as exe installer file or as plain archive into `c:/msys64` . After that you should re-run `ridk install ` to add missing development tools.

**Comment by larskanis** [comment]
Could you solve this issue?

**Comment by dupls** [comment]
As I mentioned yes I did. I removed the folder and tried the same installer without checking the box for additional components. Ruby installer downloaded this time without problems.
