### ISSUE TITLE
WIN32OLE is not working having issues....

### ISSUE THREAD

**Issue by DamienLyles** [oneclick/rubyinstaller2#71]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

I have code that drives IBM's PCOMM mainframe terminal emulator. My code works in 2.3.  However, in 2.4 I get the following error...

Error: failed to create WIN32OLE object from `PCOMM.autECLConnMgr'
    HRESULT error code:0x8007007e
      The specified module could not be found..
ERROR: Was not able to Launch a PCOM session. failed to create WIN32OLE object from `PCOMM.autECLConnMgr'
    HRESULT error code:0x8007007e
      The specified module could not be found.

## Steps to reproduce

$mgr = WIN32OLE.new('PCOMM.autECLConnMgr')

## What's the output from `ridk version`?

---
ruby:
  path: C:/Selenium_Ruby/runtime
  version: 2.4.1
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
msys2:
  path: C:\Selenium_Ruby\runtime\msys32
  title: MSYS2 32bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.2.0
sh: GNU bash, version 4.4.12(1)-release (i686-pc-msys)

**Comment by larskanis** [comment]
RubyInstaller-2.4 changed the way how DLLs are located: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#dll-loading

My guess is, that the OLE object needs to load a DLL, which is in one of the paths listed in the PATH environment variable. This worked in previous RubyInstaller versions, but now you must use one of the two options to add custom DLL paths, as described in the above article.

**Comment by larskanis** [comment]
RubyInstaller-2.4 changed the way how DLLs are located: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#dll-loading

My guess is, that the OLE object needs to load a DLL, which is in one of the paths listed in the PATH environment variable. This worked in previous RubyInstaller versions, but now you must use one of the two options to add custom DLL paths, as described in the above article.

**Comment by larskanis** [comment]
As a very first attempt you could try in a cmd shell:
```cmd
set RUBY_DLL_PATH=%PATH%
ruby your_winole_prog.rb
```

**Comment by DamienLyles** [comment]
That worked.  Thanks!
