### ISSUE TITLE
Not clear, using rubyinstaller inside existing MSYS2 environment

### ISSUE THREAD

**Issue by erikbgithub** [oneclick/rubyinstaller2#75]
Hi, I already have MSYS2 set up, and don't want to install again. But if I understand correctly your installer also installs MSYS2, right? What's the alternative if I have msys2 already working?

Thanks!

**Comment by larskanis** [comment]
You can usually use your MSYS2 setup with RubyInstaller2. It is found, if it's installed to c:/msys64 or c:/msys32, if it's installed per MSYS2 installer to any location or if it's installed as msys64 or msys32 inside the corresponding ruby directory.

Now however, that you still have to install required development tools per `ridk install`. It should detect an already installed MSYS2.

**Comment by erikbgithub** [comment]
Ah okay, so I install it on Windows as if I wouldn't have MSYS2. And then the installer will detect there is an MSYS2 and do the corresponding steps to deploy it into the MSYS2 environment. Thanks, I'll try that.

Do you think this could be documented somewhere?

**Comment by shviller** [comment]
Can the people who have MSYS2 installed elsewhere have an option to manually specify its location, please?

**Comment by larskanis** [comment]
@shviller The MSYS2 lookup code is [here](https://github.com/oneclick/rubyinstaller2/blob/master/lib/ruby_installer/build/msys2_installation.rb#L7).
1. You can use the MSYS2 installer to store MSYS2 to the desired location. The install path is then stored in the registry and MSYS2 is found at this location
2. You can add the MSYS2 path (the base/root directory) to the `PATH` environment variable
3. You can set a link to your location like so: `mklink /D c:\msys64 d:\your\special\path\msys`
