### ISSUE TITLE
Pacman failed when selection option 3

### ISSUE THREAD

**Issue by phoenixfangor** [oneclick/rubyinstaller2#76]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
Pacman failed to install when selection 3 was used.

## Steps to reproduce
After installing ruby, RubyInstaller2 for Windows prompted me to install 1, 2, or 3.
I chose 3. MSYS2 failed when pacman failed to install.

## What's the output from `ridk version`?
![image](https://user-images.githubusercontent.com/1885171/30172753-4eb06400-93bb-11e7-8f5b-e82eb7e50c68.png)

NOTE: If I select to install 1 and then 2, things seem to work fine.

**Comment by larskanis** [comment]
The error message indicates that option 2 wasn't selected. See also issue #57

**Comment by phoenixfangor** [comment]
@larskanis Seems like a dupe, then. Sorry! Left a comment on #57.

**Comment by MSP-Greg** [comment]
As a possible solution, maybe leave 'If unsure press ENTER' and add a 4th option 'All of the above` ?
