### ISSUE TITLE
a silent/unattended installation of MSYS2

### ISSUE THREAD

**Issue by flavorjones** [oneclick/rubyinstaller2#79]
## What problems are you experiencing?

Unattended installation (e.g., on a headless system) of MSYS2 via `ridk install 1 2 3` cannot complete, because the MSYS2 installer launches a wizard by default.

## What do you suggest?

The MSYS2 project provides a script, [`auto-install.js`](https://github.com/msys2/msys2-installer/blob/master/auto-install.js), that can be used to do a headless install, so long as some command-line parameters are passed in.

## Would you like to submit a PR?

I sure would! I'd like some guidance, though, on how you'd like me to handle the `auto-install.js` script in the PR.

1. Add a file to the repo, under `resources/files` ... but then I need help finding that file (would we install it?).
2. Place the file contents into a string and write it to a temp file for use of the MSYS2 installer. Ugly but I know how to do this without help.

Which option would you prefer? Or is there a third option you can guide me on?

## Anything else?

Uh, MSYS2 doesn't have a clear license, and so unfortunately the `auto-install.js` file also doesn't have a clear license. This worries me.

**Comment by larskanis** [comment]
Hi Mike! I equally thought about `auto-install.js` some times ago. The main reason the install wizard is used, is to give the user the choice to select a target install directory for MSYS2.

In fact it's not necessary to install MSYS2 per `ridk install`. It's OK to download and unpack the [xz-file](http://repo.msys2.org/distrib/) to a directory which is [found by the RubyInstaller runtime library](https://github.com/oneclick/rubyinstaller2/blob/master/lib/ruby_installer/build/msys2_installation.rb#L32-L65). Or to use the MSYS2 installer with `auto-install.js`, which has the advantage that it can be installed to any directory, because the selected path is written to the Windows registry. After that `ridk install 2 3` can be invoked to install all the required development packages.

Regarding silent `ridk install` I could imagine to use `auto-install.js` or xz-file as soon as `ridk install` is executed with parameters. But I'm not sure about how the destination directory should be chosen.

**Comment by flavorjones** [comment]
Ah, thanks for the pointers -- I'd actually be happy to install MSYS2 directly to a findable location, let me try that and comment here if I have more questions.

**Comment by emachnic** [comment]
@flavorjones Please let me know if you're able to figure out how to silently install msys2 or if installing to a findable location works. I've been trying to figure this out for the rubyinstaller Chef cookbook and RailsInstaller.

**Comment by flavorjones** [comment]
@larskanis I've installed MSYS2 into a detectable directory, and RubyInstaller finds it. However, I'm having a great deal of trouble getting `pacman` keys set up correctly.

When I run `pacman-key --init` I see something good:

```
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: Generating pacman keyring master key...
gpg: skipping control `%no-protection' ()
.....+++++
.+++++
gpg: key 186AD9DA marked as ultimately trusted
gpg: Done
==> Updating trust database...
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
```

but then subsequently running `ridk install 2 3` results in:

```
already installed
MSYS2 system update part 1  ...
> pacman -Syu --needed --noconfirm
error: mingw32: key "5F92EFC1A47D45A1" is unknown
:: Import PGP key 2048D/AD351C50AE085775EB59333B5F92EFC1A47D45A1, "Alexey Pavlov (Alexpux) <alexpux@gmail.com>", created: 2013-11-11? [Y/n] error: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust

:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
error: mingw32: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
downloading mingw64.db...
downloading mingw64.db.sig...
error: mingw64: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
downloading msys.db...
downloading msys.db.sig...
error: msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is unknown trust
error: failed to update msys (invalid or corrupted database (PGP signature))
error: failed to synchronize any databases
error: failed to init transaction (invalid or corrupted database (PGP signature))
MSYS2 system update failed
 _____       _           _____           _        _ _         ___  
|  __ \     | |         |_   _|         | |      | | |       |__ \ 
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ / 
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_ 
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _                              
                   |___/          _|_ _  __   | | o __  _| _     _ 
                                   | (_) |    |^| | | |(_|(_)\^/_> 

MSYS2 seems to be c:/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/components/02_pacman_update.rb:19:in `block in execute': pacman failed (RuntimeError)
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/msys2_installation.rb:190:in `with_msys_apps_enabled'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/components/02_pacman_update.rb:14:in `execute'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/task.rb:181:in `invoke'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:153:in `invoke_task'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block (2 levels) in top_level'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `each'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:109:in `block in top_level'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:118:in `run_with_threads'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/gems/2.4.0/gems/rake-12.1.0/lib/rake/application.rb:103:in `top_level'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/components_installer.rb:34:in `install'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:99:in `install'
	from c:/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/ruby_installer/runtime/ridk.rb:14:in `run!'
	from c:/var/vcap/packages/ruby-2.4/bin/ridk.cmd:32:in `<main>'
```

At this point I'm not sure if it's a pacman issue, or an issue initializing keys improperly, or if RubyInstaller is assuming something else ... any ideas?

**Comment by MSP-Greg** [comment]
@flavorjones 

Been a while since I started from nil (hence, I don't recall my installation), but maybe
```
pacman-key --lsign-key 5F92EFC1A47D45A1
```

I think both Lars and I have needed/used something similar to add our keys for package additions...

The full code I have in a script is:
```
bash -lc "pacman-key -r 77D8FA18 && pacman-key -f 77D8FA18 && pacman-key --lsign-key 77D8FA18"
```

**Comment by flavorjones** [comment]
Ah, OK, if I run `pacman-key --populate msys2` then I get past this error ... I think that's all I need. If so, I'll update this issue with my final procedure for making this work and close it.

**Comment by flavorjones** [comment]
OK, final version of my powershell script to install everything headless is here:

https://github.com/flavorjones/windows-ruby-dev-tools-release/blob/master/packages/ruby-2.4/packaging

but that's running the context of BOSH release package compilation, and may be hard to understand for anyone unfamiliar with BOSH.

So the TL;DR is:

1. run `rubyinstaller` with arguments `/verysilent` and `/dir=c:\path\to\target\ruby\dir`
2. verify that `ruby.exe --version` works to validate installation
3. extract the `msys2` xz archive into `c:\path\to\target\ruby\dir\msys64` which will be found by the rubyinstaller scripts according to [this line](https://github.com/oneclick/rubyinstaller2/blob/master/lib/ruby_installer/build/msys2_installation.rb#L38)
4. run `ridk exec bash.exe pacman-key --init`
5. run `ridk exec bash.exe pacman-key --populate msys2`
6. run `ridk install 2 3`
7. verify it all worked by running `ruby.exe -rdevkit -e 'puts 1234'`

**Comment by larskanis** [comment]
@flavorjones Sorry I forgot to mention the MSYS2 init step! Good to know you could solve this issue, but I recommend to replace

```sh
ridk exec bash.exe pacman-key --init
ridk exec bash.exe pacman-key --populate msys2
```
by
```sh
ridk exec bash -lc true
```

The latter form triggers the full initialization step of MSYS2 - the gpg setup is only a part of it.

All-in-all this seems to be difficult enough to legitimate an extension to `ridk install`, which automates these steps. However a plain MRI setup can not extract a `*.tar.xz` file. Did you repack the file to `*.zip`?

**Comment by flavorjones** [comment]
How does this line work?

```
ridk exec bash -lc true
```

That's ... not obvious.

**Comment by flavorjones** [comment]
And yes, I repacked the `.xz` file to a `.zip` file. :-\

**Comment by majkinetor** [comment]
This seems set directory via auto-install.js:


```javascript
Controller.prototype.PerformInstallationPageCallback = function()
{
    InstallDir = "c:\\msys"
    installer.setValue("TargetDir", InstallDir)

    var page = gui.pageWidgetByObjectName("PerformInstallationPage");
    gui.clickButton(buttons.NextButton);
}
```

**Comment by majkinetor** [comment]
I automated this via new chocolatey package:
https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/automatic/msys2

**Comment by larskanis** [comment]
@majkinetor Thank you for your efforts on MSYS2 and Ruby integration. Let me know, if there is anything to be improved for better compatibility to chocolatey!

**Comment by majkinetor** [comment]
@larskanis 

No problem. Feel free to do the same for choco package. 

I initially thought that you can consider using the [same method of installation](https://github.com/chocolatey/chocolatey-coreteampackages/blob/d97ba1d8e31a9d87ff010bb71c0cb9746e647bab/automatic/msys2/tools/chocolateyinstall.ps1#L12-L38) with `ridk install 1` (not use the installer but download xz directly, unpack it, initialize it, and register path), if you don't want users to depend on choco for msys2. That would require 7z and proxy handling so its probably best left for separated project. 

This package is [automatic](https://github.com/chocolatey/chocolatey-coreteampackages/blob/d97ba1d8e31a9d87ff010bb71c0cb9746e647bab/automatic/msys2/update.ps1) which means that it will always follow upstream releases in a matter of hours.

You could mention in the documentation about choco package.

**Comment by larskanis** [comment]
@majkinetor OK, I added Chocolatey to the [FAQ](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-choco-install) and the [README](https://github.com/oneclick/rubyinstaller2/blob/master/README.md#using-the-installer-on-a-target-system).
