### ISSUE TITLE
Windows Ruby 64 fails to create BlueZone object.

### ISSUE THREAD

**Issue by Dave567** [oneclick/rubyinstaller2#80]
We are using Rocket BlueZone Terminal Emulator. But issue is, Ruby64 is not able to create BlueZone object but same code runs perfectly fine with Ruby32. Can someone please help to fix Ruby64?
OS - Windows 10.

Code -
require 'win32ole'
class BZExtra

def start_extra_sys
@System = WIN32OLE.new('BlueZone.System') #Fail on this line .
sessions = @system.Sessions
session = sessions.Open('path')
session.WindowState = window_state
session.Visible = visible
end
end

Error -
WIN32OLERuntimeError: failed to create WIN32OLE object from `BlueZone.System'
HRESULT error code:0x80040154
Class not registered

Note- For some reason only this BlueZone is failing, when I try Excel application it works fine.

**Comment by larskanis** [comment]
OLE objects are dynamically linked into the process. That means that they have to be be available for the same architecture as the running process. If you're running ruby-x64 then you'll need the component as x64 as well.

There are some solutions to overcome this limitation (found by a quick google search):
1. https://techtalk.gfi.com/32bit-object-64bit-environment/
2. https://stackoverflow.com/questions/359331/access-x86-com-from-x64-net

Alternatively you could run a x86 ruby subprocess from your x64 ruby main process which calls the OLE object through WIN32OLE and you connect to the x86-subprocess by DRb. However this requires both x86 and x64 ruby versions to be installed and is probably far more difficult then the COM surrogate solution.

**Comment by Dave567** [comment]
Thank you Larskanis, issue resoved.

**Comment by larskanis** [comment]
Can you describe how you solved this issue?

**Comment by Dave567** [comment]
I followed steps mentioned in: https://techtalk.gfi.com/32bit-object-64bit-environment/

Thanks,
Dave

**Comment by larskanis** [comment]
OK, good to know!
