### ISSUE TITLE
Building puma with SSL support

### ISSUE THREAD

**Issue by vais** [oneclick/rubyinstaller2#81]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
I was hoping building puma with SSL support would finally start "just-working(tm)" now that we use msys2, but no such luck...

## Steps to reproduce
E.g. doing `gem install puma --platform ruby -- --use-system-libraries` then trying to run it in SSL mode currently barfs out the following `SSL not available in this build` error:
```
C:\Users\Administrator\Desktop>puma -b "ssl://127.0.0.1:9292?key=path_to_key&cert=path_to_cert"
*** SIGUSR2 not implemented, signal based restart unavailable!
*** SIGUSR1 not implemented, signal based restart unavailable!
*** SIGHUP not implemented, signal based logs reopening unavailable!
Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
* Min threads: 0, max threads: 16
* Environment: development
C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/binder.rb:149:in `check': SSL not available in this build (StandardError)
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/binder.rb:149:in `block in parse'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/binder.rb:88:in `each'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/binder.rb:88:in `parse'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/runner.rb:144:in `load_and_bind'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/single.rb:87:in `run'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/launcher.rb:183:in `run'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/lib/puma/cli.rb:77:in `run'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/lib/ruby/gems/2.4.0/gems/puma-3.10.0/bin/puma:10:in `<top (required)>'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/bin/puma:23:in `load'
        from C:/Ruby/rubyinstaller-2.4.2-2-x86/bin/puma:23:in `<main>'
```
Tried various combinations, with and without `-- --use-system-libraries`, to no avail... Does anyone know the magic incantation to install puma with SSL support under rubyinstaller2? :pray: 

## What's the output from `ridk version`?
---
ruby:
  path: C:/Ruby/rubyinstaller-2.4.2-2-x86
  version: 2.4.2
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.2-2
  git_commit: a1b07ad
msys2:
  path: c:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.2.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]

**Comment by MSP-Greg** [comment]
@vais

Does `ridk exec pacman -Q openssl` show an installed package?

If not, you need to install the package.  If you have EM installed, might re-install that afterwards also, as it can use OpenSSL also...

No one has gotten to the Puma repo and added the metadata info for RI2 to automatically install the OpenSSL package...

**Comment by vais** [comment]
Hi, @MSP-Greg, here's what I got:
```
C:\Users\Administrator>ridk exec pacman -Q openssl
openssl 1.0.2.l-2
```

> If you have EM installed, might re-install that afterwards also, as it can use OpenSSL...

Nope, no EM installed...

> No one has gotten to the Puma repo and added the metadata info for RI2 to automatically install the OpenSSL package...

I wouldn't know where to start...

**Comment by MSP-Greg** [comment]
You've got the OpenSSL package installed.  I opened an issue https://github.com/puma/puma/issues/1428

The puma [appveyor.yml file](https://github.com/puma/puma/blob/master/appveyor.yml#L4) seems to shut off SSL support, but I'm not sure why.  I'm afraid I won't be able to look at it for several hours...

**Comment by vais** [comment]
@MSP-Greg thank you so much for looking into it!

**Comment by MSP-Greg** [comment]
@vais

Okay. A few items:

>puma -b "ssl://127.0.0.1:9292?key=path_to_key&cert=path_to_cert"

1. For that command line to work, `path_to_key` and `path_to_cert` need to be replaced with file names which contain cert and key info.

2. When compiling extension gems, the authors have a mechanism to check the existence of libraries and include files.  When installing puma, the console output is as below (the three yes's are what's important)-
```
checking for BIO_read() in -lcrypto... yes
checking for SSL_CTX_new() in -lssl... yes
checking for openssl/bio.h... yes
creating Makefile
```

If you remove puma, and then re-install, you should have output matching that.

I have puma building on appveyor, and although it builds with ssl, ruby 2.2 thru 2.5 are all failing many ssl tests.  I posted an issue on it, we'll see if anyone responds...

**Comment by MSP-Greg** [comment]
@vais @juliancheal

SSL on Puma is now working correctly.  Until a new release is done, you can always fork the repo, build the gem, then `gem install` from the local gem file.  I think there's an easier way to do it, but whenever I need to do it, it's because it doesn't work in the first place...

I ran up a Puma SSL server with the repo of my doc site, I could connect from my desktop and an iPad.  Note that running an SSL server locally is slower than running just an http server...

**Comment by vais** [comment]
@MSP-Greg @juliancheal So awesome, thank you guys! And this is why RubyInstaller2 rocks - it's finally starting to feel like Ruby on Windows is treated like a first-class citizen.
