### ISSUE TITLE
Shebang line 2.4.2-2 x86 build bin folder files

### ISSUE THREAD

**Issue by MSP-Greg** [oneclick/rubyinstaller2#83]
Small issue (and probably not one in most instances)...

Many of the shebang lines in the bin folder start with:
```
#!/mingw32/bin/ruby
```

except `ridk.cmd` and `ridk.ps1`, which start with:
```
#!/mingw64/bin/ruby
```

FYI & thanks.

**Comment by larskanis** [comment]
The shebang line in cmd and ps1 files has only one purpose: to satisfy the `ruby -x` option. Since it's not the first line in the file, it will not be recognized by bash. The actual path doesn't matter therefore.

Did you encounter an issue caused by this path?

**Comment by larskanis** [comment]
OK. Thank you nevertheless for highlighting such things!

**Comment by MSP-Greg** [comment]
> OK. Thank you nevertheless for highlighting such things!

Software has become (for good reason) very test focused.  Years ago, my studies were engineering/math, so I've got a different background as to system stability.  Hence, I may mention small issues because they could point to stability issues.  Notice the 'could'...  Thanks.
