### ISSUE TITLE
Error no such file ...@ rb_sysopen - scss

### ISSUE THREAD

**Issue by ludasmokva** [oneclick/rubyinstaller2#84]
## What problems are you experiencing?
Error appeared recently when activating watch command in cmd. Watch command for scss now not working properly.

## Steps to reproduce
I initiated command:  sass --watch scss:css  
Response by cmd: Sass is watching for changes. Press Ctrl-C to stop.  _{this is ok - always had this}_
Recent addition: error No such file or directory @ rb_sysopen - scss  _{this is new; appears after above line. }_

## What's the output from `ridk version`?
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.2
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.2-2
  git_commit: a1b07ad
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.2.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]

OTHER NOTES:

1. The 'watch' command used to work fine. Now when I save the scss file, the cmd recognizes/notes the change but does not update the css file. This is new. This used to work fine. To my knowledge, there haven't been any updates/changes to either the text editor (Brackets) or the Ruby version.
However, I have had the text editor crash twice for no apparent reason. I am not sure if the editor crashed or the cmd window crashed. Both happened while I was afk so the crash was not a result of any specific command or action. Although both the cmd and editor had been open for awhile without any activity (over 24 hours) so the crash could have simply been a result of some kind of built in win task/event. Again, not sure. I simply closed both windows and restarted without any real issue that I could find. But this 'error' appeared for the first time in my most recent attempt (a few hours ago) to initiate the watch command.

2. I ran the ridk install 1 2 3;  I am not familiar with the program enough to interpret the results, but a few items stood out that may or may not be relevant:
pacman -Syu --needed  -no confirm
pacman -Su --needed  -no confirm
and numerous warnings:: autoconf /automake1/mingw... skipping

The final line said: MSYS2 and MINGW development toolchain succeeded

Not sure if any of that is relevant. I can certainly paste/send you the full details but did not want to include them here at this time in case you don't need it.

Soooo... my question: Wtf happened and how can I fix it? :)

**Comment by larskanis** [comment]
Is this issue still relevant?

**Comment by ludasmokva** [comment]
I would say no for now. I'm sure you have better things to do. :)
Although a hard boot did not seem to work, I had a power outage that shut down my comp and now the command seems to work ok... strange but true. 
Welcome to my life. ;)
I would be lying if I said I was confident in it, but uncomplicated commands seem to be copying so I would just say forget it. If it happens again, I'll write in, and you can ignore it again.  
(hehe... sorry about the dig, couldn't help myself)

**Comment by larskanis** [comment]
So I'm going to close it. Sorry I can't help everyone. I'm doing all the work on OSS just for fun in my spare time for no money at all...

**Comment by ludasmokva** [comment]
No apologies necessary. You are completely awesome for doing what you do,
and although you probably do not hear it enough, it is very much
appreciated.
I didn't bug you for that very reason.
My little aside was meant as a little joke... and obviously clearly
illustrates that I should never pursue a career as a comedian.
Thank you for touching base to check up on the status.
And thank you for all your efforts.
Cheers.
