### ISSUE TITLE
How to copy nokogiri to new Ruby install?

### ISSUE THREAD

**Issue by vnluc** [oneclick/rubyinstaller2#87]
## How to copy nokogiri to new Ruby version?

I install Ruby 2.5 and installed nokogiri which work fine for me. But when I download new Ruby version, I try to copy nokogiri from old version to this new install but it does not work. So can you clarify the following for me?

**1)	When we install a library such as**
   ridk exec pacman -S mingw-w64-x86_64-libxslt
    
  Where it physically install these file to?
  
**2) When building gem with --use-system-libraries option. how it affect gem setup and layout?**

gem install nokogiri --platform ruby -- --use-system-libraries

  When I open build_info folder, I see this option in the .info file.
  What else it change?

**3) Why copy gem  (I do xcopy for to copy all new file from the old install folder) not work?**
   I expect it copied the gem setting, built gem files, and library also.

## What's the output from `ridk version`?
ruby:
  path: D:/ruby/ruby_packages_nobk/rubyinstaller-2.5.0-snapshot-x64_2017.10.31
  version: 2.5.0
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.0-snapshot
  git_commit: bbbf666
msys2:
  path: D:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.1.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]

**Comment by larskanis** [comment]
In general it's not safe to copy C extension libraries between ruby minor versions (2.4 -> 2.5) or within a development branch (current 2.5). You have to reinstall the gem in this case.

1) into several directories under your MSYS2 directory (d:/msys64)

2) into the ruby lib directory. Make a copy and check the diff before and after the gem install, to see the changes.

3) see above

**Comment by vnluc** [comment]
Thank you. I think that should be good also, compile gem again to get latest library built is best.

**Comment by larskanis** [comment]
Yes. Is it OK to close the ticket?

**Comment by vnluc** [comment]
Yes, thank you @larskanis 
it should be closed. Actually it is not an issue of RubyInstaller2. It is just general question.
