### ISSUE TITLE
MSYS2 + MINGW fails to install properly

### ISSUE THREAD

**Issue by stakach** [oneclick/rubyinstaller2#88]
I solved the problem by running the pacman install again, except I removed the `mingw-w64-x86_64-winstorecompat-git` package

## What problems are you experiencing?

```shell
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autoconf2.13 ...
warning: file-5.28-2 is up to date -- skipping
warning: gawk-4.1.4-1 is up to date -- skipping
warning: grep-2.26-1 is up to date -- skipping
warning: m4-1.4.17-4 is up to date -- skipping
warning: sed-4.2.2-2 is up to date -- skipping
warning: wget-1.18-1 is up to date -- skipping
error: target not found: mingw-w64-x86_64-winstorecompat-git
Install MSYS2 and MINGW development toolchain failed
Installation failed: pacman failed
```

## Steps to reproduce

`ridk install` on a fresh install

## What's the output from `ridk version`?

```
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.2
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.2-2
  git_commit: a1b07ad
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.2.0
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.15063]
```

**Comment by larskanis** [comment]
If winstorecompat can not be found, it usually means, that the package database isn't up-to-date. So it seems to me, that `ridk install 2` wasn't executed?

**Comment by stakach** [comment]
Literally a fresh install of windows and ruby installer.
`ridk install` is executed as part of the installation - not super hard to check.

`pacman -S --needed --noconfirm mingw-w64-x86_64-winstorecompat-git` will fail

**Comment by larskanis** [comment]
Did you choose ridk install option 3 alone? Option 2 updates the package database (`pacman -Sy`) and must be called first. Alternatively just pressing enter in `ridk install` makes sure that all tools are installed properly. See also [this stackoverflow question](https://stackoverflow.com/questions/44229081/what-do-these-rubyinstaller-2-4-components-do) .

**Comment by stakach** [comment]
I didn't select option 2... Also sorry that my last message was a bit blunt (uncool of me) and thanks for the work you've put into this project. It is hugely useful!

So I guess that solves the issue.
I do still think the instructions seem to indicate that step 2 is optional especially since step 3 also runs step 1 - maybe updating the text to say something like "**On initial installation run each step in order**" and change the wording of step 3 to "**install MingW development toolchain**" even though it does more

**Comment by larskanis** [comment]
I removed package `winstorecompat-git` from default dev tools in commit 50100e263ede, so that option 2 is now optional. Thanks for highlighting this!
