### ISSUE TITLE
Error:build gem native extension. window10 

### ISSUE THREAD

**Issue by yyliuqu** [oneclick/rubyinstaller2#98]
@larskanis thank you. I have installed DevKit msys-x64, and under the repository c:\msys-x64 use commend line: 

    gem install ruby-debug  
and      

    gem install ruby-debug-base     

but the same error happens ... 

## What problems are you experiencing?

    C:\User>gem install jekyll bundler
    Temporarily enhancing PATH for MSYS/MINGW...
    Building native extensions. This could take a while...
    ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/bin/ruby_builtin_dlls/Ruby24-x64/lib/ruby/g
    ems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
    C:/Ruby24-x64/bin/ruby_builtin_dlls/Ruby24-x64/bin/ruby.exe -r ./siteconf2018020
     8-16540-p4iye0.rb extconf.rb
     creating Makefile

    current directory: C:/Ruby24-x64/bin/ruby_builtin_dlls/Ruby24-x64/lib/ruby/gems/
     2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
     make "DESTDIR=" clean
     'make' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
    ���������ļ���

    current directory: C:/Ruby24-x64/bin/ruby_builtin_dlls/Ruby24-x64/lib/ruby/gems/
    2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
    make "DESTDIR="
    'make' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
     ���������ļ���

     make failed, exit code 1

    Gem files will remain installed in C:/Ruby24-x64/bin/ruby_builtin_dlls/Ruby24-x6
    4/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
    Results logged to C:/Ruby24-x64/bin/ruby_builtin_dlls/Ruby24-x64/lib/ruby/gems/2
    .4.0/extensions/x64-mingw32/2.4.0/http_parser.rb-0.6.0/gem_make.out
    Fetching: bundler-1.16.1.gem (100%)
     bundler's executable "bundle" conflicts with C:/Ruby24-x64/bin/ruby_builtin_dlls
    /Ruby24-x64/bin/bundle

**Comment by larskanis** [comment]
The error message isn't readable, so that it's hard to diagnose the issue. Perhaps try another codepage in the console, so that the error message becomes readable:
```
chcp 850
gem inst jekyll
```

The error with bundler should disappear when running:
```
gem inst bundler -f
```

**Comment by larskanis** [comment]
RubyInstaller-2.4 requires MSYS2. You should use `ridk install` to install it. The old DevKit doesn't work.

**Comment by larskanis** [comment]
Is this issue solved? If so I would like to close it.
